// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package imapdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearImapAccountSyncError = `-- name: ClearImapAccountSyncError :exec
UPDATE RAC_user_imap_accounts
SET last_error = NULL,
	last_error_at = NULL,
	updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) ClearImapAccountSyncError(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearImapAccountSyncError, accountID)
	return err
}

const countImapMessagesByUserAndAccount = `-- name: CountImapMessagesByUserAndAccount :one
SELECT COUNT(m.id)::bigint
FROM RAC_user_imap_messages m
JOIN RAC_user_imap_accounts a ON a.id = m.account_id
WHERE m.account_id = $1::uuid
  AND a.user_id = $2::uuid
`

type CountImapMessagesByUserAndAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountImapMessagesByUserAndAccount(ctx context.Context, arg CountImapMessagesByUserAndAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImapMessagesByUserAndAccount, arg.AccountID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadImapMessagesByUser = `-- name: CountUnreadImapMessagesByUser :one
SELECT COUNT(m.id)::bigint
FROM RAC_user_imap_messages m
JOIN RAC_user_imap_accounts a ON a.id = m.account_id
WHERE a.user_id = $1::uuid
  AND m.seen = FALSE
`

func (q *Queries) CountUnreadImapMessagesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadImapMessagesByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createImapAccount = `-- name: CreateImapAccount :one
INSERT INTO RAC_user_imap_accounts (
	user_id,
	email_address,
	imap_host,
	imap_port,
	imap_username,
	imap_password_encrypted,
	smtp_host,
	smtp_port,
	smtp_username,
	smtp_password_encrypted,
	smtp_from_email,
	smtp_from_name,
	folder_name,
	enabled
) VALUES (
	$1::uuid,
	$2::text,
	$3::text,
	$4::int,
	$5::text,
	$6::text,
	$7::text,
	$8::int,
	$9::text,
	$10::text,
	$11::text,
	$12::text,
	$13::text,
	$14::bool
)
RETURNING id, user_id, email_address, imap_host, imap_port, imap_username, imap_password_encrypted, folder_name, enabled, last_sync_at, last_error, last_error_at, created_at, updated_at, smtp_host, smtp_port, smtp_username, smtp_password_encrypted, smtp_from_email, smtp_from_name
`

type CreateImapAccountParams struct {
	UserID                pgtype.UUID `json:"user_id"`
	EmailAddress          string      `json:"email_address"`
	ImapHost              string      `json:"imap_host"`
	ImapPort              int32       `json:"imap_port"`
	ImapUsername          string      `json:"imap_username"`
	ImapPasswordEncrypted string      `json:"imap_password_encrypted"`
	SmtpHost              pgtype.Text `json:"smtp_host"`
	SmtpPort              pgtype.Int4 `json:"smtp_port"`
	SmtpUsername          pgtype.Text `json:"smtp_username"`
	SmtpPasswordEncrypted pgtype.Text `json:"smtp_password_encrypted"`
	SmtpFromEmail         pgtype.Text `json:"smtp_from_email"`
	SmtpFromName          pgtype.Text `json:"smtp_from_name"`
	FolderName            string      `json:"folder_name"`
	Enabled               bool        `json:"enabled"`
}

func (q *Queries) CreateImapAccount(ctx context.Context, arg CreateImapAccountParams) (RacUserImapAccount, error) {
	row := q.db.QueryRow(ctx, createImapAccount,
		arg.UserID,
		arg.EmailAddress,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapUsername,
		arg.ImapPasswordEncrypted,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPasswordEncrypted,
		arg.SmtpFromEmail,
		arg.SmtpFromName,
		arg.FolderName,
		arg.Enabled,
	)
	var i RacUserImapAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailAddress,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUsername,
		&i.ImapPasswordEncrypted,
		&i.FolderName,
		&i.Enabled,
		&i.LastSyncAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPasswordEncrypted,
		&i.SmtpFromEmail,
		&i.SmtpFromName,
	)
	return i, err
}

const deleteImapAccountByUser = `-- name: DeleteImapAccountByUser :execrows
DELETE FROM RAC_user_imap_accounts
WHERE id = $1::uuid
  AND user_id = $2::uuid
`

type DeleteImapAccountByUserParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteImapAccountByUser(ctx context.Context, arg DeleteImapAccountByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteImapAccountByUser, arg.AccountID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteImapMessageMetadataByUID = `-- name: DeleteImapMessageMetadataByUID :exec
DELETE FROM RAC_user_imap_messages
WHERE account_id = $1::uuid
  AND uid = $2::bigint
`

type DeleteImapMessageMetadataByUIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Uid       int64       `json:"uid"`
}

func (q *Queries) DeleteImapMessageMetadataByUID(ctx context.Context, arg DeleteImapMessageMetadataByUIDParams) error {
	_, err := q.db.Exec(ctx, deleteImapMessageMetadataByUID, arg.AccountID, arg.Uid)
	return err
}

const getImapAccountByUser = `-- name: GetImapAccountByUser :one
SELECT id, user_id, email_address, imap_host, imap_port, imap_username, imap_password_encrypted, folder_name, enabled, last_sync_at, last_error, last_error_at, created_at, updated_at, smtp_host, smtp_port, smtp_username, smtp_password_encrypted, smtp_from_email, smtp_from_name
FROM RAC_user_imap_accounts
WHERE id = $1::uuid
  AND user_id = $2::uuid
`

type GetImapAccountByUserParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetImapAccountByUser(ctx context.Context, arg GetImapAccountByUserParams) (RacUserImapAccount, error) {
	row := q.db.QueryRow(ctx, getImapAccountByUser, arg.AccountID, arg.UserID)
	var i RacUserImapAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailAddress,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUsername,
		&i.ImapPasswordEncrypted,
		&i.FolderName,
		&i.Enabled,
		&i.LastSyncAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPasswordEncrypted,
		&i.SmtpFromEmail,
		&i.SmtpFromName,
	)
	return i, err
}

const getImapMaxUID = `-- name: GetImapMaxUID :one
SELECT COALESCE(MAX(uid), 0)::bigint
FROM RAC_user_imap_messages
WHERE account_id = $1::uuid
  AND folder_name = $2::text
`

type GetImapMaxUIDParams struct {
	AccountID  pgtype.UUID `json:"account_id"`
	FolderName string      `json:"folder_name"`
}

func (q *Queries) GetImapMaxUID(ctx context.Context, arg GetImapMaxUIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getImapMaxUID, arg.AccountID, arg.FolderName)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getImapMessageSizeByUID = `-- name: GetImapMessageSizeByUID :one
SELECT size_bytes
FROM RAC_user_imap_messages
WHERE account_id = $1::uuid
  AND uid = $2::bigint
LIMIT 1
`

type GetImapMessageSizeByUIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Uid       int64       `json:"uid"`
}

func (q *Queries) GetImapMessageSizeByUID(ctx context.Context, arg GetImapMessageSizeByUIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getImapMessageSizeByUID, arg.AccountID, arg.Uid)
	var size_bytes int64
	err := row.Scan(&size_bytes)
	return size_bytes, err
}

const listImapAccountsByUser = `-- name: ListImapAccountsByUser :many
SELECT id, user_id, email_address, imap_host, imap_port, imap_username, imap_password_encrypted, folder_name, enabled, last_sync_at, last_error, last_error_at, created_at, updated_at, smtp_host, smtp_port, smtp_username, smtp_password_encrypted, smtp_from_email, smtp_from_name
FROM RAC_user_imap_accounts
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListImapAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]RacUserImapAccount, error) {
	rows, err := q.db.Query(ctx, listImapAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacUserImapAccount
	for rows.Next() {
		var i RacUserImapAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EmailAddress,
			&i.ImapHost,
			&i.ImapPort,
			&i.ImapUsername,
			&i.ImapPasswordEncrypted,
			&i.FolderName,
			&i.Enabled,
			&i.LastSyncAt,
			&i.LastError,
			&i.LastErrorAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPasswordEncrypted,
			&i.SmtpFromEmail,
			&i.SmtpFromName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImapAccountsNeedingSync = `-- name: ListImapAccountsNeedingSync :many
SELECT id, user_id, email_address, imap_host, imap_port, imap_username, imap_password_encrypted, folder_name, enabled, last_sync_at, last_error, last_error_at, created_at, updated_at, smtp_host, smtp_port, smtp_username, smtp_password_encrypted, smtp_from_email, smtp_from_name
FROM RAC_user_imap_accounts
WHERE enabled = TRUE
  AND (last_sync_at IS NULL OR last_sync_at <= now() - $1::interval)
ORDER BY COALESCE(last_sync_at, created_at) ASC
LIMIT $2::int
`

type ListImapAccountsNeedingSyncParams struct {
	SyncAge    pgtype.Interval `json:"sync_age"`
	LimitCount int32           `json:"limit_count"`
}

func (q *Queries) ListImapAccountsNeedingSync(ctx context.Context, arg ListImapAccountsNeedingSyncParams) ([]RacUserImapAccount, error) {
	rows, err := q.db.Query(ctx, listImapAccountsNeedingSync, arg.SyncAge, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacUserImapAccount
	for rows.Next() {
		var i RacUserImapAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EmailAddress,
			&i.ImapHost,
			&i.ImapPort,
			&i.ImapUsername,
			&i.ImapPasswordEncrypted,
			&i.FolderName,
			&i.Enabled,
			&i.LastSyncAt,
			&i.LastError,
			&i.LastErrorAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpUsername,
			&i.SmtpPasswordEncrypted,
			&i.SmtpFromEmail,
			&i.SmtpFromName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImapMessagesByUser = `-- name: ListImapMessagesByUser :many
SELECT m.id, m.account_id, m.folder_name, m.uid, m.message_id, m.from_name, m.from_address, m.subject, m.sent_at, m.received_at, m.snippet, m.size_bytes, m.seen, m.flagged, m.answered, m.deleted, m.has_attachments, m.synced_at, m.created_at, m.updated_at
FROM RAC_user_imap_messages m
JOIN RAC_user_imap_accounts a ON a.id = m.account_id
WHERE m.account_id = $1::uuid
  AND a.user_id = $2::uuid
ORDER BY COALESCE(m.sent_at, m.received_at, m.created_at) DESC
LIMIT $4::int
OFFSET $3::int
`

type ListImapMessagesByUserParams struct {
	AccountID   pgtype.UUID `json:"account_id"`
	UserID      pgtype.UUID `json:"user_id"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListImapMessagesByUser(ctx context.Context, arg ListImapMessagesByUserParams) ([]RacUserImapMessage, error) {
	rows, err := q.db.Query(ctx, listImapMessagesByUser,
		arg.AccountID,
		arg.UserID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacUserImapMessage
	for rows.Next() {
		var i RacUserImapMessage
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FolderName,
			&i.Uid,
			&i.MessageID,
			&i.FromName,
			&i.FromAddress,
			&i.Subject,
			&i.SentAt,
			&i.ReceivedAt,
			&i.Snippet,
			&i.SizeBytes,
			&i.Seen,
			&i.Flagged,
			&i.Answered,
			&i.Deleted,
			&i.HasAttachments,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markImapAccountMessagesSynced = `-- name: MarkImapAccountMessagesSynced :exec
UPDATE RAC_user_imap_accounts
SET last_sync_at = now(),
	last_error = NULL,
	last_error_at = NULL,
	updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) MarkImapAccountMessagesSynced(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markImapAccountMessagesSynced, accountID)
	return err
}

const markImapAccountSynced = `-- name: MarkImapAccountSynced :exec
UPDATE RAC_user_imap_accounts
SET last_sync_at = $1::timestamptz,
	last_error = NULL,
	last_error_at = NULL,
	updated_at = now()
WHERE id = $2::uuid
`

type MarkImapAccountSyncedParams struct {
	SyncAt    pgtype.Timestamptz `json:"sync_at"`
	AccountID pgtype.UUID        `json:"account_id"`
}

func (q *Queries) MarkImapAccountSynced(ctx context.Context, arg MarkImapAccountSyncedParams) error {
	_, err := q.db.Exec(ctx, markImapAccountSynced, arg.SyncAt, arg.AccountID)
	return err
}

const setImapAccountSyncError = `-- name: SetImapAccountSyncError :exec
UPDATE RAC_user_imap_accounts
SET last_error = $1::text,
	last_error_at = now(),
	updated_at = now()
WHERE id = $2::uuid
`

type SetImapAccountSyncErrorParams struct {
	ErrorMessage string      `json:"error_message"`
	AccountID    pgtype.UUID `json:"account_id"`
}

func (q *Queries) SetImapAccountSyncError(ctx context.Context, arg SetImapAccountSyncErrorParams) error {
	_, err := q.db.Exec(ctx, setImapAccountSyncError, arg.ErrorMessage, arg.AccountID)
	return err
}

const updateImapAccountByUser = `-- name: UpdateImapAccountByUser :one
UPDATE RAC_user_imap_accounts
SET email_address = COALESCE($1::text, email_address),
	imap_host = COALESCE($2::text, imap_host),
	imap_port = COALESCE($3::int, imap_port),
	imap_username = COALESCE($4::text, imap_username),
	imap_password_encrypted = COALESCE($5::text, imap_password_encrypted),
	smtp_host = COALESCE($6::text, smtp_host),
	smtp_port = COALESCE($7::int, smtp_port),
	smtp_username = COALESCE($8::text, smtp_username),
	smtp_password_encrypted = COALESCE($9::text, smtp_password_encrypted),
	smtp_from_email = COALESCE($10::text, smtp_from_email),
	smtp_from_name = COALESCE($11::text, smtp_from_name),
	folder_name = COALESCE($12::text, folder_name),
	enabled = COALESCE($13::bool, enabled),
	updated_at = now()
WHERE id = $14::uuid
  AND user_id = $15::uuid
RETURNING id, user_id, email_address, imap_host, imap_port, imap_username, imap_password_encrypted, folder_name, enabled, last_sync_at, last_error, last_error_at, created_at, updated_at, smtp_host, smtp_port, smtp_username, smtp_password_encrypted, smtp_from_email, smtp_from_name
`

type UpdateImapAccountByUserParams struct {
	EmailAddress          pgtype.Text `json:"email_address"`
	ImapHost              pgtype.Text `json:"imap_host"`
	ImapPort              pgtype.Int4 `json:"imap_port"`
	ImapUsername          pgtype.Text `json:"imap_username"`
	ImapPasswordEncrypted pgtype.Text `json:"imap_password_encrypted"`
	SmtpHost              pgtype.Text `json:"smtp_host"`
	SmtpPort              pgtype.Int4 `json:"smtp_port"`
	SmtpUsername          pgtype.Text `json:"smtp_username"`
	SmtpPasswordEncrypted pgtype.Text `json:"smtp_password_encrypted"`
	SmtpFromEmail         pgtype.Text `json:"smtp_from_email"`
	SmtpFromName          pgtype.Text `json:"smtp_from_name"`
	FolderName            pgtype.Text `json:"folder_name"`
	Enabled               pgtype.Bool `json:"enabled"`
	AccountID             pgtype.UUID `json:"account_id"`
	UserID                pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateImapAccountByUser(ctx context.Context, arg UpdateImapAccountByUserParams) (RacUserImapAccount, error) {
	row := q.db.QueryRow(ctx, updateImapAccountByUser,
		arg.EmailAddress,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapUsername,
		arg.ImapPasswordEncrypted,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPasswordEncrypted,
		arg.SmtpFromEmail,
		arg.SmtpFromName,
		arg.FolderName,
		arg.Enabled,
		arg.AccountID,
		arg.UserID,
	)
	var i RacUserImapAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailAddress,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapUsername,
		&i.ImapPasswordEncrypted,
		&i.FolderName,
		&i.Enabled,
		&i.LastSyncAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPasswordEncrypted,
		&i.SmtpFromEmail,
		&i.SmtpFromName,
	)
	return i, err
}

const updateImapMessageAnsweredByUID = `-- name: UpdateImapMessageAnsweredByUID :exec
UPDATE RAC_user_imap_messages
SET answered = $1::bool,
	updated_at = now()
WHERE account_id = $2::uuid
  AND uid = $3::bigint
`

type UpdateImapMessageAnsweredByUIDParams struct {
	Answered  bool        `json:"answered"`
	AccountID pgtype.UUID `json:"account_id"`
	Uid       int64       `json:"uid"`
}

func (q *Queries) UpdateImapMessageAnsweredByUID(ctx context.Context, arg UpdateImapMessageAnsweredByUIDParams) error {
	_, err := q.db.Exec(ctx, updateImapMessageAnsweredByUID, arg.Answered, arg.AccountID, arg.Uid)
	return err
}

const updateImapMessageSeenByUID = `-- name: UpdateImapMessageSeenByUID :exec
UPDATE RAC_user_imap_messages
SET seen = $1::bool,
	updated_at = now()
WHERE account_id = $2::uuid
  AND uid = $3::bigint
`

type UpdateImapMessageSeenByUIDParams struct {
	Seen      bool        `json:"seen"`
	AccountID pgtype.UUID `json:"account_id"`
	Uid       int64       `json:"uid"`
}

func (q *Queries) UpdateImapMessageSeenByUID(ctx context.Context, arg UpdateImapMessageSeenByUIDParams) error {
	_, err := q.db.Exec(ctx, updateImapMessageSeenByUID, arg.Seen, arg.AccountID, arg.Uid)
	return err
}

const upsertImapMessage = `-- name: UpsertImapMessage :exec
INSERT INTO RAC_user_imap_messages (
	account_id,
	folder_name,
	uid,
	message_id,
	from_name,
	from_address,
	subject,
	sent_at,
	received_at,
	snippet,
	size_bytes,
	seen,
	flagged,
	answered,
	deleted,
	has_attachments,
	synced_at
) VALUES (
	$1::uuid,
	$2::text,
	$3::bigint,
	$4::text,
	$5::text,
	$6::text,
	$7::text,
	$8::timestamptz,
	$9::timestamptz,
	$10::text,
	$11::bigint,
	$12::bool,
	$13::bool,
	$14::bool,
	$15::bool,
	$16::bool,
	$17::timestamptz
)
ON CONFLICT (account_id, folder_name, uid)
DO UPDATE SET
	message_id = EXCLUDED.message_id,
	from_name = EXCLUDED.from_name,
	from_address = EXCLUDED.from_address,
	subject = EXCLUDED.subject,
	sent_at = EXCLUDED.sent_at,
	received_at = EXCLUDED.received_at,
	snippet = EXCLUDED.snippet,
	size_bytes = EXCLUDED.size_bytes,
	seen = EXCLUDED.seen,
	flagged = EXCLUDED.flagged,
	answered = EXCLUDED.answered,
	deleted = EXCLUDED.deleted,
	has_attachments = EXCLUDED.has_attachments,
	synced_at = EXCLUDED.synced_at,
	updated_at = now()
`

type UpsertImapMessageParams struct {
	AccountID      pgtype.UUID        `json:"account_id"`
	FolderName     string             `json:"folder_name"`
	Uid            int64              `json:"uid"`
	MessageID      pgtype.Text        `json:"message_id"`
	FromName       pgtype.Text        `json:"from_name"`
	FromAddress    pgtype.Text        `json:"from_address"`
	Subject        string             `json:"subject"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	Snippet        pgtype.Text        `json:"snippet"`
	SizeBytes      int64              `json:"size_bytes"`
	Seen           bool               `json:"seen"`
	Flagged        bool               `json:"flagged"`
	Answered       bool               `json:"answered"`
	Deleted        bool               `json:"deleted"`
	HasAttachments bool               `json:"has_attachments"`
	SyncedAt       pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) UpsertImapMessage(ctx context.Context, arg UpsertImapMessageParams) error {
	_, err := q.db.Exec(ctx, upsertImapMessage,
		arg.AccountID,
		arg.FolderName,
		arg.Uid,
		arg.MessageID,
		arg.FromName,
		arg.FromAddress,
		arg.Subject,
		arg.SentAt,
		arg.ReceivedAt,
		arg.Snippet,
		arg.SizeBytes,
		arg.Seen,
		arg.Flagged,
		arg.Answered,
		arg.Deleted,
		arg.HasAttachments,
		arg.SyncedAt,
	)
	return err
}
