// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :exec
INSERT INTO RAC_organization_members (organization_id, user_id)
VALUES ($1, $2)
`

type AddMemberParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.OrganizationID, arg.UserID)
	return err
}

const clearOrganizationLogo = `-- name: ClearOrganizationLogo :one
UPDATE RAC_organizations
SET
  logo_file_key = NULL,
  logo_file_name = NULL,
  logo_content_type = NULL,
  logo_size_bytes = NULL,
  updated_at = now()
WHERE id = $1
RETURNING id, name, email, phone, vat_number, kvk_number, address_line1, address_line2, postal_code, city, country,
  logo_file_key, logo_file_name, logo_content_type, logo_size_bytes,
  created_by, created_at, updated_at
`

type ClearOrganizationLogoRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	VatNumber       pgtype.Text        `json:"vat_number"`
	KvkNumber       pgtype.Text        `json:"kvk_number"`
	AddressLine1    pgtype.Text        `json:"address_line1"`
	AddressLine2    pgtype.Text        `json:"address_line2"`
	PostalCode      pgtype.Text        `json:"postal_code"`
	City            pgtype.Text        `json:"city"`
	Country         pgtype.Text        `json:"country"`
	LogoFileKey     pgtype.Text        `json:"logo_file_key"`
	LogoFileName    pgtype.Text        `json:"logo_file_name"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoSizeBytes   pgtype.Int8        `json:"logo_size_bytes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ClearOrganizationLogo(ctx context.Context, id pgtype.UUID) (ClearOrganizationLogoRow, error) {
	row := q.db.QueryRow(ctx, clearOrganizationLogo, id)
	var i ClearOrganizationLogoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VatNumber,
		&i.KvkNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearOrganizationSMTP = `-- name: ClearOrganizationSMTP :exec
UPDATE RAC_organization_settings
SET smtp_host = NULL, smtp_port = NULL, smtp_username = NULL, smtp_password = NULL,
    smtp_from_email = NULL, smtp_from_name = NULL, updated_at = now()
WHERE organization_id = $1
`

func (q *Queries) ClearOrganizationSMTP(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearOrganizationSMTP, organizationID)
	return err
}

const createDefaultWorkflowAssignmentRule = `-- name: CreateDefaultWorkflowAssignmentRule :exec
INSERT INTO RAC_workflow_assignment_rules (
  organization_id,
  workflow_id,
  name,
  enabled,
  priority,
  lead_source,
  lead_service_type,
  pipeline_stage
)
VALUES ($1, $2, $3, TRUE, $4, NULL, NULL, NULL)
`

type CreateDefaultWorkflowAssignmentRuleParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	WorkflowID     pgtype.UUID `json:"workflow_id"`
	Name           string      `json:"name"`
	Priority       int32       `json:"priority"`
}

func (q *Queries) CreateDefaultWorkflowAssignmentRule(ctx context.Context, arg CreateDefaultWorkflowAssignmentRuleParams) error {
	_, err := q.db.Exec(ctx, createDefaultWorkflowAssignmentRule,
		arg.OrganizationID,
		arg.WorkflowID,
		arg.Name,
		arg.Priority,
	)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO RAC_organization_invites (organization_id, email, token_hash, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by
`

type CreateInviteParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Email          string             `json:"email"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (RacOrganizationInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.OrganizationID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i RacOrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one

INSERT INTO RAC_organizations (name, created_by)
VALUES ($1, $2)
RETURNING id, name, email, phone, vat_number, kvk_number, address_line1, address_line2, postal_code, city, country,
  logo_file_key, logo_file_name, logo_content_type, logo_size_bytes,
  created_by, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

type CreateOrganizationRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	VatNumber       pgtype.Text        `json:"vat_number"`
	KvkNumber       pgtype.Text        `json:"kvk_number"`
	AddressLine1    pgtype.Text        `json:"address_line1"`
	AddressLine2    pgtype.Text        `json:"address_line2"`
	PostalCode      pgtype.Text        `json:"postal_code"`
	City            pgtype.Text        `json:"city"`
	Country         pgtype.Text        `json:"country"`
	LogoFileKey     pgtype.Text        `json:"logo_file_key"`
	LogoFileName    pgtype.Text        `json:"logo_file_name"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoSizeBytes   pgtype.Int8        `json:"logo_size_bytes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Identity Domain SQL Queries
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.CreatedBy)
	var i CreateOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VatNumber,
		&i.KvkNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowAssignmentRule = `-- name: CreateWorkflowAssignmentRule :exec
INSERT INTO RAC_workflow_assignment_rules (
  id, organization_id, workflow_id, name, enabled, priority,
  lead_source, lead_service_type, pipeline_stage
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateWorkflowAssignmentRuleParams struct {
	ID              pgtype.UUID `json:"id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	WorkflowID      pgtype.UUID `json:"workflow_id"`
	Name            string      `json:"name"`
	Enabled         bool        `json:"enabled"`
	Priority        int32       `json:"priority"`
	LeadSource      pgtype.Text `json:"lead_source"`
	LeadServiceType pgtype.Text `json:"lead_service_type"`
	PipelineStage   pgtype.Text `json:"pipeline_stage"`
}

func (q *Queries) CreateWorkflowAssignmentRule(ctx context.Context, arg CreateWorkflowAssignmentRuleParams) error {
	_, err := q.db.Exec(ctx, createWorkflowAssignmentRule,
		arg.ID,
		arg.OrganizationID,
		arg.WorkflowID,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.LeadSource,
		arg.LeadServiceType,
		arg.PipelineStage,
	)
	return err
}

const defaultWorkflowAssignmentRuleExists = `-- name: DefaultWorkflowAssignmentRuleExists :one
SELECT EXISTS (
  SELECT 1
  FROM RAC_workflow_assignment_rules
  WHERE organization_id = $1
    AND lead_source IS NULL
    AND lead_service_type IS NULL
    AND pipeline_stage IS NULL
) AS exists
`

func (q *Queries) DefaultWorkflowAssignmentRuleExists(ctx context.Context, organizationID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, defaultWorkflowAssignmentRuleExists, organizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteLeadWorkflowOverride = `-- name: DeleteLeadWorkflowOverride :exec
DELETE FROM RAC_lead_workflow_overrides
WHERE lead_id = $1 AND organization_id = $2
`

type DeleteLeadWorkflowOverrideParams struct {
	LeadID         pgtype.UUID `json:"lead_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteLeadWorkflowOverride(ctx context.Context, arg DeleteLeadWorkflowOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteLeadWorkflowOverride, arg.LeadID, arg.OrganizationID)
	return err
}

const deleteWorkflowAssignmentRulesByOrganization = `-- name: DeleteWorkflowAssignmentRulesByOrganization :exec
DELETE FROM RAC_workflow_assignment_rules
WHERE organization_id = $1
`

func (q *Queries) DeleteWorkflowAssignmentRulesByOrganization(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowAssignmentRulesByOrganization, organizationID)
	return err
}

const deleteWorkflowStepsByWorkflow = `-- name: DeleteWorkflowStepsByWorkflow :exec
DELETE FROM RAC_workflow_steps
WHERE organization_id = $1 AND workflow_id = $2
`

type DeleteWorkflowStepsByWorkflowParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	WorkflowID     pgtype.UUID `json:"workflow_id"`
}

func (q *Queries) DeleteWorkflowStepsByWorkflow(ctx context.Context, arg DeleteWorkflowStepsByWorkflowParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflowStepsByWorkflow, arg.OrganizationID, arg.WorkflowID)
	return err
}

const deleteWorkflowStepsNotInList = `-- name: DeleteWorkflowStepsNotInList :exec
DELETE FROM RAC_workflow_steps
WHERE organization_id = $1
  AND workflow_id = $2
  AND NOT (id = ANY($3::uuid[]))
`

type DeleteWorkflowStepsNotInListParams struct {
	OrganizationID pgtype.UUID   `json:"organization_id"`
	WorkflowID     pgtype.UUID   `json:"workflow_id"`
	Column3        []pgtype.UUID `json:"column_3"`
}

func (q *Queries) DeleteWorkflowStepsNotInList(ctx context.Context, arg DeleteWorkflowStepsNotInListParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflowStepsNotInList, arg.OrganizationID, arg.WorkflowID, arg.Column3)
	return err
}

const deleteWorkflowsByOrganization = `-- name: DeleteWorkflowsByOrganization :exec
DELETE FROM RAC_workflows
WHERE organization_id = $1
`

func (q *Queries) DeleteWorkflowsByOrganization(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowsByOrganization, organizationID)
	return err
}

const deleteWorkflowsNotInList = `-- name: DeleteWorkflowsNotInList :exec
DELETE FROM RAC_workflows
WHERE organization_id = $1
  AND NOT (id = ANY($2::uuid[]))
`

type DeleteWorkflowsNotInListParams struct {
	OrganizationID pgtype.UUID   `json:"organization_id"`
	Column2        []pgtype.UUID `json:"column_2"`
}

func (q *Queries) DeleteWorkflowsNotInList(ctx context.Context, arg DeleteWorkflowsNotInListParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflowsNotInList, arg.OrganizationID, arg.Column2)
	return err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, organization_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by
FROM RAC_organization_invites
WHERE token_hash = $1
`

func (q *Queries) GetInviteByToken(ctx context.Context, tokenHash string) (RacOrganizationInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, tokenHash)
	var i RacOrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const getLeadWorkflowOverride = `-- name: GetLeadWorkflowOverride :one
SELECT lead_id, organization_id, workflow_id, override_mode, reason, assigned_by, created_at, updated_at
FROM RAC_lead_workflow_overrides
WHERE lead_id = $1 AND organization_id = $2
`

type GetLeadWorkflowOverrideParams struct {
	LeadID         pgtype.UUID `json:"lead_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetLeadWorkflowOverride(ctx context.Context, arg GetLeadWorkflowOverrideParams) (RacLeadWorkflowOverride, error) {
	row := q.db.QueryRow(ctx, getLeadWorkflowOverride, arg.LeadID, arg.OrganizationID)
	var i RacLeadWorkflowOverride
	err := row.Scan(
		&i.LeadID,
		&i.OrganizationID,
		&i.WorkflowID,
		&i.OverrideMode,
		&i.Reason,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, email, phone, vat_number, kvk_number, address_line1, address_line2, postal_code, city, country,
  logo_file_key, logo_file_name, logo_content_type, logo_size_bytes,
  created_by, created_at, updated_at
FROM RAC_organizations
WHERE id = $1
`

type GetOrganizationRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	VatNumber       pgtype.Text        `json:"vat_number"`
	KvkNumber       pgtype.Text        `json:"kvk_number"`
	AddressLine1    pgtype.Text        `json:"address_line1"`
	AddressLine2    pgtype.Text        `json:"address_line2"`
	PostalCode      pgtype.Text        `json:"postal_code"`
	City            pgtype.Text        `json:"city"`
	Country         pgtype.Text        `json:"country"`
	LogoFileKey     pgtype.Text        `json:"logo_file_key"`
	LogoFileName    pgtype.Text        `json:"logo_file_name"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoSizeBytes   pgtype.Int8        `json:"logo_size_bytes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrganization(ctx context.Context, id pgtype.UUID) (GetOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i GetOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VatNumber,
		&i.KvkNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationSettings = `-- name: GetOrganizationSettings :one
SELECT organization_id, quote_payment_days, quote_valid_days,
       ai_auto_disqualify_junk, ai_auto_dispatch, ai_auto_estimate, ai_confidence_gate_enabled,
       ai_adaptive_reasoning_enabled, ai_experience_memory_enabled, ai_council_enabled,
       ai_council_consensus_mode,
       catalog_gap_threshold, catalog_gap_lookback_days,
  photo_analysis_preprocessing_enabled,
  photo_analysis_ocr_assist_enabled,
  photo_analysis_ocr_assist_service_types,
  photo_analysis_lens_correction_enabled,
  photo_analysis_lens_correction_service_types,
  photo_analysis_perspective_normalization_enabled,
  photo_analysis_perspective_normalization_service_types,
      notification_email, whatsapp_device_id, whatsapp_presence, whatsapp_welcome_delay_minutes,
       smtp_host, smtp_port, smtp_username, smtp_password, smtp_from_email, smtp_from_name,
       created_at, updated_at
FROM RAC_organization_settings
WHERE organization_id = $1
`

type GetOrganizationSettingsRow struct {
	OrganizationID                                    pgtype.UUID        `json:"organization_id"`
	QuotePaymentDays                                  int32              `json:"quote_payment_days"`
	QuoteValidDays                                    int32              `json:"quote_valid_days"`
	AiAutoDisqualifyJunk                              bool               `json:"ai_auto_disqualify_junk"`
	AiAutoDispatch                                    bool               `json:"ai_auto_dispatch"`
	AiAutoEstimate                                    bool               `json:"ai_auto_estimate"`
	AiConfidenceGateEnabled                           bool               `json:"ai_confidence_gate_enabled"`
	AiAdaptiveReasoningEnabled                        bool               `json:"ai_adaptive_reasoning_enabled"`
	AiExperienceMemoryEnabled                         bool               `json:"ai_experience_memory_enabled"`
	AiCouncilEnabled                                  bool               `json:"ai_council_enabled"`
	AiCouncilConsensusMode                            string             `json:"ai_council_consensus_mode"`
	CatalogGapThreshold                               int32              `json:"catalog_gap_threshold"`
	CatalogGapLookbackDays                            int32              `json:"catalog_gap_lookback_days"`
	PhotoAnalysisPreprocessingEnabled                 bool               `json:"photo_analysis_preprocessing_enabled"`
	PhotoAnalysisOcrAssistEnabled                     bool               `json:"photo_analysis_ocr_assist_enabled"`
	PhotoAnalysisOcrAssistServiceTypes                []string           `json:"photo_analysis_ocr_assist_service_types"`
	PhotoAnalysisLensCorrectionEnabled                bool               `json:"photo_analysis_lens_correction_enabled"`
	PhotoAnalysisLensCorrectionServiceTypes           []string           `json:"photo_analysis_lens_correction_service_types"`
	PhotoAnalysisPerspectiveNormalizationEnabled      bool               `json:"photo_analysis_perspective_normalization_enabled"`
	PhotoAnalysisPerspectiveNormalizationServiceTypes []string           `json:"photo_analysis_perspective_normalization_service_types"`
	NotificationEmail                                 pgtype.Text        `json:"notification_email"`
	WhatsappDeviceID                                  pgtype.Text        `json:"whatsapp_device_id"`
	WhatsappPresence                                  string             `json:"whatsapp_presence"`
	WhatsappWelcomeDelayMinutes                       int32              `json:"whatsapp_welcome_delay_minutes"`
	SmtpHost                                          pgtype.Text        `json:"smtp_host"`
	SmtpPort                                          pgtype.Int4        `json:"smtp_port"`
	SmtpUsername                                      pgtype.Text        `json:"smtp_username"`
	SmtpPassword                                      pgtype.Text        `json:"smtp_password"`
	SmtpFromEmail                                     pgtype.Text        `json:"smtp_from_email"`
	SmtpFromName                                      pgtype.Text        `json:"smtp_from_name"`
	CreatedAt                                         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                                         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrganizationSettings(ctx context.Context, organizationID pgtype.UUID) (GetOrganizationSettingsRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationSettings, organizationID)
	var i GetOrganizationSettingsRow
	err := row.Scan(
		&i.OrganizationID,
		&i.QuotePaymentDays,
		&i.QuoteValidDays,
		&i.AiAutoDisqualifyJunk,
		&i.AiAutoDispatch,
		&i.AiAutoEstimate,
		&i.AiConfidenceGateEnabled,
		&i.AiAdaptiveReasoningEnabled,
		&i.AiExperienceMemoryEnabled,
		&i.AiCouncilEnabled,
		&i.AiCouncilConsensusMode,
		&i.CatalogGapThreshold,
		&i.CatalogGapLookbackDays,
		&i.PhotoAnalysisPreprocessingEnabled,
		&i.PhotoAnalysisOcrAssistEnabled,
		&i.PhotoAnalysisOcrAssistServiceTypes,
		&i.PhotoAnalysisLensCorrectionEnabled,
		&i.PhotoAnalysisLensCorrectionServiceTypes,
		&i.PhotoAnalysisPerspectiveNormalizationEnabled,
		&i.PhotoAnalysisPerspectiveNormalizationServiceTypes,
		&i.NotificationEmail,
		&i.WhatsappDeviceID,
		&i.WhatsappPresence,
		&i.WhatsappWelcomeDelayMinutes,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpFromEmail,
		&i.SmtpFromName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrganizationID = `-- name: GetUserOrganizationID :one
SELECT organization_id
FROM RAC_organization_members
WHERE user_id = $1
`

func (q *Queries) GetUserOrganizationID(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserOrganizationID, userID)
	var organization_id pgtype.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const leadExistsInOrganization = `-- name: LeadExistsInOrganization :one
SELECT EXISTS (
  SELECT 1
  FROM RAC_leads
  WHERE id = $1 AND organization_id = $2
) AS exists
`

type LeadExistsInOrganizationParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) LeadExistsInOrganization(ctx context.Context, arg LeadExistsInOrganizationParams) (bool, error) {
	row := q.db.QueryRow(ctx, leadExistsInOrganization, arg.ID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, organization_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by
FROM RAC_organization_invites
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context, organizationID pgtype.UUID) ([]RacOrganizationInvite, error) {
	rows, err := q.db.Query(ctx, listInvites, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacOrganizationInvite
	for rows.Next() {
		var i RacOrganizationInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowAssignmentRules = `-- name: ListWorkflowAssignmentRules :many
SELECT id, organization_id, workflow_id, name, enabled, priority,
       lead_source, lead_service_type, pipeline_stage, created_at, updated_at
FROM RAC_workflow_assignment_rules
WHERE organization_id = $1
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) ListWorkflowAssignmentRules(ctx context.Context, organizationID pgtype.UUID) ([]RacWorkflowAssignmentRule, error) {
	rows, err := q.db.Query(ctx, listWorkflowAssignmentRules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacWorkflowAssignmentRule
	for rows.Next() {
		var i RacWorkflowAssignmentRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowID,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.LeadSource,
			&i.LeadServiceType,
			&i.PipelineStage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowSteps = `-- name: ListWorkflowSteps :many
SELECT id, organization_id, workflow_id, trigger, channel, audience, action,
       step_order, delay_minutes, enabled, recipient_config, template_subject,
       template_body, stop_on_reply, created_at, updated_at
FROM RAC_workflow_steps
WHERE organization_id = $1
ORDER BY workflow_id ASC, trigger ASC, channel ASC, step_order ASC
`

func (q *Queries) ListWorkflowSteps(ctx context.Context, organizationID pgtype.UUID) ([]RacWorkflowStep, error) {
	rows, err := q.db.Query(ctx, listWorkflowSteps, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacWorkflowStep
	for rows.Next() {
		var i RacWorkflowStep
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowID,
			&i.Trigger,
			&i.Channel,
			&i.Audience,
			&i.Action,
			&i.StepOrder,
			&i.DelayMinutes,
			&i.Enabled,
			&i.RecipientConfig,
			&i.TemplateSubject,
			&i.TemplateBody,
			&i.StopOnReply,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, organization_id, workflow_key, name, description, enabled,
       quote_valid_days_override, quote_payment_days_override, created_at, updated_at
FROM RAC_workflows
WHERE organization_id = $1
ORDER BY workflow_key ASC
`

func (q *Queries) ListWorkflows(ctx context.Context, organizationID pgtype.UUID) ([]RacWorkflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacWorkflow
	for rows.Next() {
		var i RacWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.WorkflowKey,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.QuoteValidDaysOverride,
			&i.QuotePaymentDaysOverride,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE RAC_organization_invites
SET expires_at = now()
WHERE id = $1 AND organization_id = $2 AND used_at IS NULL
RETURNING id, organization_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by
`

type RevokeInviteParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (RacOrganizationInvite, error) {
	row := q.db.QueryRow(ctx, revokeInvite, arg.ID, arg.OrganizationID)
	var i RacOrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const updateInvite = `-- name: UpdateInvite :one
UPDATE RAC_organization_invites
SET
  email = COALESCE($1::text, email),
  token_hash = COALESCE($2::text, token_hash),
  expires_at = COALESCE($3::timestamptz, expires_at)
WHERE id = $4::uuid AND organization_id = $5::uuid AND used_at IS NULL
RETURNING id, organization_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by
`

type UpdateInviteParams struct {
	Email          pgtype.Text        `json:"email"`
	TokenHash      pgtype.Text        `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

func (q *Queries) UpdateInvite(ctx context.Context, arg UpdateInviteParams) (RacOrganizationInvite, error) {
	row := q.db.QueryRow(ctx, updateInvite,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.ID,
		arg.OrganizationID,
	)
	var i RacOrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const updateOrganizationLogo = `-- name: UpdateOrganizationLogo :one
UPDATE RAC_organizations
SET
  logo_file_key = $2,
  logo_file_name = $3,
  logo_content_type = $4,
  logo_size_bytes = $5,
  updated_at = now()
WHERE id = $1
RETURNING id, name, email, phone, vat_number, kvk_number, address_line1, address_line2, postal_code, city, country,
  logo_file_key, logo_file_name, logo_content_type, logo_size_bytes,
  created_by, created_at, updated_at
`

type UpdateOrganizationLogoParams struct {
	ID              pgtype.UUID `json:"id"`
	LogoFileKey     pgtype.Text `json:"logo_file_key"`
	LogoFileName    pgtype.Text `json:"logo_file_name"`
	LogoContentType pgtype.Text `json:"logo_content_type"`
	LogoSizeBytes   pgtype.Int8 `json:"logo_size_bytes"`
}

type UpdateOrganizationLogoRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	VatNumber       pgtype.Text        `json:"vat_number"`
	KvkNumber       pgtype.Text        `json:"kvk_number"`
	AddressLine1    pgtype.Text        `json:"address_line1"`
	AddressLine2    pgtype.Text        `json:"address_line2"`
	PostalCode      pgtype.Text        `json:"postal_code"`
	City            pgtype.Text        `json:"city"`
	Country         pgtype.Text        `json:"country"`
	LogoFileKey     pgtype.Text        `json:"logo_file_key"`
	LogoFileName    pgtype.Text        `json:"logo_file_name"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoSizeBytes   pgtype.Int8        `json:"logo_size_bytes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrganizationLogo(ctx context.Context, arg UpdateOrganizationLogoParams) (UpdateOrganizationLogoRow, error) {
	row := q.db.QueryRow(ctx, updateOrganizationLogo,
		arg.ID,
		arg.LogoFileKey,
		arg.LogoFileName,
		arg.LogoContentType,
		arg.LogoSizeBytes,
	)
	var i UpdateOrganizationLogoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VatNumber,
		&i.KvkNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationProfile = `-- name: UpdateOrganizationProfile :one
UPDATE RAC_organizations
SET
  name = COALESCE($1::text, name),
  email = COALESCE($2::text, email),
  phone = COALESCE($3::text, phone),
  vat_number = COALESCE($4::text, vat_number),
  kvk_number = COALESCE($5::text, kvk_number),
  address_line1 = COALESCE($6::text, address_line1),
  address_line2 = COALESCE($7::text, address_line2),
  postal_code = COALESCE($8::text, postal_code),
  city = COALESCE($9::text, city),
  country = COALESCE($10::text, country),
  updated_at = now()
WHERE id = $11::uuid
RETURNING id, name, email, phone, vat_number, kvk_number, address_line1, address_line2, postal_code, city, country,
  logo_file_key, logo_file_name, logo_content_type, logo_size_bytes,
  created_by, created_at, updated_at
`

type UpdateOrganizationProfileParams struct {
	Name         pgtype.Text `json:"name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	VatNumber    pgtype.Text `json:"vat_number"`
	KvkNumber    pgtype.Text `json:"kvk_number"`
	AddressLine1 pgtype.Text `json:"address_line1"`
	AddressLine2 pgtype.Text `json:"address_line2"`
	PostalCode   pgtype.Text `json:"postal_code"`
	City         pgtype.Text `json:"city"`
	Country      pgtype.Text `json:"country"`
	ID           pgtype.UUID `json:"id"`
}

type UpdateOrganizationProfileRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	VatNumber       pgtype.Text        `json:"vat_number"`
	KvkNumber       pgtype.Text        `json:"kvk_number"`
	AddressLine1    pgtype.Text        `json:"address_line1"`
	AddressLine2    pgtype.Text        `json:"address_line2"`
	PostalCode      pgtype.Text        `json:"postal_code"`
	City            pgtype.Text        `json:"city"`
	Country         pgtype.Text        `json:"country"`
	LogoFileKey     pgtype.Text        `json:"logo_file_key"`
	LogoFileName    pgtype.Text        `json:"logo_file_name"`
	LogoContentType pgtype.Text        `json:"logo_content_type"`
	LogoSizeBytes   pgtype.Int8        `json:"logo_size_bytes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) (UpdateOrganizationProfileRow, error) {
	row := q.db.QueryRow(ctx, updateOrganizationProfile,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.VatNumber,
		arg.KvkNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.PostalCode,
		arg.City,
		arg.Country,
		arg.ID,
	)
	var i UpdateOrganizationProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.VatNumber,
		&i.KvkNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLeadWorkflowOverride = `-- name: UpsertLeadWorkflowOverride :one
INSERT INTO RAC_lead_workflow_overrides (
  lead_id, organization_id, workflow_id, override_mode, reason, assigned_by
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (lead_id) DO UPDATE SET
  workflow_id = EXCLUDED.workflow_id,
  override_mode = EXCLUDED.override_mode,
  reason = EXCLUDED.reason,
  assigned_by = EXCLUDED.assigned_by,
  updated_at = now()
RETURNING lead_id, organization_id, workflow_id, override_mode, reason, assigned_by, created_at, updated_at
`

type UpsertLeadWorkflowOverrideParams struct {
	LeadID         pgtype.UUID `json:"lead_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	WorkflowID     pgtype.UUID `json:"workflow_id"`
	OverrideMode   string      `json:"override_mode"`
	Reason         pgtype.Text `json:"reason"`
	AssignedBy     pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) UpsertLeadWorkflowOverride(ctx context.Context, arg UpsertLeadWorkflowOverrideParams) (RacLeadWorkflowOverride, error) {
	row := q.db.QueryRow(ctx, upsertLeadWorkflowOverride,
		arg.LeadID,
		arg.OrganizationID,
		arg.WorkflowID,
		arg.OverrideMode,
		arg.Reason,
		arg.AssignedBy,
	)
	var i RacLeadWorkflowOverride
	err := row.Scan(
		&i.LeadID,
		&i.OrganizationID,
		&i.WorkflowID,
		&i.OverrideMode,
		&i.Reason,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationSMTP = `-- name: UpsertOrganizationSMTP :one
INSERT INTO RAC_organization_settings (organization_id, smtp_host, smtp_port, smtp_username, smtp_password, smtp_from_email, smtp_from_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (organization_id) DO UPDATE SET
  smtp_host = $2,
  smtp_port = $3,
  smtp_username = $4,
  smtp_password = $5,
  smtp_from_email = $6,
  smtp_from_name = $7,
  updated_at = now()
RETURNING organization_id, quote_payment_days, quote_valid_days,
  ai_auto_disqualify_junk, ai_auto_dispatch, ai_auto_estimate, ai_confidence_gate_enabled,
  ai_adaptive_reasoning_enabled, ai_experience_memory_enabled, ai_council_enabled,
  ai_council_consensus_mode,
  catalog_gap_threshold, catalog_gap_lookback_days,
  photo_analysis_preprocessing_enabled,
  photo_analysis_ocr_assist_enabled,
  photo_analysis_ocr_assist_service_types,
  photo_analysis_lens_correction_enabled,
  photo_analysis_lens_correction_service_types,
  photo_analysis_perspective_normalization_enabled,
  photo_analysis_perspective_normalization_service_types,
  notification_email, whatsapp_device_id, whatsapp_presence, whatsapp_welcome_delay_minutes,
  smtp_host, smtp_port, smtp_username, smtp_password, smtp_from_email, smtp_from_name,
  created_at, updated_at
`

type UpsertOrganizationSMTPParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	SmtpHost       pgtype.Text `json:"smtp_host"`
	SmtpPort       pgtype.Int4 `json:"smtp_port"`
	SmtpUsername   pgtype.Text `json:"smtp_username"`
	SmtpPassword   pgtype.Text `json:"smtp_password"`
	SmtpFromEmail  pgtype.Text `json:"smtp_from_email"`
	SmtpFromName   pgtype.Text `json:"smtp_from_name"`
}

type UpsertOrganizationSMTPRow struct {
	OrganizationID                                    pgtype.UUID        `json:"organization_id"`
	QuotePaymentDays                                  int32              `json:"quote_payment_days"`
	QuoteValidDays                                    int32              `json:"quote_valid_days"`
	AiAutoDisqualifyJunk                              bool               `json:"ai_auto_disqualify_junk"`
	AiAutoDispatch                                    bool               `json:"ai_auto_dispatch"`
	AiAutoEstimate                                    bool               `json:"ai_auto_estimate"`
	AiConfidenceGateEnabled                           bool               `json:"ai_confidence_gate_enabled"`
	AiAdaptiveReasoningEnabled                        bool               `json:"ai_adaptive_reasoning_enabled"`
	AiExperienceMemoryEnabled                         bool               `json:"ai_experience_memory_enabled"`
	AiCouncilEnabled                                  bool               `json:"ai_council_enabled"`
	AiCouncilConsensusMode                            string             `json:"ai_council_consensus_mode"`
	CatalogGapThreshold                               int32              `json:"catalog_gap_threshold"`
	CatalogGapLookbackDays                            int32              `json:"catalog_gap_lookback_days"`
	PhotoAnalysisPreprocessingEnabled                 bool               `json:"photo_analysis_preprocessing_enabled"`
	PhotoAnalysisOcrAssistEnabled                     bool               `json:"photo_analysis_ocr_assist_enabled"`
	PhotoAnalysisOcrAssistServiceTypes                []string           `json:"photo_analysis_ocr_assist_service_types"`
	PhotoAnalysisLensCorrectionEnabled                bool               `json:"photo_analysis_lens_correction_enabled"`
	PhotoAnalysisLensCorrectionServiceTypes           []string           `json:"photo_analysis_lens_correction_service_types"`
	PhotoAnalysisPerspectiveNormalizationEnabled      bool               `json:"photo_analysis_perspective_normalization_enabled"`
	PhotoAnalysisPerspectiveNormalizationServiceTypes []string           `json:"photo_analysis_perspective_normalization_service_types"`
	NotificationEmail                                 pgtype.Text        `json:"notification_email"`
	WhatsappDeviceID                                  pgtype.Text        `json:"whatsapp_device_id"`
	WhatsappPresence                                  string             `json:"whatsapp_presence"`
	WhatsappWelcomeDelayMinutes                       int32              `json:"whatsapp_welcome_delay_minutes"`
	SmtpHost                                          pgtype.Text        `json:"smtp_host"`
	SmtpPort                                          pgtype.Int4        `json:"smtp_port"`
	SmtpUsername                                      pgtype.Text        `json:"smtp_username"`
	SmtpPassword                                      pgtype.Text        `json:"smtp_password"`
	SmtpFromEmail                                     pgtype.Text        `json:"smtp_from_email"`
	SmtpFromName                                      pgtype.Text        `json:"smtp_from_name"`
	CreatedAt                                         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                                         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertOrganizationSMTP(ctx context.Context, arg UpsertOrganizationSMTPParams) (UpsertOrganizationSMTPRow, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSMTP,
		arg.OrganizationID,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpUsername,
		arg.SmtpPassword,
		arg.SmtpFromEmail,
		arg.SmtpFromName,
	)
	var i UpsertOrganizationSMTPRow
	err := row.Scan(
		&i.OrganizationID,
		&i.QuotePaymentDays,
		&i.QuoteValidDays,
		&i.AiAutoDisqualifyJunk,
		&i.AiAutoDispatch,
		&i.AiAutoEstimate,
		&i.AiConfidenceGateEnabled,
		&i.AiAdaptiveReasoningEnabled,
		&i.AiExperienceMemoryEnabled,
		&i.AiCouncilEnabled,
		&i.AiCouncilConsensusMode,
		&i.CatalogGapThreshold,
		&i.CatalogGapLookbackDays,
		&i.PhotoAnalysisPreprocessingEnabled,
		&i.PhotoAnalysisOcrAssistEnabled,
		&i.PhotoAnalysisOcrAssistServiceTypes,
		&i.PhotoAnalysisLensCorrectionEnabled,
		&i.PhotoAnalysisLensCorrectionServiceTypes,
		&i.PhotoAnalysisPerspectiveNormalizationEnabled,
		&i.PhotoAnalysisPerspectiveNormalizationServiceTypes,
		&i.NotificationEmail,
		&i.WhatsappDeviceID,
		&i.WhatsappPresence,
		&i.WhatsappWelcomeDelayMinutes,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpFromEmail,
		&i.SmtpFromName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationSettings = `-- name: UpsertOrganizationSettings :one
INSERT INTO RAC_organization_settings (
  organization_id,
  quote_payment_days,
  quote_valid_days,
  ai_auto_disqualify_junk,
  ai_auto_dispatch,
  ai_auto_estimate,
  ai_confidence_gate_enabled,
  ai_adaptive_reasoning_enabled,
  ai_experience_memory_enabled,
  ai_council_enabled,
  ai_council_consensus_mode,
  catalog_gap_threshold,
  catalog_gap_lookback_days,
  photo_analysis_preprocessing_enabled,
  photo_analysis_ocr_assist_enabled,
  photo_analysis_ocr_assist_service_types,
  photo_analysis_lens_correction_enabled,
  photo_analysis_lens_correction_service_types,
  photo_analysis_perspective_normalization_enabled,
  photo_analysis_perspective_normalization_service_types,
  notification_email,
  whatsapp_device_id,
  whatsapp_presence,
  whatsapp_welcome_delay_minutes
)
VALUES (
  $1::uuid,
  COALESCE($2::int, 7),
  COALESCE($3::int, 14),
  COALESCE($4::boolean, true),
  COALESCE($5::boolean, false),
  COALESCE($6::boolean, true),
  COALESCE($7::boolean, false),
  COALESCE($8::boolean, true),
  COALESCE($9::boolean, true),
  COALESCE($10::boolean, true),
  COALESCE(NULLIF($11::text, ''), 'weighted'),
  COALESCE($12::int, 3),
  COALESCE($13::int, 30),
  COALESCE($14::boolean, true),
  COALESCE($15::boolean, false),
  COALESCE($16::text[], '{}'::text[]),
  COALESCE($17::boolean, false),
  COALESCE($18::text[], '{}'::text[]),
  COALESCE($19::boolean, false),
  COALESCE($20::text[], '{}'::text[]),
  NULLIF($21::text, ''),
  NULLIF($22::text, ''),
  COALESCE(NULLIF($23::text, ''), 'available'),
  COALESCE($24::int, 2)
)
ON CONFLICT (organization_id) DO UPDATE SET
  quote_payment_days = COALESCE($2::int, RAC_organization_settings.quote_payment_days),
  quote_valid_days = COALESCE($3::int, RAC_organization_settings.quote_valid_days),
  ai_auto_disqualify_junk = COALESCE($4::boolean, RAC_organization_settings.ai_auto_disqualify_junk),
  ai_auto_dispatch = COALESCE($5::boolean, RAC_organization_settings.ai_auto_dispatch),
  ai_auto_estimate = COALESCE($6::boolean, RAC_organization_settings.ai_auto_estimate),
  ai_confidence_gate_enabled = COALESCE($7::boolean, RAC_organization_settings.ai_confidence_gate_enabled),
  ai_adaptive_reasoning_enabled = COALESCE($8::boolean, RAC_organization_settings.ai_adaptive_reasoning_enabled),
  ai_experience_memory_enabled = COALESCE($9::boolean, RAC_organization_settings.ai_experience_memory_enabled),
  ai_council_enabled = COALESCE($10::boolean, RAC_organization_settings.ai_council_enabled),
  ai_council_consensus_mode = COALESCE(NULLIF($11::text, ''), RAC_organization_settings.ai_council_consensus_mode),
  catalog_gap_threshold = COALESCE($12::int, RAC_organization_settings.catalog_gap_threshold),
  catalog_gap_lookback_days = COALESCE($13::int, RAC_organization_settings.catalog_gap_lookback_days),
  photo_analysis_preprocessing_enabled = COALESCE($14::boolean, RAC_organization_settings.photo_analysis_preprocessing_enabled),
  photo_analysis_ocr_assist_enabled = COALESCE($15::boolean, RAC_organization_settings.photo_analysis_ocr_assist_enabled),
  photo_analysis_ocr_assist_service_types = COALESCE($16::text[], RAC_organization_settings.photo_analysis_ocr_assist_service_types),
  photo_analysis_lens_correction_enabled = COALESCE($17::boolean, RAC_organization_settings.photo_analysis_lens_correction_enabled),
  photo_analysis_lens_correction_service_types = COALESCE($18::text[], RAC_organization_settings.photo_analysis_lens_correction_service_types),
  photo_analysis_perspective_normalization_enabled = COALESCE($19::boolean, RAC_organization_settings.photo_analysis_perspective_normalization_enabled),
  photo_analysis_perspective_normalization_service_types = COALESCE($20::text[], RAC_organization_settings.photo_analysis_perspective_normalization_service_types),
  notification_email = CASE WHEN $21::text IS NULL THEN RAC_organization_settings.notification_email ELSE NULLIF($21::text, '') END,
  whatsapp_device_id = CASE WHEN $22::text IS NULL THEN RAC_organization_settings.whatsapp_device_id ELSE NULLIF($22::text, '') END,
  whatsapp_presence = COALESCE(NULLIF($23::text, ''), RAC_organization_settings.whatsapp_presence),
  whatsapp_welcome_delay_minutes = COALESCE($24::int, RAC_organization_settings.whatsapp_welcome_delay_minutes),
  updated_at = now()
RETURNING organization_id, quote_payment_days, quote_valid_days,
  ai_auto_disqualify_junk, ai_auto_dispatch, ai_auto_estimate, ai_confidence_gate_enabled,
  ai_adaptive_reasoning_enabled, ai_experience_memory_enabled, ai_council_enabled,
  ai_council_consensus_mode,
  catalog_gap_threshold, catalog_gap_lookback_days,
  photo_analysis_preprocessing_enabled,
  photo_analysis_ocr_assist_enabled,
  photo_analysis_ocr_assist_service_types,
  photo_analysis_lens_correction_enabled,
  photo_analysis_lens_correction_service_types,
  photo_analysis_perspective_normalization_enabled,
  photo_analysis_perspective_normalization_service_types,
  notification_email, whatsapp_device_id, whatsapp_presence, whatsapp_welcome_delay_minutes,
  smtp_host, smtp_port, smtp_username, smtp_password, smtp_from_email, smtp_from_name,
  created_at, updated_at
`

type UpsertOrganizationSettingsParams struct {
	OrganizationID                                    pgtype.UUID `json:"organization_id"`
	QuotePaymentDays                                  pgtype.Int4 `json:"quote_payment_days"`
	QuoteValidDays                                    pgtype.Int4 `json:"quote_valid_days"`
	AiAutoDisqualifyJunk                              pgtype.Bool `json:"ai_auto_disqualify_junk"`
	AiAutoDispatch                                    pgtype.Bool `json:"ai_auto_dispatch"`
	AiAutoEstimate                                    pgtype.Bool `json:"ai_auto_estimate"`
	AiConfidenceGateEnabled                           pgtype.Bool `json:"ai_confidence_gate_enabled"`
	AiAdaptiveReasoningEnabled                        pgtype.Bool `json:"ai_adaptive_reasoning_enabled"`
	AiExperienceMemoryEnabled                         pgtype.Bool `json:"ai_experience_memory_enabled"`
	AiCouncilEnabled                                  pgtype.Bool `json:"ai_council_enabled"`
	AiCouncilConsensusMode                            pgtype.Text `json:"ai_council_consensus_mode"`
	CatalogGapThreshold                               pgtype.Int4 `json:"catalog_gap_threshold"`
	CatalogGapLookbackDays                            pgtype.Int4 `json:"catalog_gap_lookback_days"`
	PhotoAnalysisPreprocessingEnabled                 pgtype.Bool `json:"photo_analysis_preprocessing_enabled"`
	PhotoAnalysisOcrAssistEnabled                     pgtype.Bool `json:"photo_analysis_ocr_assist_enabled"`
	PhotoAnalysisOcrAssistServiceTypes                []string    `json:"photo_analysis_ocr_assist_service_types"`
	PhotoAnalysisLensCorrectionEnabled                pgtype.Bool `json:"photo_analysis_lens_correction_enabled"`
	PhotoAnalysisLensCorrectionServiceTypes           []string    `json:"photo_analysis_lens_correction_service_types"`
	PhotoAnalysisPerspectiveNormalizationEnabled      pgtype.Bool `json:"photo_analysis_perspective_normalization_enabled"`
	PhotoAnalysisPerspectiveNormalizationServiceTypes []string    `json:"photo_analysis_perspective_normalization_service_types"`
	NotificationEmail                                 pgtype.Text `json:"notification_email"`
	WhatsappDeviceID                                  pgtype.Text `json:"whatsapp_device_id"`
	WhatsappPresence                                  pgtype.Text `json:"whatsapp_presence"`
	WhatsappWelcomeDelayMinutes                       pgtype.Int4 `json:"whatsapp_welcome_delay_minutes"`
}

type UpsertOrganizationSettingsRow struct {
	OrganizationID                                    pgtype.UUID        `json:"organization_id"`
	QuotePaymentDays                                  int32              `json:"quote_payment_days"`
	QuoteValidDays                                    int32              `json:"quote_valid_days"`
	AiAutoDisqualifyJunk                              bool               `json:"ai_auto_disqualify_junk"`
	AiAutoDispatch                                    bool               `json:"ai_auto_dispatch"`
	AiAutoEstimate                                    bool               `json:"ai_auto_estimate"`
	AiConfidenceGateEnabled                           bool               `json:"ai_confidence_gate_enabled"`
	AiAdaptiveReasoningEnabled                        bool               `json:"ai_adaptive_reasoning_enabled"`
	AiExperienceMemoryEnabled                         bool               `json:"ai_experience_memory_enabled"`
	AiCouncilEnabled                                  bool               `json:"ai_council_enabled"`
	AiCouncilConsensusMode                            string             `json:"ai_council_consensus_mode"`
	CatalogGapThreshold                               int32              `json:"catalog_gap_threshold"`
	CatalogGapLookbackDays                            int32              `json:"catalog_gap_lookback_days"`
	PhotoAnalysisPreprocessingEnabled                 bool               `json:"photo_analysis_preprocessing_enabled"`
	PhotoAnalysisOcrAssistEnabled                     bool               `json:"photo_analysis_ocr_assist_enabled"`
	PhotoAnalysisOcrAssistServiceTypes                []string           `json:"photo_analysis_ocr_assist_service_types"`
	PhotoAnalysisLensCorrectionEnabled                bool               `json:"photo_analysis_lens_correction_enabled"`
	PhotoAnalysisLensCorrectionServiceTypes           []string           `json:"photo_analysis_lens_correction_service_types"`
	PhotoAnalysisPerspectiveNormalizationEnabled      bool               `json:"photo_analysis_perspective_normalization_enabled"`
	PhotoAnalysisPerspectiveNormalizationServiceTypes []string           `json:"photo_analysis_perspective_normalization_service_types"`
	NotificationEmail                                 pgtype.Text        `json:"notification_email"`
	WhatsappDeviceID                                  pgtype.Text        `json:"whatsapp_device_id"`
	WhatsappPresence                                  string             `json:"whatsapp_presence"`
	WhatsappWelcomeDelayMinutes                       int32              `json:"whatsapp_welcome_delay_minutes"`
	SmtpHost                                          pgtype.Text        `json:"smtp_host"`
	SmtpPort                                          pgtype.Int4        `json:"smtp_port"`
	SmtpUsername                                      pgtype.Text        `json:"smtp_username"`
	SmtpPassword                                      pgtype.Text        `json:"smtp_password"`
	SmtpFromEmail                                     pgtype.Text        `json:"smtp_from_email"`
	SmtpFromName                                      pgtype.Text        `json:"smtp_from_name"`
	CreatedAt                                         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                                         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertOrganizationSettings(ctx context.Context, arg UpsertOrganizationSettingsParams) (UpsertOrganizationSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationSettings,
		arg.OrganizationID,
		arg.QuotePaymentDays,
		arg.QuoteValidDays,
		arg.AiAutoDisqualifyJunk,
		arg.AiAutoDispatch,
		arg.AiAutoEstimate,
		arg.AiConfidenceGateEnabled,
		arg.AiAdaptiveReasoningEnabled,
		arg.AiExperienceMemoryEnabled,
		arg.AiCouncilEnabled,
		arg.AiCouncilConsensusMode,
		arg.CatalogGapThreshold,
		arg.CatalogGapLookbackDays,
		arg.PhotoAnalysisPreprocessingEnabled,
		arg.PhotoAnalysisOcrAssistEnabled,
		arg.PhotoAnalysisOcrAssistServiceTypes,
		arg.PhotoAnalysisLensCorrectionEnabled,
		arg.PhotoAnalysisLensCorrectionServiceTypes,
		arg.PhotoAnalysisPerspectiveNormalizationEnabled,
		arg.PhotoAnalysisPerspectiveNormalizationServiceTypes,
		arg.NotificationEmail,
		arg.WhatsappDeviceID,
		arg.WhatsappPresence,
		arg.WhatsappWelcomeDelayMinutes,
	)
	var i UpsertOrganizationSettingsRow
	err := row.Scan(
		&i.OrganizationID,
		&i.QuotePaymentDays,
		&i.QuoteValidDays,
		&i.AiAutoDisqualifyJunk,
		&i.AiAutoDispatch,
		&i.AiAutoEstimate,
		&i.AiConfidenceGateEnabled,
		&i.AiAdaptiveReasoningEnabled,
		&i.AiExperienceMemoryEnabled,
		&i.AiCouncilEnabled,
		&i.AiCouncilConsensusMode,
		&i.CatalogGapThreshold,
		&i.CatalogGapLookbackDays,
		&i.PhotoAnalysisPreprocessingEnabled,
		&i.PhotoAnalysisOcrAssistEnabled,
		&i.PhotoAnalysisOcrAssistServiceTypes,
		&i.PhotoAnalysisLensCorrectionEnabled,
		&i.PhotoAnalysisLensCorrectionServiceTypes,
		&i.PhotoAnalysisPerspectiveNormalizationEnabled,
		&i.PhotoAnalysisPerspectiveNormalizationServiceTypes,
		&i.NotificationEmail,
		&i.WhatsappDeviceID,
		&i.WhatsappPresence,
		&i.WhatsappWelcomeDelayMinutes,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpUsername,
		&i.SmtpPassword,
		&i.SmtpFromEmail,
		&i.SmtpFromName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkflow = `-- name: UpsertWorkflow :one
INSERT INTO RAC_workflows (
  id, organization_id, workflow_key, name, description, enabled,
  quote_valid_days_override, quote_payment_days_override
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (organization_id, workflow_key) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  enabled = EXCLUDED.enabled,
  quote_valid_days_override = EXCLUDED.quote_valid_days_override,
  quote_payment_days_override = EXCLUDED.quote_payment_days_override,
  updated_at = now()
RETURNING id
`

type UpsertWorkflowParams struct {
	ID                       pgtype.UUID `json:"id"`
	OrganizationID           pgtype.UUID `json:"organization_id"`
	WorkflowKey              string      `json:"workflow_key"`
	Name                     string      `json:"name"`
	Description              pgtype.Text `json:"description"`
	Enabled                  bool        `json:"enabled"`
	QuoteValidDaysOverride   pgtype.Int4 `json:"quote_valid_days_override"`
	QuotePaymentDaysOverride pgtype.Int4 `json:"quote_payment_days_override"`
}

func (q *Queries) UpsertWorkflow(ctx context.Context, arg UpsertWorkflowParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertWorkflow,
		arg.ID,
		arg.OrganizationID,
		arg.WorkflowKey,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.QuoteValidDaysOverride,
		arg.QuotePaymentDaysOverride,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertWorkflowStep = `-- name: UpsertWorkflowStep :one
INSERT INTO RAC_workflow_steps (
  id, organization_id, workflow_id, trigger, channel, audience, action,
  step_order, delay_minutes, enabled, recipient_config, template_subject,
  template_body, stop_on_reply
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb, $12, $13, $14)
ON CONFLICT (workflow_id, trigger, channel, step_order) DO UPDATE
SET
  audience = EXCLUDED.audience,
  action = EXCLUDED.action,
  delay_minutes = EXCLUDED.delay_minutes,
  enabled = EXCLUDED.enabled,
  recipient_config = EXCLUDED.recipient_config,
  template_subject = EXCLUDED.template_subject,
  template_body = EXCLUDED.template_body,
  stop_on_reply = EXCLUDED.stop_on_reply,
  updated_at = now()
RETURNING id
`

type UpsertWorkflowStepParams struct {
	ID              pgtype.UUID `json:"id"`
	OrganizationID  pgtype.UUID `json:"organization_id"`
	WorkflowID      pgtype.UUID `json:"workflow_id"`
	Trigger         string      `json:"trigger"`
	Channel         string      `json:"channel"`
	Audience        string      `json:"audience"`
	Action          string      `json:"action"`
	StepOrder       int32       `json:"step_order"`
	DelayMinutes    int32       `json:"delay_minutes"`
	Enabled         bool        `json:"enabled"`
	Column11        []byte      `json:"column_11"`
	TemplateSubject pgtype.Text `json:"template_subject"`
	TemplateBody    pgtype.Text `json:"template_body"`
	StopOnReply     bool        `json:"stop_on_reply"`
}

func (q *Queries) UpsertWorkflowStep(ctx context.Context, arg UpsertWorkflowStepParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertWorkflowStep,
		arg.ID,
		arg.OrganizationID,
		arg.WorkflowID,
		arg.Trigger,
		arg.Channel,
		arg.Audience,
		arg.Action,
		arg.StepOrder,
		arg.DelayMinutes,
		arg.Enabled,
		arg.Column11,
		arg.TemplateSubject,
		arg.TemplateBody,
		arg.StopOnReply,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const useInvite = `-- name: UseInvite :exec
UPDATE RAC_organization_invites
SET used_at = now(), used_by = $2
WHERE id = $1 AND used_at IS NULL
`

type UseInviteParams struct {
	ID     pgtype.UUID `json:"id"`
	UsedBy pgtype.UUID `json:"used_by"`
}

func (q *Queries) UseInvite(ctx context.Context, arg UseInviteParams) error {
	_, err := q.db.Exec(ctx, useInvite, arg.ID, arg.UsedBy)
	return err
}

const workflowExistsInOrganization = `-- name: WorkflowExistsInOrganization :one
SELECT EXISTS (
  SELECT 1
  FROM RAC_workflows
  WHERE id = $1 AND organization_id = $2
) AS exists
`

type WorkflowExistsInOrganizationParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) WorkflowExistsInOrganization(ctx context.Context, arg WorkflowExistsInOrganizationParams) (bool, error) {
	row := q.db.QueryRow(ctx, workflowExistsInOrganization, arg.ID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
