// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package identitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMember(ctx context.Context, arg AddMemberParams) error
	ClearOrganizationLogo(ctx context.Context, id pgtype.UUID) (ClearOrganizationLogoRow, error)
	ClearOrganizationSMTP(ctx context.Context, organizationID pgtype.UUID) error
	CreateDefaultWorkflowAssignmentRule(ctx context.Context, arg CreateDefaultWorkflowAssignmentRuleParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) (RacOrganizationInvite, error)
	// Identity Domain SQL Queries
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (CreateOrganizationRow, error)
	CreateWorkflowAssignmentRule(ctx context.Context, arg CreateWorkflowAssignmentRuleParams) error
	DefaultWorkflowAssignmentRuleExists(ctx context.Context, organizationID pgtype.UUID) (bool, error)
	DeleteLeadWorkflowOverride(ctx context.Context, arg DeleteLeadWorkflowOverrideParams) error
	DeleteWorkflowAssignmentRulesByOrganization(ctx context.Context, organizationID pgtype.UUID) error
	DeleteWorkflowStepsByWorkflow(ctx context.Context, arg DeleteWorkflowStepsByWorkflowParams) error
	DeleteWorkflowStepsNotInList(ctx context.Context, arg DeleteWorkflowStepsNotInListParams) error
	DeleteWorkflowsByOrganization(ctx context.Context, organizationID pgtype.UUID) error
	DeleteWorkflowsNotInList(ctx context.Context, arg DeleteWorkflowsNotInListParams) error
	GetInviteByToken(ctx context.Context, tokenHash string) (RacOrganizationInvite, error)
	GetLeadWorkflowOverride(ctx context.Context, arg GetLeadWorkflowOverrideParams) (RacLeadWorkflowOverride, error)
	GetOrganization(ctx context.Context, id pgtype.UUID) (GetOrganizationRow, error)
	GetOrganizationSettings(ctx context.Context, organizationID pgtype.UUID) (GetOrganizationSettingsRow, error)
	GetUserOrganizationID(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error)
	LeadExistsInOrganization(ctx context.Context, arg LeadExistsInOrganizationParams) (bool, error)
	ListInvites(ctx context.Context, organizationID pgtype.UUID) ([]RacOrganizationInvite, error)
	ListWorkflowAssignmentRules(ctx context.Context, organizationID pgtype.UUID) ([]RacWorkflowAssignmentRule, error)
	ListWorkflowSteps(ctx context.Context, organizationID pgtype.UUID) ([]RacWorkflowStep, error)
	ListWorkflows(ctx context.Context, organizationID pgtype.UUID) ([]RacWorkflow, error)
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) (RacOrganizationInvite, error)
	UpdateInvite(ctx context.Context, arg UpdateInviteParams) (RacOrganizationInvite, error)
	UpdateOrganizationLogo(ctx context.Context, arg UpdateOrganizationLogoParams) (UpdateOrganizationLogoRow, error)
	UpdateOrganizationProfile(ctx context.Context, arg UpdateOrganizationProfileParams) (UpdateOrganizationProfileRow, error)
	UpsertLeadWorkflowOverride(ctx context.Context, arg UpsertLeadWorkflowOverrideParams) (RacLeadWorkflowOverride, error)
	UpsertOrganizationSMTP(ctx context.Context, arg UpsertOrganizationSMTPParams) (UpsertOrganizationSMTPRow, error)
	UpsertOrganizationSettings(ctx context.Context, arg UpsertOrganizationSettingsParams) (UpsertOrganizationSettingsRow, error)
	UpsertWorkflow(ctx context.Context, arg UpsertWorkflowParams) (pgtype.UUID, error)
	UpsertWorkflowStep(ctx context.Context, arg UpsertWorkflowStepParams) (pgtype.UUID, error)
	UseInvite(ctx context.Context, arg UseInviteParams) error
	WorkflowExistsInOrganization(ctx context.Context, arg WorkflowExistsInOrganizationParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
