-- +goose Up
ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS vat_number TEXT,
  ADD COLUMN IF NOT EXISTS kvk_number TEXT,
  ADD COLUMN IF NOT EXISTS address_line1 TEXT,
  ADD COLUMN IF NOT EXISTS address_line2 TEXT,
  ADD COLUMN IF NOT EXISTS postal_code TEXT,
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS country TEXT;

-- +goose Down
ALTER TABLE organizations
  DROP COLUMN IF EXISTS country,
  DROP COLUMN IF EXISTS city,
  DROP COLUMN IF EXISTS postal_code,
  DROP COLUMN IF EXISTS address_line2,
  DROP COLUMN IF EXISTS address_line1,
  DROP COLUMN IF EXISTS kvk_number,
  DROP COLUMN IF EXISTS vat_number,
  DROP COLUMN IF EXISTS phone,
  DROP COLUMN IF EXISTS email;
