// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package waagentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentUser = `-- name: CreateAgentUser :exec
INSERT INTO RAC_whatsapp_agent_users (phone_number, organization_id, display_name, user_type, partner_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAgentUserParams struct {
	PhoneNumber    string      `json:"phone_number"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	DisplayName    string      `json:"display_name"`
	UserType       string      `json:"user_type"`
	PartnerID      pgtype.UUID `json:"partner_id"`
}

func (q *Queries) CreateAgentUser(ctx context.Context, arg CreateAgentUserParams) error {
	_, err := q.db.Exec(ctx, createAgentUser,
		arg.PhoneNumber,
		arg.OrganizationID,
		arg.DisplayName,
		arg.UserType,
		arg.PartnerID,
	)
	return err
}

const deleteAgentConfig = `-- name: DeleteAgentConfig :exec
DELETE FROM RAC_whatsapp_agent_config
`

func (q *Queries) DeleteAgentConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAgentConfig)
	return err
}

const deleteAgentMessagesByPhone = `-- name: DeleteAgentMessagesByPhone :exec
DELETE FROM RAC_whatsapp_agent_messages
WHERE organization_id = $1
    AND phone_number = $2
`

type DeleteAgentMessagesByPhoneParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PhoneNumber    string      `json:"phone_number"`
}

func (q *Queries) DeleteAgentMessagesByPhone(ctx context.Context, arg DeleteAgentMessagesByPhoneParams) error {
	_, err := q.db.Exec(ctx, deleteAgentMessagesByPhone, arg.OrganizationID, arg.PhoneNumber)
	return err
}

const deleteAgentUser = `-- name: DeleteAgentUser :exec
DELETE FROM RAC_whatsapp_agent_users
WHERE phone_number = $1 AND organization_id = $2
`

type DeleteAgentUserParams struct {
	PhoneNumber    string      `json:"phone_number"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteAgentUser(ctx context.Context, arg DeleteAgentUserParams) error {
	_, err := q.db.Exec(ctx, deleteAgentUser, arg.PhoneNumber, arg.OrganizationID)
	return err
}

const getAgentConfig = `-- name: GetAgentConfig :one
SELECT id, device_id, account_jid, created_at, updated_at
FROM RAC_whatsapp_agent_config
LIMIT 1
`

func (q *Queries) GetAgentConfig(ctx context.Context) (RacWhatsappAgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfig)
	var i RacWhatsappAgentConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.AccountJid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentConfigByDeviceID = `-- name: GetAgentConfigByDeviceID :one
SELECT id, device_id, account_jid, created_at, updated_at
FROM RAC_whatsapp_agent_config
WHERE device_id = $1
`

func (q *Queries) GetAgentConfigByDeviceID(ctx context.Context, deviceID string) (RacWhatsappAgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfigByDeviceID, deviceID)
	var i RacWhatsappAgentConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.AccountJid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentMessageByExternalID = `-- name: GetAgentMessageByExternalID :one
SELECT id, organization_id, phone_number, role, content, external_message_id, metadata, created_at
FROM RAC_whatsapp_agent_messages
WHERE organization_id = $1
    AND external_message_id = $2
LIMIT 1
`

type GetAgentMessageByExternalIDParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ExternalMessageID pgtype.Text `json:"external_message_id"`
}

type GetAgentMessageByExternalIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	PhoneNumber       string             `json:"phone_number"`
	Role              string             `json:"role"`
	Content           string             `json:"content"`
	ExternalMessageID pgtype.Text        `json:"external_message_id"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAgentMessageByExternalID(ctx context.Context, arg GetAgentMessageByExternalIDParams) (GetAgentMessageByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getAgentMessageByExternalID, arg.OrganizationID, arg.ExternalMessageID)
	var i GetAgentMessageByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PhoneNumber,
		&i.Role,
		&i.Content,
		&i.ExternalMessageID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentUserByPhone = `-- name: GetAgentUserByPhone :one
SELECT phone_number, organization_id, display_name, user_type, partner_id, created_at
FROM RAC_whatsapp_agent_users
WHERE phone_number = $1
`

type GetAgentUserByPhoneRow struct {
	PhoneNumber    string             `json:"phone_number"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	DisplayName    string             `json:"display_name"`
	UserType       string             `json:"user_type"`
	PartnerID      pgtype.UUID        `json:"partner_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAgentUserByPhone(ctx context.Context, phoneNumber string) (GetAgentUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getAgentUserByPhone, phoneNumber)
	var i GetAgentUserByPhoneRow
	err := row.Scan(
		&i.PhoneNumber,
		&i.OrganizationID,
		&i.DisplayName,
		&i.UserType,
		&i.PartnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentVoiceTranscriptionByExternalID = `-- name: GetAgentVoiceTranscriptionByExternalID :one
SELECT id, organization_id, external_message_id, phone_number, status, storage_bucket, storage_key, content_type, provider, language, confidence_score, transcript_text, error_message, created_at, updated_at, completed_at
FROM RAC_whatsapp_agent_voice_transcriptions
WHERE organization_id = $1
    AND external_message_id = $2
LIMIT 1
`

type GetAgentVoiceTranscriptionByExternalIDParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ExternalMessageID string      `json:"external_message_id"`
}

func (q *Queries) GetAgentVoiceTranscriptionByExternalID(ctx context.Context, arg GetAgentVoiceTranscriptionByExternalIDParams) (RacWhatsappAgentVoiceTranscription, error) {
	row := q.db.QueryRow(ctx, getAgentVoiceTranscriptionByExternalID, arg.OrganizationID, arg.ExternalMessageID)
	var i RacWhatsappAgentVoiceTranscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalMessageID,
		&i.PhoneNumber,
		&i.Status,
		&i.StorageBucket,
		&i.StorageKey,
		&i.ContentType,
		&i.Provider,
		&i.Language,
		&i.ConfidenceScore,
		&i.TranscriptText,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getRecentAgentMessages = `-- name: GetRecentAgentMessages :many
SELECT id, organization_id, phone_number, role, content, external_message_id, metadata, created_at
FROM RAC_whatsapp_agent_messages
WHERE phone_number = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentAgentMessagesParams struct {
	PhoneNumber string `json:"phone_number"`
	Limit       int32  `json:"limit"`
}

type GetRecentAgentMessagesRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	PhoneNumber       string             `json:"phone_number"`
	Role              string             `json:"role"`
	Content           string             `json:"content"`
	ExternalMessageID pgtype.Text        `json:"external_message_id"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentAgentMessages(ctx context.Context, arg GetRecentAgentMessagesParams) ([]GetRecentAgentMessagesRow, error) {
	rows, err := q.db.Query(ctx, getRecentAgentMessages, arg.PhoneNumber, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentAgentMessagesRow
	for rows.Next() {
		var i GetRecentAgentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PhoneNumber,
			&i.Role,
			&i.Content,
			&i.ExternalMessageID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentInboundAgentMessages = `-- name: GetRecentInboundAgentMessages :many
SELECT id, organization_id, phone_number, role, content, external_message_id, metadata, created_at
FROM RAC_whatsapp_agent_messages
WHERE organization_id = $1
    AND phone_number = $2
    AND role = 'user'
ORDER BY created_at DESC
LIMIT $3
`

type GetRecentInboundAgentMessagesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PhoneNumber    string      `json:"phone_number"`
	Limit          int32       `json:"limit"`
}

type GetRecentInboundAgentMessagesRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrganizationID    pgtype.UUID        `json:"organization_id"`
	PhoneNumber       string             `json:"phone_number"`
	Role              string             `json:"role"`
	Content           string             `json:"content"`
	ExternalMessageID pgtype.Text        `json:"external_message_id"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentInboundAgentMessages(ctx context.Context, arg GetRecentInboundAgentMessagesParams) ([]GetRecentInboundAgentMessagesRow, error) {
	rows, err := q.db.Query(ctx, getRecentInboundAgentMessages, arg.OrganizationID, arg.PhoneNumber, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentInboundAgentMessagesRow
	for rows.Next() {
		var i GetRecentInboundAgentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PhoneNumber,
			&i.Role,
			&i.Content,
			&i.ExternalMessageID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAgentMessage = `-- name: InsertAgentMessage :exec
INSERT INTO RAC_whatsapp_agent_messages (organization_id, phone_number, role, content, external_message_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAgentMessageParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	PhoneNumber       string      `json:"phone_number"`
	Role              string      `json:"role"`
	Content           string      `json:"content"`
	ExternalMessageID pgtype.Text `json:"external_message_id"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) InsertAgentMessage(ctx context.Context, arg InsertAgentMessageParams) error {
	_, err := q.db.Exec(ctx, insertAgentMessage,
		arg.OrganizationID,
		arg.PhoneNumber,
		arg.Role,
		arg.Content,
		arg.ExternalMessageID,
		arg.Metadata,
	)
	return err
}

const listAgentUsersByOrganization = `-- name: ListAgentUsersByOrganization :many
SELECT phone_number, organization_id, display_name, user_type, partner_id, created_at
FROM RAC_whatsapp_agent_users
WHERE organization_id = $1
ORDER BY created_at DESC
`

type ListAgentUsersByOrganizationRow struct {
	PhoneNumber    string             `json:"phone_number"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	DisplayName    string             `json:"display_name"`
	UserType       string             `json:"user_type"`
	PartnerID      pgtype.UUID        `json:"partner_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAgentUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListAgentUsersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listAgentUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentUsersByOrganizationRow
	for rows.Next() {
		var i ListAgentUsersByOrganizationRow
		if err := rows.Scan(
			&i.PhoneNumber,
			&i.OrganizationID,
			&i.DisplayName,
			&i.UserType,
			&i.PartnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentVoiceTranscriptionCompleted = `-- name: MarkAgentVoiceTranscriptionCompleted :exec
UPDATE RAC_whatsapp_agent_voice_transcriptions
SET status = 'completed',
    transcript_text = $3,
    provider = $4,
    language = $5,
    confidence_score = $6,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE organization_id = $1
    AND external_message_id = $2
`

type MarkAgentVoiceTranscriptionCompletedParams struct {
	OrganizationID    pgtype.UUID   `json:"organization_id"`
	ExternalMessageID string        `json:"external_message_id"`
	TranscriptText    pgtype.Text   `json:"transcript_text"`
	Provider          pgtype.Text   `json:"provider"`
	Language          pgtype.Text   `json:"language"`
	ConfidenceScore   pgtype.Float8 `json:"confidence_score"`
}

func (q *Queries) MarkAgentVoiceTranscriptionCompleted(ctx context.Context, arg MarkAgentVoiceTranscriptionCompletedParams) error {
	_, err := q.db.Exec(ctx, markAgentVoiceTranscriptionCompleted,
		arg.OrganizationID,
		arg.ExternalMessageID,
		arg.TranscriptText,
		arg.Provider,
		arg.Language,
		arg.ConfidenceScore,
	)
	return err
}

const markAgentVoiceTranscriptionFailed = `-- name: MarkAgentVoiceTranscriptionFailed :exec
UPDATE RAC_whatsapp_agent_voice_transcriptions
SET status = 'failed',
    error_message = $3,
    updated_at = now()
WHERE organization_id = $1
    AND external_message_id = $2
`

type MarkAgentVoiceTranscriptionFailedParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ExternalMessageID string      `json:"external_message_id"`
	ErrorMessage      pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkAgentVoiceTranscriptionFailed(ctx context.Context, arg MarkAgentVoiceTranscriptionFailedParams) error {
	_, err := q.db.Exec(ctx, markAgentVoiceTranscriptionFailed, arg.OrganizationID, arg.ExternalMessageID, arg.ErrorMessage)
	return err
}

const markAgentVoiceTranscriptionProcessing = `-- name: MarkAgentVoiceTranscriptionProcessing :exec
UPDATE RAC_whatsapp_agent_voice_transcriptions
SET status = 'processing',
    error_message = NULL,
    updated_at = now()
WHERE organization_id = $1
    AND external_message_id = $2
`

type MarkAgentVoiceTranscriptionProcessingParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ExternalMessageID string      `json:"external_message_id"`
}

func (q *Queries) MarkAgentVoiceTranscriptionProcessing(ctx context.Context, arg MarkAgentVoiceTranscriptionProcessingParams) error {
	_, err := q.db.Exec(ctx, markAgentVoiceTranscriptionProcessing, arg.OrganizationID, arg.ExternalMessageID)
	return err
}

const updateAgentMessageByExternalID = `-- name: UpdateAgentMessageByExternalID :exec
UPDATE RAC_whatsapp_agent_messages
SET content = $3,
    metadata = $4
WHERE organization_id = $1
    AND external_message_id = $2
`

type UpdateAgentMessageByExternalIDParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ExternalMessageID pgtype.Text `json:"external_message_id"`
	Content           string      `json:"content"`
	Metadata          []byte      `json:"metadata"`
}

func (q *Queries) UpdateAgentMessageByExternalID(ctx context.Context, arg UpdateAgentMessageByExternalIDParams) error {
	_, err := q.db.Exec(ctx, updateAgentMessageByExternalID,
		arg.OrganizationID,
		arg.ExternalMessageID,
		arg.Content,
		arg.Metadata,
	)
	return err
}

const updateAgentVoiceTranscriptionStorage = `-- name: UpdateAgentVoiceTranscriptionStorage :exec
UPDATE RAC_whatsapp_agent_voice_transcriptions
SET storage_bucket = $3,
    storage_key = $4,
    content_type = $5,
    updated_at = now()
WHERE organization_id = $1
    AND external_message_id = $2
`

type UpdateAgentVoiceTranscriptionStorageParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ExternalMessageID string      `json:"external_message_id"`
	StorageBucket     pgtype.Text `json:"storage_bucket"`
	StorageKey        pgtype.Text `json:"storage_key"`
	ContentType       pgtype.Text `json:"content_type"`
}

func (q *Queries) UpdateAgentVoiceTranscriptionStorage(ctx context.Context, arg UpdateAgentVoiceTranscriptionStorageParams) error {
	_, err := q.db.Exec(ctx, updateAgentVoiceTranscriptionStorage,
		arg.OrganizationID,
		arg.ExternalMessageID,
		arg.StorageBucket,
		arg.StorageKey,
		arg.ContentType,
	)
	return err
}

const upsertAgentConfig = `-- name: UpsertAgentConfig :one
INSERT INTO RAC_whatsapp_agent_config (device_id, account_jid)
VALUES ($1, $2)
ON CONFLICT (device_id) DO UPDATE SET
    account_jid = EXCLUDED.account_jid,
    updated_at = now()
RETURNING id, device_id, account_jid, created_at, updated_at
`

type UpsertAgentConfigParams struct {
	DeviceID   string      `json:"device_id"`
	AccountJid pgtype.Text `json:"account_jid"`
}

func (q *Queries) UpsertAgentConfig(ctx context.Context, arg UpsertAgentConfigParams) (RacWhatsappAgentConfig, error) {
	row := q.db.QueryRow(ctx, upsertAgentConfig, arg.DeviceID, arg.AccountJid)
	var i RacWhatsappAgentConfig
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.AccountJid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentVoiceTranscription = `-- name: UpsertAgentVoiceTranscription :exec
INSERT INTO RAC_whatsapp_agent_voice_transcriptions (
    organization_id,
    external_message_id,
    phone_number,
    status,
    provider,
    error_message
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (organization_id, external_message_id) DO UPDATE SET
    phone_number = EXCLUDED.phone_number,
    status = EXCLUDED.status,
    provider = EXCLUDED.provider,
    error_message = EXCLUDED.error_message,
    updated_at = now()
`

type UpsertAgentVoiceTranscriptionParams struct {
	OrganizationID    pgtype.UUID `json:"organization_id"`
	ExternalMessageID string      `json:"external_message_id"`
	PhoneNumber       string      `json:"phone_number"`
	Status            string      `json:"status"`
	Provider          pgtype.Text `json:"provider"`
	ErrorMessage      pgtype.Text `json:"error_message"`
}

func (q *Queries) UpsertAgentVoiceTranscription(ctx context.Context, arg UpsertAgentVoiceTranscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertAgentVoiceTranscription,
		arg.OrganizationID,
		arg.ExternalMessageID,
		arg.PhoneNumber,
		arg.Status,
		arg.Provider,
		arg.ErrorMessage,
	)
	return err
}
