// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package servicesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServiceTypes = `-- name: CountServiceTypes :one
SELECT COUNT(*)::int AS countValue
FROM RAC_service_types
WHERE organization_id = $1
  AND ($2::text IS NULL OR name ILIKE $2::text OR slug ILIKE $2::text)
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
`

type CountServiceTypesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Search         pgtype.Text `json:"search"`
	IsActive       pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountServiceTypes(ctx context.Context, arg CountServiceTypesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countServiceTypes, arg.OrganizationID, arg.Search, arg.IsActive)
	var countvalue int32
	err := row.Scan(&countvalue)
	return countvalue, err
}

const createServiceType = `-- name: CreateServiceType :one
INSERT INTO RAC_service_types (
  organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color, is_active, created_at, updated_at
`

type CreateServiceTypeParams struct {
	OrganizationID       pgtype.UUID `json:"organization_id"`
	Name                 string      `json:"name"`
	Slug                 string      `json:"slug"`
	Description          pgtype.Text `json:"description"`
	IntakeGuidelines     pgtype.Text `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text `json:"estimation_guidelines"`
	Icon                 pgtype.Text `json:"icon"`
	Color                pgtype.Text `json:"color"`
}

type CreateServiceTypeRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	IntakeGuidelines     pgtype.Text        `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text        `json:"estimation_guidelines"`
	Icon                 pgtype.Text        `json:"icon"`
	Color                pgtype.Text        `json:"color"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (CreateServiceTypeRow, error) {
	row := q.db.QueryRow(ctx, createServiceType,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IntakeGuidelines,
		arg.EstimationGuidelines,
		arg.Icon,
		arg.Color,
	)
	var i CreateServiceTypeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IntakeGuidelines,
		&i.EstimationGuidelines,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceType = `-- name: DeleteServiceType :execrows
DELETE FROM RAC_service_types
WHERE id = $1 AND organization_id = $2
`

type DeleteServiceTypeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceType, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceTypeByID = `-- name: GetServiceTypeByID :one
SELECT id, organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color, is_active, created_at, updated_at
FROM RAC_service_types
WHERE id = $1 AND organization_id = $2
`

type GetServiceTypeByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetServiceTypeByIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	IntakeGuidelines     pgtype.Text        `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text        `json:"estimation_guidelines"`
	Icon                 pgtype.Text        `json:"icon"`
	Color                pgtype.Text        `json:"color"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetServiceTypeByID(ctx context.Context, arg GetServiceTypeByIDParams) (GetServiceTypeByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceTypeByID, arg.ID, arg.OrganizationID)
	var i GetServiceTypeByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IntakeGuidelines,
		&i.EstimationGuidelines,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceTypeBySlug = `-- name: GetServiceTypeBySlug :one
SELECT id, organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color, is_active, created_at, updated_at
FROM RAC_service_types
WHERE slug = $1 AND organization_id = $2
`

type GetServiceTypeBySlugParams struct {
	Slug           string      `json:"slug"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetServiceTypeBySlugRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	IntakeGuidelines     pgtype.Text        `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text        `json:"estimation_guidelines"`
	Icon                 pgtype.Text        `json:"icon"`
	Color                pgtype.Text        `json:"color"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetServiceTypeBySlug(ctx context.Context, arg GetServiceTypeBySlugParams) (GetServiceTypeBySlugRow, error) {
	row := q.db.QueryRow(ctx, getServiceTypeBySlug, arg.Slug, arg.OrganizationID)
	var i GetServiceTypeBySlugRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IntakeGuidelines,
		&i.EstimationGuidelines,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveServiceTypes = `-- name: ListActiveServiceTypes :many
SELECT id, organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color, is_active, created_at, updated_at
FROM RAC_service_types
WHERE organization_id = $1 AND is_active = true
ORDER BY name ASC
`

type ListActiveServiceTypesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	IntakeGuidelines     pgtype.Text        `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text        `json:"estimation_guidelines"`
	Icon                 pgtype.Text        `json:"icon"`
	Color                pgtype.Text        `json:"color"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveServiceTypes(ctx context.Context, organizationID pgtype.UUID) ([]ListActiveServiceTypesRow, error) {
	rows, err := q.db.Query(ctx, listActiveServiceTypes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveServiceTypesRow
	for rows.Next() {
		var i ListActiveServiceTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IntakeGuidelines,
			&i.EstimationGuidelines,
			&i.Icon,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTypes = `-- name: ListServiceTypes :many
SELECT id, organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color, is_active, created_at, updated_at
FROM RAC_service_types
WHERE organization_id = $1
ORDER BY name ASC
`

type ListServiceTypesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	IntakeGuidelines     pgtype.Text        `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text        `json:"estimation_guidelines"`
	Icon                 pgtype.Text        `json:"icon"`
	Color                pgtype.Text        `json:"color"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListServiceTypes(ctx context.Context, organizationID pgtype.UUID) ([]ListServiceTypesRow, error) {
	rows, err := q.db.Query(ctx, listServiceTypes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceTypesRow
	for rows.Next() {
		var i ListServiceTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IntakeGuidelines,
			&i.EstimationGuidelines,
			&i.Icon,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTypesWithFilters = `-- name: ListServiceTypesWithFilters :many
SELECT id, organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color, is_active, created_at, updated_at
FROM RAC_service_types
WHERE organization_id = $1
  AND ($2::text IS NULL OR name ILIKE $2::text OR slug ILIKE $2::text)
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
ORDER BY
  CASE WHEN $4::text = 'name' AND $5::text = 'asc' THEN name END ASC,
  CASE WHEN $4::text = 'name' AND $5::text = 'desc' THEN name END DESC,
  CASE WHEN $4::text = 'slug' AND $5::text = 'asc' THEN slug END ASC,
  CASE WHEN $4::text = 'slug' AND $5::text = 'desc' THEN slug END DESC,
  CASE WHEN $4::text = 'isActive' AND $5::text = 'asc' THEN is_active END ASC,
  CASE WHEN $4::text = 'isActive' AND $5::text = 'desc' THEN is_active END DESC,
  CASE WHEN $4::text = 'createdAt' AND $5::text = 'asc' THEN created_at END ASC,
  CASE WHEN $4::text = 'createdAt' AND $5::text = 'desc' THEN created_at END DESC,
  CASE WHEN $4::text = 'updatedAt' AND $5::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $4::text = 'updatedAt' AND $5::text = 'desc' THEN updated_at END DESC,
  name ASC
LIMIT $7 OFFSET $6
`

type ListServiceTypesWithFiltersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Search         pgtype.Text `json:"search"`
	IsActive       pgtype.Bool `json:"is_active"`
	SortBy         string      `json:"sort_by"`
	SortOrder      string      `json:"sort_order"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
}

type ListServiceTypesWithFiltersRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	IntakeGuidelines     pgtype.Text        `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text        `json:"estimation_guidelines"`
	Icon                 pgtype.Text        `json:"icon"`
	Color                pgtype.Text        `json:"color"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListServiceTypesWithFilters(ctx context.Context, arg ListServiceTypesWithFiltersParams) ([]ListServiceTypesWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, listServiceTypesWithFilters,
		arg.OrganizationID,
		arg.Search,
		arg.IsActive,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiceTypesWithFiltersRow
	for rows.Next() {
		var i ListServiceTypesWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IntakeGuidelines,
			&i.EstimationGuidelines,
			&i.Icon,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceTypeExists = `-- name: ServiceTypeExists :one
SELECT EXISTS(SELECT 1 FROM RAC_service_types WHERE id = $1 AND organization_id = $2)
`

type ServiceTypeExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ServiceTypeExists(ctx context.Context, arg ServiceTypeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceTypeExists, arg.ID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const serviceTypeHasLeadServices = `-- name: ServiceTypeHasLeadServices :one
SELECT EXISTS(SELECT 1 FROM RAC_lead_services WHERE service_type_id = $1 AND organization_id = $2)
`

type ServiceTypeHasLeadServicesParams struct {
	ServiceTypeID  pgtype.UUID `json:"service_type_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ServiceTypeHasLeadServices(ctx context.Context, arg ServiceTypeHasLeadServicesParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceTypeHasLeadServices, arg.ServiceTypeID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setServiceTypeActive = `-- name: SetServiceTypeActive :execrows
UPDATE RAC_service_types
SET is_active = $3, updated_at = now()
WHERE id = $1 AND organization_id = $2
`

type SetServiceTypeActiveParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) SetServiceTypeActive(ctx context.Context, arg SetServiceTypeActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setServiceTypeActive, arg.ID, arg.OrganizationID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateServiceType = `-- name: UpdateServiceType :one
UPDATE RAC_service_types
SET name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    description = COALESCE($3, description),
    intake_guidelines = COALESCE($4, intake_guidelines),
    estimation_guidelines = COALESCE($5, estimation_guidelines),
    icon = COALESCE($6, icon),
    color = COALESCE($7, color),
    updated_at = now()
WHERE id = $8 AND organization_id = $9
RETURNING id, organization_id, name, slug, description, intake_guidelines, estimation_guidelines, icon, color, is_active, created_at, updated_at
`

type UpdateServiceTypeParams struct {
	Name                 pgtype.Text `json:"name"`
	Slug                 pgtype.Text `json:"slug"`
	Description          pgtype.Text `json:"description"`
	IntakeGuidelines     pgtype.Text `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text `json:"estimation_guidelines"`
	Icon                 pgtype.Text `json:"icon"`
	Color                pgtype.Text `json:"color"`
	ID                   pgtype.UUID `json:"id"`
	OrganizationID       pgtype.UUID `json:"organization_id"`
}

type UpdateServiceTypeRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	Description          pgtype.Text        `json:"description"`
	IntakeGuidelines     pgtype.Text        `json:"intake_guidelines"`
	EstimationGuidelines pgtype.Text        `json:"estimation_guidelines"`
	Icon                 pgtype.Text        `json:"icon"`
	Color                pgtype.Text        `json:"color"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (UpdateServiceTypeRow, error) {
	row := q.db.QueryRow(ctx, updateServiceType,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IntakeGuidelines,
		arg.EstimationGuidelines,
		arg.Icon,
		arg.Color,
		arg.ID,
		arg.OrganizationID,
	)
	var i UpdateServiceTypeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IntakeGuidelines,
		&i.EstimationGuidelines,
		&i.Icon,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
