// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package servicesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountServiceTypes(ctx context.Context, arg CountServiceTypesParams) (int32, error)
	CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (CreateServiceTypeRow, error)
	DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) (int64, error)
	GetServiceTypeByID(ctx context.Context, arg GetServiceTypeByIDParams) (GetServiceTypeByIDRow, error)
	GetServiceTypeBySlug(ctx context.Context, arg GetServiceTypeBySlugParams) (GetServiceTypeBySlugRow, error)
	ListActiveServiceTypes(ctx context.Context, organizationID pgtype.UUID) ([]ListActiveServiceTypesRow, error)
	ListServiceTypes(ctx context.Context, organizationID pgtype.UUID) ([]ListServiceTypesRow, error)
	ListServiceTypesWithFilters(ctx context.Context, arg ListServiceTypesWithFiltersParams) ([]ListServiceTypesWithFiltersRow, error)
	ServiceTypeExists(ctx context.Context, arg ServiceTypeExistsParams) (bool, error)
	ServiceTypeHasLeadServices(ctx context.Context, arg ServiceTypeHasLeadServicesParams) (bool, error)
	SetServiceTypeActive(ctx context.Context, arg SetServiceTypeActiveParams) (int64, error)
	UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (UpdateServiceTypeRow, error)
}

var _ Querier = (*Queries)(nil)
