// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package isdedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listInstallationMeldcodesByCodes = `-- name: ListInstallationMeldcodesByCodes :many
SELECT
  meldcode,
  category,
  brand,
  product_name,
  subsidy_amount_cents
FROM RAC_isde_installation_meldcodes
WHERE is_active = TRUE
  AND meldcode = ANY($1::text[])
`

type ListInstallationMeldcodesByCodesRow struct {
	Meldcode           string      `json:"meldcode"`
	Category           string      `json:"category"`
	Brand              pgtype.Text `json:"brand"`
	ProductName        pgtype.Text `json:"product_name"`
	SubsidyAmountCents int64       `json:"subsidy_amount_cents"`
}

func (q *Queries) ListInstallationMeldcodesByCodes(ctx context.Context, meldcodes []string) ([]ListInstallationMeldcodesByCodesRow, error) {
	rows, err := q.db.Query(ctx, listInstallationMeldcodesByCodes, meldcodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstallationMeldcodesByCodesRow
	for rows.Next() {
		var i ListInstallationMeldcodesByCodesRow
		if err := rows.Scan(
			&i.Meldcode,
			&i.Category,
			&i.Brand,
			&i.ProductName,
			&i.SubsidyAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeasureRulesByIDs = `-- name: ListMeasureRulesByIDs :many

SELECT
  measure_id,
  display_name,
  category,
  min_m2,
  performance_rule,
  performance_threshold,
  base_rate_cents_per_m2,
  double_rate_cents_per_m2,
  mki_bonus_cents_per_m2
FROM RAC_isde_measure_rules
WHERE is_active = TRUE
  AND measure_id = ANY($1::text[])
`

type ListMeasureRulesByIDsRow struct {
	MeasureID            string         `json:"measure_id"`
	DisplayName          string         `json:"display_name"`
	Category             string         `json:"category"`
	MinM2                pgtype.Numeric `json:"min_m2"`
	PerformanceRule      string         `json:"performance_rule"`
	PerformanceThreshold pgtype.Numeric `json:"performance_threshold"`
	BaseRateCentsPerM2   int64          `json:"base_rate_cents_per_m2"`
	DoubleRateCentsPerM2 int64          `json:"double_rate_cents_per_m2"`
	MkiBonusCentsPerM2   int64          `json:"mki_bonus_cents_per_m2"`
}

// ISDE Domain SQL Queries
func (q *Queries) ListMeasureRulesByIDs(ctx context.Context, measureIds []string) ([]ListMeasureRulesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listMeasureRulesByIDs, measureIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeasureRulesByIDsRow
	for rows.Next() {
		var i ListMeasureRulesByIDsRow
		if err := rows.Scan(
			&i.MeasureID,
			&i.DisplayName,
			&i.Category,
			&i.MinM2,
			&i.PerformanceRule,
			&i.PerformanceThreshold,
			&i.BaseRateCentsPerM2,
			&i.DoubleRateCentsPerM2,
			&i.MkiBonusCentsPerM2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
