// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package partnersdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptPartnerOffer = `-- name: AcceptPartnerOffer :execrows
UPDATE RAC_partner_offers
SET status = 'accepted',
	accepted_at = now(),
	inspection_availability = $1::jsonb,
	job_availability = $2::jsonb,
	signer_name = $3::text,
	signer_business_name = $4::text,
	signer_address = $5::text,
	signature_data = $6::text,
	updated_at = now()
WHERE id = $7::uuid
  AND status IN ('pending', 'sent')
`

type AcceptPartnerOfferParams struct {
	InspectionSlots    []byte      `json:"inspection_slots"`
	JobSlots           []byte      `json:"job_slots"`
	SignerName         pgtype.Text `json:"signer_name"`
	SignerBusinessName pgtype.Text `json:"signer_business_name"`
	SignerAddress      pgtype.Text `json:"signer_address"`
	SignatureData      pgtype.Text `json:"signature_data"`
	OfferID            pgtype.UUID `json:"offer_id"`
}

func (q *Queries) AcceptPartnerOffer(ctx context.Context, arg AcceptPartnerOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptPartnerOffer,
		arg.InspectionSlots,
		arg.JobSlots,
		arg.SignerName,
		arg.SignerBusinessName,
		arg.SignerAddress,
		arg.SignatureData,
		arg.OfferID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearPartnerLogo = `-- name: ClearPartnerLogo :one
UPDATE RAC_partners
SET logo_file_key = NULL,
	logo_file_name = NULL,
	logo_content_type = NULL,
	logo_size_bytes = NULL,
	updated_at = now()
WHERE id = $1::uuid
  AND organization_id = $2::uuid
RETURNING id, organization_id, business_name, kvk_number, vat_number, address_line1, address_line2, postal_code, city, country, contact_name, contact_email, contact_phone, created_at, updated_at, logo_file_key, logo_file_name, logo_content_type, logo_size_bytes, latitude, longitude, house_number, whatsapp_opted_in
`

type ClearPartnerLogoParams struct {
	PartnerID      pgtype.UUID `json:"partner_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ClearPartnerLogo(ctx context.Context, arg ClearPartnerLogoParams) (RacPartner, error) {
	row := q.db.QueryRow(ctx, clearPartnerLogo, arg.PartnerID, arg.OrganizationID)
	var i RacPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessName,
		&i.KvkNumber,
		&i.VatNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.Latitude,
		&i.Longitude,
		&i.HouseNumber,
		&i.WhatsappOptedIn,
	)
	return i, err
}

const countPartnerOffers = `-- name: CountPartnerOffers :one
SELECT COUNT(*)::bigint
FROM RAC_partner_offers o
JOIN RAC_partners p ON p.id = o.partner_id
JOIN RAC_organizations org ON org.id = o.organization_id
JOIN RAC_lead_services ls ON ls.id = o.lead_service_id
JOIN RAC_service_types st ON st.id = ls.service_type_id AND st.organization_id = ls.organization_id
JOIN RAC_leads l ON l.id = ls.lead_id
WHERE o.organization_id = $1::uuid
  AND (
		$2::text IS NULL
		OR p.business_name ILIKE $2::text
		OR st.name ILIKE $2::text
		OR l.address_city ILIKE $2::text
	  )
  AND ($3::text IS NULL OR o.status::text = $3::text)
  AND ($4::uuid IS NULL OR o.partner_id = $4::uuid)
  AND ($5::uuid IS NULL OR o.lead_service_id = $5::uuid)
  AND ($6::uuid IS NULL OR ls.service_type_id = $6::uuid)
`

type CountPartnerOffersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Search         pgtype.Text `json:"search"`
	Status         pgtype.Text `json:"status"`
	PartnerID      pgtype.UUID `json:"partner_id"`
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	ServiceTypeID  pgtype.UUID `json:"service_type_id"`
}

func (q *Queries) CountPartnerOffers(ctx context.Context, arg CountPartnerOffersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPartnerOffers,
		arg.OrganizationID,
		arg.Search,
		arg.Status,
		arg.PartnerID,
		arg.LeadServiceID,
		arg.ServiceTypeID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPartners = `-- name: CountPartners :one
SELECT COUNT(*)::bigint
FROM RAC_partners
WHERE organization_id = $1::uuid
  AND (
		$2::text IS NULL
		OR business_name ILIKE $2::text
		OR contact_name ILIKE $2::text
		OR contact_email ILIKE $2::text
		OR kvk_number ILIKE $2::text
		OR vat_number ILIKE $2::text
	  )
`

type CountPartnersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Search         pgtype.Text `json:"search"`
}

func (q *Queries) CountPartners(ctx context.Context, arg CountPartnersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPartners, arg.OrganizationID, arg.Search)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countValidServiceTypes = `-- name: CountValidServiceTypes :one
SELECT COUNT(*)::bigint
FROM RAC_service_types
WHERE organization_id = $1::uuid
  AND id = ANY($2::uuid[])
`

type CountValidServiceTypesParams struct {
	OrganizationID pgtype.UUID   `json:"organization_id"`
	ServiceTypeIds []pgtype.UUID `json:"service_type_ids"`
}

func (q *Queries) CountValidServiceTypes(ctx context.Context, arg CountValidServiceTypesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countValidServiceTypes, arg.OrganizationID, arg.ServiceTypeIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPartner = `-- name: CreatePartner :one
INSERT INTO RAC_partners (
	id,
	organization_id,
	business_name,
	kvk_number,
	vat_number,
	address_line1,
	address_line2,
	house_number,
	postal_code,
	city,
	country,
	latitude,
	longitude,
	contact_name,
	contact_email,
	contact_phone,
	whatsapp_opted_in,
	created_at,
	updated_at
) VALUES (
	$1::uuid,
	$2::uuid,
	$3::text,
	$4::text,
	$5::text,
	$6::text,
	$7::text,
	$8::text,
	$9::text,
	$10::text,
	$11::text,
	$12::float8,
	$13::float8,
	$14::text,
	$15::text,
	$16::text,
	$17::bool,
	$18::timestamptz,
	$19::timestamptz
)
RETURNING id, organization_id, business_name, kvk_number, vat_number, address_line1, address_line2, postal_code, city, country, contact_name, contact_email, contact_phone, created_at, updated_at, logo_file_key, logo_file_name, logo_content_type, logo_size_bytes, latitude, longitude, house_number, whatsapp_opted_in
`

type CreatePartnerParams struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	BusinessName    string             `json:"business_name"`
	KvkNumber       pgtype.Text        `json:"kvk_number"`
	VatNumber       pgtype.Text        `json:"vat_number"`
	AddressLine1    string             `json:"address_line1"`
	AddressLine2    pgtype.Text        `json:"address_line2"`
	HouseNumber     pgtype.Text        `json:"house_number"`
	PostalCode      string             `json:"postal_code"`
	City            string             `json:"city"`
	Country         string             `json:"country"`
	Latitude        pgtype.Float8      `json:"latitude"`
	Longitude       pgtype.Float8      `json:"longitude"`
	ContactName     string             `json:"contact_name"`
	ContactEmail    string             `json:"contact_email"`
	ContactPhone    string             `json:"contact_phone"`
	WhatsappOptedIn bool               `json:"whatsapp_opted_in"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (RacPartner, error) {
	row := q.db.QueryRow(ctx, createPartner,
		arg.ID,
		arg.OrganizationID,
		arg.BusinessName,
		arg.KvkNumber,
		arg.VatNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.HouseNumber,
		arg.PostalCode,
		arg.City,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.WhatsappOptedIn,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RacPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessName,
		&i.KvkNumber,
		&i.VatNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.Latitude,
		&i.Longitude,
		&i.HouseNumber,
		&i.WhatsappOptedIn,
	)
	return i, err
}

const createPartnerInvite = `-- name: CreatePartnerInvite :one
INSERT INTO RAC_partner_invites (
	id,
	organization_id,
	partner_id,
	email,
	token_hash,
	expires_at,
	created_by,
	created_at,
	used_at,
	used_by,
	lead_id,
	lead_service_id
) VALUES (
	$1::uuid,
	$2::uuid,
	$3::uuid,
	$4::text,
	$5::text,
	$6::timestamptz,
	$7::uuid,
	$8::timestamptz,
	$9::timestamptz,
	$10::uuid,
	$11::uuid,
	$12::uuid
)
RETURNING id, organization_id, partner_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by, lead_id, lead_service_id
`

type CreatePartnerInviteParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	PartnerID      pgtype.UUID        `json:"partner_id"`
	Email          string             `json:"email"`
	TokenHash      string             `json:"token_hash"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
	UsedBy         pgtype.UUID        `json:"used_by"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
}

func (q *Queries) CreatePartnerInvite(ctx context.Context, arg CreatePartnerInviteParams) (RacPartnerInvite, error) {
	row := q.db.QueryRow(ctx, createPartnerInvite,
		arg.ID,
		arg.OrganizationID,
		arg.PartnerID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UsedAt,
		arg.UsedBy,
		arg.LeadID,
		arg.LeadServiceID,
	)
	var i RacPartnerInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PartnerID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.LeadID,
		&i.LeadServiceID,
	)
	return i, err
}

const createPartnerOffer = `-- name: CreatePartnerOffer :one
INSERT INTO RAC_partner_offers (
	organization_id,
	partner_id,
	lead_service_id,
	public_token,
	expires_at,
	pricing_source,
	customer_price_cents,
	vakman_price_cents,
	margin_basis_points,
	offer_line_items,
	job_summary_short,
	builder_summary,
	requires_inspection,
	status
) VALUES (
	$1::uuid,
	$2::uuid,
	$3::uuid,
	$4::text,
	$5::timestamptz,
	$6::pricing_source,
	$7::bigint,
	$8::bigint,
	$9::int,
	$10::jsonb,
	$11::text,
	$12::text,
	$13::bool,
	'pending'
)
RETURNING id,
	organization_id,
	partner_id,
	lead_service_id,
	public_token,
	expires_at,
	pricing_source::text AS pricing_source,
	customer_price_cents,
	vakman_price_cents,
	margin_basis_points,
	offer_line_items,
	job_summary_short,
	builder_summary,
	status::text AS status,
	requires_inspection,
	accepted_at,
	rejected_at,
	rejection_reason,
	inspection_availability,
	job_availability,
	signer_name,
	signer_business_name,
	signer_address,
	signature_data,
	pdf_file_key,
	created_at,
	updated_at
`

type CreatePartnerOfferParams struct {
	OrganizationID     pgtype.UUID        `json:"organization_id"`
	PartnerID          pgtype.UUID        `json:"partner_id"`
	LeadServiceID      pgtype.UUID        `json:"lead_service_id"`
	PublicToken        string             `json:"public_token"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	PricingSource      PricingSource      `json:"pricing_source"`
	CustomerPriceCents int64              `json:"customer_price_cents"`
	VakmanPriceCents   int64              `json:"vakman_price_cents"`
	MarginBasisPoints  int32              `json:"margin_basis_points"`
	OfferLineItems     []byte             `json:"offer_line_items"`
	JobSummaryShort    pgtype.Text        `json:"job_summary_short"`
	BuilderSummary     pgtype.Text        `json:"builder_summary"`
	RequiresInspection bool               `json:"requires_inspection"`
}

type CreatePartnerOfferRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	PartnerID              pgtype.UUID        `json:"partner_id"`
	LeadServiceID          pgtype.UUID        `json:"lead_service_id"`
	PublicToken            string             `json:"public_token"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	PricingSource          string             `json:"pricing_source"`
	CustomerPriceCents     int64              `json:"customer_price_cents"`
	VakmanPriceCents       int64              `json:"vakman_price_cents"`
	MarginBasisPoints      int32              `json:"margin_basis_points"`
	OfferLineItems         []byte             `json:"offer_line_items"`
	JobSummaryShort        pgtype.Text        `json:"job_summary_short"`
	BuilderSummary         pgtype.Text        `json:"builder_summary"`
	Status                 string             `json:"status"`
	RequiresInspection     bool               `json:"requires_inspection"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	InspectionAvailability []byte             `json:"inspection_availability"`
	JobAvailability        []byte             `json:"job_availability"`
	SignerName             pgtype.Text        `json:"signer_name"`
	SignerBusinessName     pgtype.Text        `json:"signer_business_name"`
	SignerAddress          pgtype.Text        `json:"signer_address"`
	SignatureData          pgtype.Text        `json:"signature_data"`
	PdfFileKey             pgtype.Text        `json:"pdf_file_key"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePartnerOffer(ctx context.Context, arg CreatePartnerOfferParams) (CreatePartnerOfferRow, error) {
	row := q.db.QueryRow(ctx, createPartnerOffer,
		arg.OrganizationID,
		arg.PartnerID,
		arg.LeadServiceID,
		arg.PublicToken,
		arg.ExpiresAt,
		arg.PricingSource,
		arg.CustomerPriceCents,
		arg.VakmanPriceCents,
		arg.MarginBasisPoints,
		arg.OfferLineItems,
		arg.JobSummaryShort,
		arg.BuilderSummary,
		arg.RequiresInspection,
	)
	var i CreatePartnerOfferRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PartnerID,
		&i.LeadServiceID,
		&i.PublicToken,
		&i.ExpiresAt,
		&i.PricingSource,
		&i.CustomerPriceCents,
		&i.VakmanPriceCents,
		&i.MarginBasisPoints,
		&i.OfferLineItems,
		&i.JobSummaryShort,
		&i.BuilderSummary,
		&i.Status,
		&i.RequiresInspection,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.InspectionAvailability,
		&i.JobAvailability,
		&i.SignerName,
		&i.SignerBusinessName,
		&i.SignerAddress,
		&i.SignatureData,
		&i.PdfFileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartnerServiceType = `-- name: CreatePartnerServiceType :exec
INSERT INTO RAC_partner_service_types (partner_id, service_type_id)
VALUES (
	$1::uuid,
	$2::uuid
)
`

type CreatePartnerServiceTypeParams struct {
	PartnerID     pgtype.UUID `json:"partner_id"`
	ServiceTypeID pgtype.UUID `json:"service_type_id"`
}

func (q *Queries) CreatePartnerServiceType(ctx context.Context, arg CreatePartnerServiceTypeParams) error {
	_, err := q.db.Exec(ctx, createPartnerServiceType, arg.PartnerID, arg.ServiceTypeID)
	return err
}

const deletePartner = `-- name: DeletePartner :execrows
DELETE FROM RAC_partners
WHERE id = $1::uuid
  AND organization_id = $2::uuid
`

type DeletePartnerParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeletePartner(ctx context.Context, arg DeletePartnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePartner, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePartnerOffer = `-- name: DeletePartnerOffer :execrows
DELETE FROM RAC_partner_offers
WHERE id = $1::uuid
  AND organization_id = $2::uuid
	AND status::text = ANY($3::text[])
`

type DeletePartnerOfferParams struct {
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Statuses       []string    `json:"statuses"`
}

func (q *Queries) DeletePartnerOffer(ctx context.Context, arg DeletePartnerOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePartnerOffer, arg.OfferID, arg.OrganizationID, arg.Statuses)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePartnerServiceTypes = `-- name: DeletePartnerServiceTypes :exec
DELETE FROM RAC_partner_service_types
WHERE partner_id = $1::uuid
`

func (q *Queries) DeletePartnerServiceTypes(ctx context.Context, partnerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePartnerServiceTypes, partnerID)
	return err
}

const expirePartnerOffers = `-- name: ExpirePartnerOffers :many
UPDATE RAC_partner_offers
SET status = 'expired',
	updated_at = now()
WHERE status IN ('pending', 'sent')
  AND expires_at < now()
RETURNING id, organization_id, partner_id, lead_service_id
`

type ExpirePartnerOffersRow struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PartnerID      pgtype.UUID `json:"partner_id"`
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
}

func (q *Queries) ExpirePartnerOffers(ctx context.Context) ([]ExpirePartnerOffersRow, error) {
	rows, err := q.db.Query(ctx, expirePartnerOffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpirePartnerOffersRow
	for rows.Next() {
		var i ExpirePartnerOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PartnerID,
			&i.LeadServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeadIDForService = `-- name: GetLeadIDForService :one
SELECT lead_id
FROM RAC_lead_services
WHERE id = $1::uuid
  AND organization_id = $2::uuid
`

type GetLeadIDForServiceParams struct {
	ServiceID      pgtype.UUID `json:"service_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetLeadIDForService(ctx context.Context, arg GetLeadIDForServiceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLeadIDForService, arg.ServiceID, arg.OrganizationID)
	var lead_id pgtype.UUID
	err := row.Scan(&lead_id)
	return lead_id, err
}

const getLeadServiceImageAttachmentByID = `-- name: GetLeadServiceImageAttachmentByID :one
SELECT id,
	lead_service_id,
	organization_id,
	file_key,
	file_name,
	content_type,
	size_bytes,
	uploaded_by,
	created_at
FROM RAC_lead_service_attachments
WHERE id = $1::uuid
  AND lead_service_id = $2::uuid
  AND organization_id = $3::uuid
  AND content_type LIKE 'image/%'
`

type GetLeadServiceImageAttachmentByIDParams struct {
	AttachmentID   pgtype.UUID `json:"attachment_id"`
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetLeadServiceImageAttachmentByID(ctx context.Context, arg GetLeadServiceImageAttachmentByIDParams) (RacLeadServiceAttachment, error) {
	row := q.db.QueryRow(ctx, getLeadServiceImageAttachmentByID, arg.AttachmentID, arg.LeadServiceID, arg.OrganizationID)
	var i RacLeadServiceAttachment
	err := row.Scan(
		&i.ID,
		&i.LeadServiceID,
		&i.OrganizationID,
		&i.FileKey,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLeadServiceImageAttachments = `-- name: GetLeadServiceImageAttachments :many
SELECT id,
	lead_service_id,
	organization_id,
	file_key,
	file_name,
	content_type,
	size_bytes,
	uploaded_by,
	created_at
FROM RAC_lead_service_attachments
WHERE lead_service_id = $1::uuid
  AND organization_id = $2::uuid
  AND content_type LIKE 'image/%'
ORDER BY created_at ASC
`

type GetLeadServiceImageAttachmentsParams struct {
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetLeadServiceImageAttachments(ctx context.Context, arg GetLeadServiceImageAttachmentsParams) ([]RacLeadServiceAttachment, error) {
	rows, err := q.db.Query(ctx, getLeadServiceImageAttachments, arg.LeadServiceID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacLeadServiceAttachment
	for rows.Next() {
		var i RacLeadServiceAttachment
		if err := rows.Scan(
			&i.ID,
			&i.LeadServiceID,
			&i.OrganizationID,
			&i.FileKey,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeadServiceSummaryContext = `-- name: GetLeadServiceSummaryContext :one
SELECT ls.lead_id,
	st.name AS service_type,
	COALESCE(ai.urgency_level::text, '') AS urgency_level
FROM RAC_lead_services ls
JOIN RAC_service_types st ON st.id = ls.service_type_id AND st.organization_id = ls.organization_id
LEFT JOIN LATERAL (
	SELECT urgency_level
	FROM RAC_lead_ai_analysis
	WHERE lead_service_id = ls.id
	ORDER BY created_at DESC
	LIMIT 1
) ai ON true
WHERE ls.id = $1::uuid
  AND ls.organization_id = $2::uuid
`

type GetLeadServiceSummaryContextParams struct {
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetLeadServiceSummaryContextRow struct {
	LeadID       pgtype.UUID `json:"lead_id"`
	ServiceType  string      `json:"service_type"`
	UrgencyLevel interface{} `json:"urgency_level"`
}

func (q *Queries) GetLeadServiceSummaryContext(ctx context.Context, arg GetLeadServiceSummaryContextParams) (GetLeadServiceSummaryContextRow, error) {
	row := q.db.QueryRow(ctx, getLeadServiceSummaryContext, arg.LeadServiceID, arg.OrganizationID)
	var i GetLeadServiceSummaryContextRow
	err := row.Scan(&i.LeadID, &i.ServiceType, &i.UrgencyLevel)
	return i, err
}

const getOrganizationName = `-- name: GetOrganizationName :one
SELECT name
FROM RAC_organizations
WHERE id = $1::uuid
`

func (q *Queries) GetOrganizationName(ctx context.Context, organizationID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getOrganizationName, organizationID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getPartnerByID = `-- name: GetPartnerByID :one
SELECT id, organization_id, business_name, kvk_number, vat_number, address_line1, address_line2, postal_code, city, country, contact_name, contact_email, contact_phone, created_at, updated_at, logo_file_key, logo_file_name, logo_content_type, logo_size_bytes, latitude, longitude, house_number, whatsapp_opted_in
FROM RAC_partners
WHERE id = $1::uuid
  AND organization_id = $2::uuid
`

type GetPartnerByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetPartnerByID(ctx context.Context, arg GetPartnerByIDParams) (RacPartner, error) {
	row := q.db.QueryRow(ctx, getPartnerByID, arg.ID, arg.OrganizationID)
	var i RacPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessName,
		&i.KvkNumber,
		&i.VatNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.Latitude,
		&i.Longitude,
		&i.HouseNumber,
		&i.WhatsappOptedIn,
	)
	return i, err
}

const getPartnerOfferByID = `-- name: GetPartnerOfferByID :one
SELECT id,
	organization_id,
	partner_id,
	lead_service_id,
	public_token,
	expires_at,
	pricing_source::text AS pricing_source,
	customer_price_cents,
	vakman_price_cents,
	margin_basis_points,
	offer_line_items,
	job_summary_short,
	builder_summary,
	status::text AS status,
	requires_inspection,
	accepted_at,
	rejected_at,
	rejection_reason,
	inspection_availability,
	job_availability,
	signer_name,
	signer_business_name,
	signer_address,
	signature_data,
	pdf_file_key,
	created_at,
	updated_at
FROM RAC_partner_offers
WHERE id = $1::uuid
  AND organization_id = $2::uuid
`

type GetPartnerOfferByIDParams struct {
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetPartnerOfferByIDRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	PartnerID              pgtype.UUID        `json:"partner_id"`
	LeadServiceID          pgtype.UUID        `json:"lead_service_id"`
	PublicToken            string             `json:"public_token"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	PricingSource          string             `json:"pricing_source"`
	CustomerPriceCents     int64              `json:"customer_price_cents"`
	VakmanPriceCents       int64              `json:"vakman_price_cents"`
	MarginBasisPoints      int32              `json:"margin_basis_points"`
	OfferLineItems         []byte             `json:"offer_line_items"`
	JobSummaryShort        pgtype.Text        `json:"job_summary_short"`
	BuilderSummary         pgtype.Text        `json:"builder_summary"`
	Status                 string             `json:"status"`
	RequiresInspection     bool               `json:"requires_inspection"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	InspectionAvailability []byte             `json:"inspection_availability"`
	JobAvailability        []byte             `json:"job_availability"`
	SignerName             pgtype.Text        `json:"signer_name"`
	SignerBusinessName     pgtype.Text        `json:"signer_business_name"`
	SignerAddress          pgtype.Text        `json:"signer_address"`
	SignatureData          pgtype.Text        `json:"signature_data"`
	PdfFileKey             pgtype.Text        `json:"pdf_file_key"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPartnerOfferByID(ctx context.Context, arg GetPartnerOfferByIDParams) (GetPartnerOfferByIDRow, error) {
	row := q.db.QueryRow(ctx, getPartnerOfferByID, arg.OfferID, arg.OrganizationID)
	var i GetPartnerOfferByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PartnerID,
		&i.LeadServiceID,
		&i.PublicToken,
		&i.ExpiresAt,
		&i.PricingSource,
		&i.CustomerPriceCents,
		&i.VakmanPriceCents,
		&i.MarginBasisPoints,
		&i.OfferLineItems,
		&i.JobSummaryShort,
		&i.BuilderSummary,
		&i.Status,
		&i.RequiresInspection,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.InspectionAvailability,
		&i.JobAvailability,
		&i.SignerName,
		&i.SignerBusinessName,
		&i.SignerAddress,
		&i.SignatureData,
		&i.PdfFileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartnerOfferByIDWithContext = `-- name: GetPartnerOfferByIDWithContext :one
SELECT o.id,
	o.organization_id,
	o.partner_id,
	o.lead_service_id,
	o.public_token,
	o.expires_at,
	o.pricing_source::text AS pricing_source,
	o.customer_price_cents,
	o.vakman_price_cents,
	o.margin_basis_points,
	o.offer_line_items,
	o.job_summary_short,
	o.builder_summary,
	o.status::text AS status,
	o.requires_inspection,
	o.accepted_at,
	o.rejected_at,
	o.rejection_reason,
	o.inspection_availability,
	o.job_availability,
	o.signer_name,
	o.signer_business_name,
	o.signer_address,
	o.signature_data,
	o.pdf_file_key,
	o.created_at,
	o.updated_at,
	p.business_name,
	org.name,
	l.address_city,
	st.name AS service_type,
	st.id AS service_type_id,
	l.lead_enrichment_postcode4,
	l.lead_enrichment_buurtcode,
	l.energy_bouwjaar,
	COALESCE(ai.urgency_level::text, '') AS urgency_level
FROM RAC_partner_offers o
JOIN RAC_partners p ON p.id = o.partner_id
JOIN RAC_organizations org ON org.id = o.organization_id
JOIN RAC_lead_services ls ON ls.id = o.lead_service_id
JOIN RAC_service_types st ON st.id = ls.service_type_id AND st.organization_id = ls.organization_id
JOIN RAC_leads l ON l.id = ls.lead_id
LEFT JOIN LATERAL (
	SELECT urgency_level
	FROM RAC_lead_ai_analysis
	WHERE lead_service_id = ls.id
	ORDER BY created_at DESC
	LIMIT 1
) ai ON true
WHERE o.id = $1::uuid
  AND o.organization_id = $2::uuid
`

type GetPartnerOfferByIDWithContextParams struct {
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetPartnerOfferByIDWithContextRow struct {
	ID                      pgtype.UUID        `json:"id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	PartnerID               pgtype.UUID        `json:"partner_id"`
	LeadServiceID           pgtype.UUID        `json:"lead_service_id"`
	PublicToken             string             `json:"public_token"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	PricingSource           string             `json:"pricing_source"`
	CustomerPriceCents      int64              `json:"customer_price_cents"`
	VakmanPriceCents        int64              `json:"vakman_price_cents"`
	MarginBasisPoints       int32              `json:"margin_basis_points"`
	OfferLineItems          []byte             `json:"offer_line_items"`
	JobSummaryShort         pgtype.Text        `json:"job_summary_short"`
	BuilderSummary          pgtype.Text        `json:"builder_summary"`
	Status                  string             `json:"status"`
	RequiresInspection      bool               `json:"requires_inspection"`
	AcceptedAt              pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt              pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason         pgtype.Text        `json:"rejection_reason"`
	InspectionAvailability  []byte             `json:"inspection_availability"`
	JobAvailability         []byte             `json:"job_availability"`
	SignerName              pgtype.Text        `json:"signer_name"`
	SignerBusinessName      pgtype.Text        `json:"signer_business_name"`
	SignerAddress           pgtype.Text        `json:"signer_address"`
	SignatureData           pgtype.Text        `json:"signature_data"`
	PdfFileKey              pgtype.Text        `json:"pdf_file_key"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	BusinessName            string             `json:"business_name"`
	Name                    string             `json:"name"`
	AddressCity             string             `json:"address_city"`
	ServiceType             string             `json:"service_type"`
	ServiceTypeID           pgtype.UUID        `json:"service_type_id"`
	LeadEnrichmentPostcode4 pgtype.Text        `json:"lead_enrichment_postcode4"`
	LeadEnrichmentBuurtcode pgtype.Text        `json:"lead_enrichment_buurtcode"`
	EnergyBouwjaar          pgtype.Int4        `json:"energy_bouwjaar"`
	UrgencyLevel            interface{}        `json:"urgency_level"`
}

func (q *Queries) GetPartnerOfferByIDWithContext(ctx context.Context, arg GetPartnerOfferByIDWithContextParams) (GetPartnerOfferByIDWithContextRow, error) {
	row := q.db.QueryRow(ctx, getPartnerOfferByIDWithContext, arg.OfferID, arg.OrganizationID)
	var i GetPartnerOfferByIDWithContextRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PartnerID,
		&i.LeadServiceID,
		&i.PublicToken,
		&i.ExpiresAt,
		&i.PricingSource,
		&i.CustomerPriceCents,
		&i.VakmanPriceCents,
		&i.MarginBasisPoints,
		&i.OfferLineItems,
		&i.JobSummaryShort,
		&i.BuilderSummary,
		&i.Status,
		&i.RequiresInspection,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.InspectionAvailability,
		&i.JobAvailability,
		&i.SignerName,
		&i.SignerBusinessName,
		&i.SignerAddress,
		&i.SignatureData,
		&i.PdfFileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessName,
		&i.Name,
		&i.AddressCity,
		&i.ServiceType,
		&i.ServiceTypeID,
		&i.LeadEnrichmentPostcode4,
		&i.LeadEnrichmentBuurtcode,
		&i.EnergyBouwjaar,
		&i.UrgencyLevel,
	)
	return i, err
}

const getPartnerOfferByTokenWithContext = `-- name: GetPartnerOfferByTokenWithContext :one
SELECT o.id,
	o.organization_id,
	o.partner_id,
	o.lead_service_id,
	o.public_token,
	o.expires_at,
	o.pricing_source::text AS pricing_source,
	o.customer_price_cents,
	o.vakman_price_cents,
	o.margin_basis_points,
	o.offer_line_items,
	o.job_summary_short,
	o.builder_summary,
	o.status::text AS status,
	o.requires_inspection,
	o.accepted_at,
	o.rejected_at,
	o.rejection_reason,
	o.inspection_availability,
	o.job_availability,
	o.signer_name,
	o.signer_business_name,
	o.signer_address,
	o.signature_data,
	o.pdf_file_key,
	o.created_at,
	o.updated_at,
	p.business_name,
	org.name,
	l.address_city,
	st.name AS service_type,
	st.id AS service_type_id,
	l.lead_enrichment_postcode4,
	l.lead_enrichment_buurtcode,
	l.energy_bouwjaar,
	COALESCE(ai.urgency_level::text, '') AS urgency_level
FROM RAC_partner_offers o
JOIN RAC_partners p ON p.id = o.partner_id
JOIN RAC_organizations org ON org.id = o.organization_id
JOIN RAC_lead_services ls ON ls.id = o.lead_service_id
JOIN RAC_service_types st ON st.id = ls.service_type_id AND st.organization_id = ls.organization_id
JOIN RAC_leads l ON l.id = ls.lead_id
LEFT JOIN LATERAL (
	SELECT urgency_level
	FROM RAC_lead_ai_analysis
	WHERE lead_service_id = ls.id
	ORDER BY created_at DESC
	LIMIT 1
) ai ON true
WHERE o.public_token = $1::text
`

type GetPartnerOfferByTokenWithContextRow struct {
	ID                      pgtype.UUID        `json:"id"`
	OrganizationID          pgtype.UUID        `json:"organization_id"`
	PartnerID               pgtype.UUID        `json:"partner_id"`
	LeadServiceID           pgtype.UUID        `json:"lead_service_id"`
	PublicToken             string             `json:"public_token"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	PricingSource           string             `json:"pricing_source"`
	CustomerPriceCents      int64              `json:"customer_price_cents"`
	VakmanPriceCents        int64              `json:"vakman_price_cents"`
	MarginBasisPoints       int32              `json:"margin_basis_points"`
	OfferLineItems          []byte             `json:"offer_line_items"`
	JobSummaryShort         pgtype.Text        `json:"job_summary_short"`
	BuilderSummary          pgtype.Text        `json:"builder_summary"`
	Status                  string             `json:"status"`
	RequiresInspection      bool               `json:"requires_inspection"`
	AcceptedAt              pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt              pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason         pgtype.Text        `json:"rejection_reason"`
	InspectionAvailability  []byte             `json:"inspection_availability"`
	JobAvailability         []byte             `json:"job_availability"`
	SignerName              pgtype.Text        `json:"signer_name"`
	SignerBusinessName      pgtype.Text        `json:"signer_business_name"`
	SignerAddress           pgtype.Text        `json:"signer_address"`
	SignatureData           pgtype.Text        `json:"signature_data"`
	PdfFileKey              pgtype.Text        `json:"pdf_file_key"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	BusinessName            string             `json:"business_name"`
	Name                    string             `json:"name"`
	AddressCity             string             `json:"address_city"`
	ServiceType             string             `json:"service_type"`
	ServiceTypeID           pgtype.UUID        `json:"service_type_id"`
	LeadEnrichmentPostcode4 pgtype.Text        `json:"lead_enrichment_postcode4"`
	LeadEnrichmentBuurtcode pgtype.Text        `json:"lead_enrichment_buurtcode"`
	EnergyBouwjaar          pgtype.Int4        `json:"energy_bouwjaar"`
	UrgencyLevel            interface{}        `json:"urgency_level"`
}

func (q *Queries) GetPartnerOfferByTokenWithContext(ctx context.Context, publicToken string) (GetPartnerOfferByTokenWithContextRow, error) {
	row := q.db.QueryRow(ctx, getPartnerOfferByTokenWithContext, publicToken)
	var i GetPartnerOfferByTokenWithContextRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PartnerID,
		&i.LeadServiceID,
		&i.PublicToken,
		&i.ExpiresAt,
		&i.PricingSource,
		&i.CustomerPriceCents,
		&i.VakmanPriceCents,
		&i.MarginBasisPoints,
		&i.OfferLineItems,
		&i.JobSummaryShort,
		&i.BuilderSummary,
		&i.Status,
		&i.RequiresInspection,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.InspectionAvailability,
		&i.JobAvailability,
		&i.SignerName,
		&i.SignerBusinessName,
		&i.SignerAddress,
		&i.SignatureData,
		&i.PdfFileKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessName,
		&i.Name,
		&i.AddressCity,
		&i.ServiceType,
		&i.ServiceTypeID,
		&i.LeadEnrichmentPostcode4,
		&i.LeadEnrichmentBuurtcode,
		&i.EnergyBouwjaar,
		&i.UrgencyLevel,
	)
	return i, err
}

const getQuoteForPartnerOffer = `-- name: GetQuoteForPartnerOffer :one
SELECT id,
	organization_id,
	lead_id,
	lead_service_id,
	status::text AS status,
	total_cents
FROM RAC_quotes
WHERE id = $1::uuid
  AND organization_id = $2::uuid
`

type GetQuoteForPartnerOfferParams struct {
	QuoteID        pgtype.UUID `json:"quote_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetQuoteForPartnerOfferRow struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	LeadID         pgtype.UUID `json:"lead_id"`
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	Status         string      `json:"status"`
	TotalCents     int64       `json:"total_cents"`
}

func (q *Queries) GetQuoteForPartnerOffer(ctx context.Context, arg GetQuoteForPartnerOfferParams) (GetQuoteForPartnerOfferRow, error) {
	row := q.db.QueryRow(ctx, getQuoteForPartnerOffer, arg.QuoteID, arg.OrganizationID)
	var i GetQuoteForPartnerOfferRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LeadID,
		&i.LeadServiceID,
		&i.Status,
		&i.TotalCents,
	)
	return i, err
}

const hasActivePartnerOffer = `-- name: HasActivePartnerOffer :one
SELECT EXISTS(
	SELECT 1
	FROM RAC_partner_offers
	WHERE lead_service_id = $1::uuid
	  AND status IN ('pending', 'sent')
)
`

func (q *Queries) HasActivePartnerOffer(ctx context.Context, leadServiceID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActivePartnerOffer, leadServiceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const leadExists = `-- name: LeadExists :one
SELECT EXISTS(
	SELECT 1
	FROM RAC_leads
	WHERE id = $1::uuid
	  AND organization_id = $2::uuid
)
`

type LeadExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) LeadExists(ctx context.Context, arg LeadExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, leadExists, arg.ID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const leadServiceExists = `-- name: LeadServiceExists :one
SELECT EXISTS(
	SELECT 1
	FROM RAC_lead_services
	WHERE id = $1::uuid
	  AND organization_id = $2::uuid
)
`

type LeadServiceExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) LeadServiceExists(ctx context.Context, arg LeadServiceExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, leadServiceExists, arg.ID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkPartnerLead = `-- name: LinkPartnerLead :execrows
INSERT INTO RAC_partner_leads (organization_id, partner_id, lead_id)
VALUES (
	$1::uuid,
	$2::uuid,
	$3::uuid
)
ON CONFLICT DO NOTHING
`

type LinkPartnerLeadParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PartnerID      pgtype.UUID `json:"partner_id"`
	LeadID         pgtype.UUID `json:"lead_id"`
}

func (q *Queries) LinkPartnerLead(ctx context.Context, arg LinkPartnerLeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkPartnerLead, arg.OrganizationID, arg.PartnerID, arg.LeadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLatestQuoteItemsForService = `-- name: ListLatestQuoteItemsForService :many
WITH latest_quote AS (
	SELECT id
	FROM RAC_quotes
	WHERE lead_service_id = $1::uuid
	  AND organization_id = $2::uuid
	  AND status != 'Draft'
	ORDER BY created_at DESC
	LIMIT 1
)
SELECT qi.description,
	qi.quantity::text AS quantity,
	qi.id,
	qi.unit_price_cents,
	ROUND((qi.quantity_numeric * qi.unit_price_cents::numeric) * (1 + qi.tax_rate::numeric / 10000))::bigint AS line_total_cents
FROM RAC_quote_items qi
JOIN latest_quote lq ON lq.id = qi.quote_id
WHERE qi.is_optional = FALSE OR qi.is_selected = TRUE
ORDER BY qi.sort_order ASC
`

type ListLatestQuoteItemsForServiceParams struct {
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListLatestQuoteItemsForServiceRow struct {
	Description    string      `json:"description"`
	Quantity       string      `json:"quantity"`
	ID             pgtype.UUID `json:"id"`
	UnitPriceCents int64       `json:"unit_price_cents"`
	LineTotalCents int64       `json:"line_total_cents"`
}

func (q *Queries) ListLatestQuoteItemsForService(ctx context.Context, arg ListLatestQuoteItemsForServiceParams) ([]ListLatestQuoteItemsForServiceRow, error) {
	rows, err := q.db.Query(ctx, listLatestQuoteItemsForService, arg.LeadServiceID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestQuoteItemsForServiceRow
	for rows.Next() {
		var i ListLatestQuoteItemsForServiceRow
		if err := rows.Scan(
			&i.Description,
			&i.Quantity,
			&i.ID,
			&i.UnitPriceCents,
			&i.LineTotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerInvites = `-- name: ListPartnerInvites :many
SELECT id, organization_id, partner_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by, lead_id, lead_service_id
FROM RAC_partner_invites
WHERE organization_id = $1::uuid
  AND partner_id = $2::uuid
ORDER BY created_at DESC
`

type ListPartnerInvitesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PartnerID      pgtype.UUID `json:"partner_id"`
}

func (q *Queries) ListPartnerInvites(ctx context.Context, arg ListPartnerInvitesParams) ([]RacPartnerInvite, error) {
	rows, err := q.db.Query(ctx, listPartnerInvites, arg.OrganizationID, arg.PartnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacPartnerInvite
	for rows.Next() {
		var i RacPartnerInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PartnerID,
			&i.Email,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedBy,
			&i.LeadID,
			&i.LeadServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerLeads = `-- name: ListPartnerLeads :many
SELECT l.id,
	l.consumer_first_name,
	l.consumer_last_name,
	l.consumer_phone,
	l.address_street,
	COALESCE(l.address_house_number, '')::text AS house_number,
	l.address_city
FROM RAC_partner_leads pl
JOIN RAC_leads l ON l.id = pl.lead_id
WHERE pl.organization_id = $1::uuid
  AND pl.partner_id = $2::uuid
ORDER BY l.created_at DESC
`

type ListPartnerLeadsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PartnerID      pgtype.UUID `json:"partner_id"`
}

type ListPartnerLeadsRow struct {
	ID                pgtype.UUID `json:"id"`
	ConsumerFirstName string      `json:"consumer_first_name"`
	ConsumerLastName  string      `json:"consumer_last_name"`
	ConsumerPhone     string      `json:"consumer_phone"`
	AddressStreet     string      `json:"address_street"`
	HouseNumber       string      `json:"house_number"`
	AddressCity       string      `json:"address_city"`
}

func (q *Queries) ListPartnerLeads(ctx context.Context, arg ListPartnerLeadsParams) ([]ListPartnerLeadsRow, error) {
	rows, err := q.db.Query(ctx, listPartnerLeads, arg.OrganizationID, arg.PartnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerLeadsRow
	for rows.Next() {
		var i ListPartnerLeadsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerFirstName,
			&i.ConsumerLastName,
			&i.ConsumerPhone,
			&i.AddressStreet,
			&i.HouseNumber,
			&i.AddressCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerOffers = `-- name: ListPartnerOffers :many
SELECT o.id,
	o.organization_id,
	o.partner_id,
	o.lead_service_id,
	o.public_token,
	o.expires_at,
	o.pricing_source::text AS pricing_source,
	o.customer_price_cents,
	o.vakman_price_cents,
	o.margin_basis_points,
	o.offer_line_items,
	o.job_summary_short,
	o.builder_summary,
	o.status::text AS status,
	o.accepted_at,
	o.rejected_at,
	o.rejection_reason,
	o.inspection_availability,
	o.job_availability,
	o.created_at,
	o.updated_at,
	p.business_name,
	org.name,
	l.address_city,
	st.name AS service_type,
	ls.service_type_id
FROM RAC_partner_offers o
JOIN RAC_partners p ON p.id = o.partner_id
JOIN RAC_organizations org ON org.id = o.organization_id
JOIN RAC_lead_services ls ON ls.id = o.lead_service_id
JOIN RAC_service_types st ON st.id = ls.service_type_id AND st.organization_id = ls.organization_id
JOIN RAC_leads l ON l.id = ls.lead_id
WHERE o.organization_id = $1::uuid
  AND (
		$2::text IS NULL
		OR p.business_name ILIKE $2::text
		OR st.name ILIKE $2::text
		OR l.address_city ILIKE $2::text
	  )
  AND ($3::text IS NULL OR o.status::text = $3::text)
  AND ($4::uuid IS NULL OR o.partner_id = $4::uuid)
  AND ($5::uuid IS NULL OR o.lead_service_id = $5::uuid)
  AND ($6::uuid IS NULL OR ls.service_type_id = $6::uuid)
ORDER BY
	CASE WHEN $7::text = 'createdAt' AND $8::text = 'asc' THEN o.created_at END ASC,
	CASE WHEN $7::text = 'createdAt' AND $8::text = 'desc' THEN o.created_at END DESC,
	CASE WHEN $7::text = 'expiresAt' AND $8::text = 'asc' THEN o.expires_at END ASC,
	CASE WHEN $7::text = 'expiresAt' AND $8::text = 'desc' THEN o.expires_at END DESC,
	CASE WHEN $7::text = 'status' AND $8::text = 'asc' THEN o.status::text END ASC,
	CASE WHEN $7::text = 'status' AND $8::text = 'desc' THEN o.status::text END DESC,
	CASE WHEN $7::text = 'partnerName' AND $8::text = 'asc' THEN p.business_name END ASC,
	CASE WHEN $7::text = 'partnerName' AND $8::text = 'desc' THEN p.business_name END DESC,
	CASE WHEN $7::text = 'serviceType' AND $8::text = 'asc' THEN st.name END ASC,
	CASE WHEN $7::text = 'serviceType' AND $8::text = 'desc' THEN st.name END DESC,
	CASE WHEN $7::text = 'vakmanPriceCents' AND $8::text = 'asc' THEN o.vakman_price_cents END ASC,
	CASE WHEN $7::text = 'vakmanPriceCents' AND $8::text = 'desc' THEN o.vakman_price_cents END DESC,
	CASE WHEN $7::text = 'customerPriceCents' AND $8::text = 'asc' THEN o.customer_price_cents END ASC,
	CASE WHEN $7::text = 'customerPriceCents' AND $8::text = 'desc' THEN o.customer_price_cents END DESC,
	o.created_at DESC
LIMIT $10::int
OFFSET $9::int
`

type ListPartnerOffersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Search         pgtype.Text `json:"search"`
	Status         pgtype.Text `json:"status"`
	PartnerID      pgtype.UUID `json:"partner_id"`
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	ServiceTypeID  pgtype.UUID `json:"service_type_id"`
	SortBy         string      `json:"sort_by"`
	SortOrder      string      `json:"sort_order"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

type ListPartnerOffersRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	PartnerID              pgtype.UUID        `json:"partner_id"`
	LeadServiceID          pgtype.UUID        `json:"lead_service_id"`
	PublicToken            string             `json:"public_token"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	PricingSource          string             `json:"pricing_source"`
	CustomerPriceCents     int64              `json:"customer_price_cents"`
	VakmanPriceCents       int64              `json:"vakman_price_cents"`
	MarginBasisPoints      int32              `json:"margin_basis_points"`
	OfferLineItems         []byte             `json:"offer_line_items"`
	JobSummaryShort        pgtype.Text        `json:"job_summary_short"`
	BuilderSummary         pgtype.Text        `json:"builder_summary"`
	Status                 string             `json:"status"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	InspectionAvailability []byte             `json:"inspection_availability"`
	JobAvailability        []byte             `json:"job_availability"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	BusinessName           string             `json:"business_name"`
	Name                   string             `json:"name"`
	AddressCity            string             `json:"address_city"`
	ServiceType            string             `json:"service_type"`
	ServiceTypeID          pgtype.UUID        `json:"service_type_id"`
}

func (q *Queries) ListPartnerOffers(ctx context.Context, arg ListPartnerOffersParams) ([]ListPartnerOffersRow, error) {
	rows, err := q.db.Query(ctx, listPartnerOffers,
		arg.OrganizationID,
		arg.Search,
		arg.Status,
		arg.PartnerID,
		arg.LeadServiceID,
		arg.ServiceTypeID,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerOffersRow
	for rows.Next() {
		var i ListPartnerOffersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PartnerID,
			&i.LeadServiceID,
			&i.PublicToken,
			&i.ExpiresAt,
			&i.PricingSource,
			&i.CustomerPriceCents,
			&i.VakmanPriceCents,
			&i.MarginBasisPoints,
			&i.OfferLineItems,
			&i.JobSummaryShort,
			&i.BuilderSummary,
			&i.Status,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.InspectionAvailability,
			&i.JobAvailability,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusinessName,
			&i.Name,
			&i.AddressCity,
			&i.ServiceType,
			&i.ServiceTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerOffersByPartner = `-- name: ListPartnerOffersByPartner :many
SELECT o.id,
	o.organization_id,
	o.partner_id,
	o.lead_service_id,
	o.public_token,
	o.expires_at,
	o.pricing_source::text AS pricing_source,
	o.customer_price_cents,
	o.vakman_price_cents,
	o.margin_basis_points,
	o.offer_line_items,
	o.status::text AS status,
	o.accepted_at,
	o.rejected_at,
	o.rejection_reason,
	o.inspection_availability,
	o.job_availability,
	o.created_at,
	o.updated_at,
	p.business_name,
	org.name,
	l.address_city,
	st.name AS service_type,
	ls.service_type_id
FROM RAC_partner_offers o
JOIN RAC_partners p ON p.id = o.partner_id
JOIN RAC_organizations org ON org.id = o.organization_id
JOIN RAC_lead_services ls ON ls.id = o.lead_service_id
JOIN RAC_service_types st ON st.id = ls.service_type_id AND st.organization_id = ls.organization_id
JOIN RAC_leads l ON l.id = ls.lead_id
WHERE o.partner_id = $1::uuid
  AND o.organization_id = $2::uuid
ORDER BY o.created_at DESC
`

type ListPartnerOffersByPartnerParams struct {
	PartnerID      pgtype.UUID `json:"partner_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListPartnerOffersByPartnerRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	PartnerID              pgtype.UUID        `json:"partner_id"`
	LeadServiceID          pgtype.UUID        `json:"lead_service_id"`
	PublicToken            string             `json:"public_token"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	PricingSource          string             `json:"pricing_source"`
	CustomerPriceCents     int64              `json:"customer_price_cents"`
	VakmanPriceCents       int64              `json:"vakman_price_cents"`
	MarginBasisPoints      int32              `json:"margin_basis_points"`
	OfferLineItems         []byte             `json:"offer_line_items"`
	Status                 string             `json:"status"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	InspectionAvailability []byte             `json:"inspection_availability"`
	JobAvailability        []byte             `json:"job_availability"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	BusinessName           string             `json:"business_name"`
	Name                   string             `json:"name"`
	AddressCity            string             `json:"address_city"`
	ServiceType            string             `json:"service_type"`
	ServiceTypeID          pgtype.UUID        `json:"service_type_id"`
}

func (q *Queries) ListPartnerOffersByPartner(ctx context.Context, arg ListPartnerOffersByPartnerParams) ([]ListPartnerOffersByPartnerRow, error) {
	rows, err := q.db.Query(ctx, listPartnerOffersByPartner, arg.PartnerID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerOffersByPartnerRow
	for rows.Next() {
		var i ListPartnerOffersByPartnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PartnerID,
			&i.LeadServiceID,
			&i.PublicToken,
			&i.ExpiresAt,
			&i.PricingSource,
			&i.CustomerPriceCents,
			&i.VakmanPriceCents,
			&i.MarginBasisPoints,
			&i.OfferLineItems,
			&i.Status,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.InspectionAvailability,
			&i.JobAvailability,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusinessName,
			&i.Name,
			&i.AddressCity,
			&i.ServiceType,
			&i.ServiceTypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerOffersForService = `-- name: ListPartnerOffersForService :many
SELECT o.id,
	o.organization_id,
	o.partner_id,
	o.lead_service_id,
	o.public_token,
	o.expires_at,
	o.pricing_source::text AS pricing_source,
	o.customer_price_cents,
	o.vakman_price_cents,
	o.margin_basis_points,
	o.offer_line_items,
	o.status::text AS status,
	o.accepted_at,
	o.rejected_at,
	o.rejection_reason,
	o.inspection_availability,
	o.job_availability,
	o.created_at,
	o.updated_at,
	p.business_name
FROM RAC_partner_offers o
JOIN RAC_partners p ON p.id = o.partner_id
WHERE o.lead_service_id = $1::uuid
  AND o.organization_id = $2::uuid
ORDER BY o.created_at DESC
`

type ListPartnerOffersForServiceParams struct {
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListPartnerOffersForServiceRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OrganizationID         pgtype.UUID        `json:"organization_id"`
	PartnerID              pgtype.UUID        `json:"partner_id"`
	LeadServiceID          pgtype.UUID        `json:"lead_service_id"`
	PublicToken            string             `json:"public_token"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	PricingSource          string             `json:"pricing_source"`
	CustomerPriceCents     int64              `json:"customer_price_cents"`
	VakmanPriceCents       int64              `json:"vakman_price_cents"`
	MarginBasisPoints      int32              `json:"margin_basis_points"`
	OfferLineItems         []byte             `json:"offer_line_items"`
	Status                 string             `json:"status"`
	AcceptedAt             pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	InspectionAvailability []byte             `json:"inspection_availability"`
	JobAvailability        []byte             `json:"job_availability"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	BusinessName           string             `json:"business_name"`
}

func (q *Queries) ListPartnerOffersForService(ctx context.Context, arg ListPartnerOffersForServiceParams) ([]ListPartnerOffersForServiceRow, error) {
	rows, err := q.db.Query(ctx, listPartnerOffersForService, arg.LeadServiceID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnerOffersForServiceRow
	for rows.Next() {
		var i ListPartnerOffersForServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PartnerID,
			&i.LeadServiceID,
			&i.PublicToken,
			&i.ExpiresAt,
			&i.PricingSource,
			&i.CustomerPriceCents,
			&i.VakmanPriceCents,
			&i.MarginBasisPoints,
			&i.OfferLineItems,
			&i.Status,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.InspectionAvailability,
			&i.JobAvailability,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusinessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartnerServiceTypeIDs = `-- name: ListPartnerServiceTypeIDs :many
SELECT pst.service_type_id
FROM RAC_partner_service_types pst
JOIN RAC_service_types st ON st.id = pst.service_type_id
WHERE pst.partner_id = $1::uuid
  AND st.organization_id = $2::uuid
ORDER BY st.name ASC
`

type ListPartnerServiceTypeIDsParams struct {
	PartnerID      pgtype.UUID `json:"partner_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListPartnerServiceTypeIDs(ctx context.Context, arg ListPartnerServiceTypeIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPartnerServiceTypeIDs, arg.PartnerID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var service_type_id pgtype.UUID
		if err := rows.Scan(&service_type_id); err != nil {
			return nil, err
		}
		items = append(items, service_type_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartners = `-- name: ListPartners :many
SELECT id, organization_id, business_name, kvk_number, vat_number, address_line1, address_line2, postal_code, city, country, contact_name, contact_email, contact_phone, created_at, updated_at, logo_file_key, logo_file_name, logo_content_type, logo_size_bytes, latitude, longitude, house_number, whatsapp_opted_in
FROM RAC_partners
WHERE organization_id = $1::uuid
  AND (
		$2::text IS NULL
		OR business_name ILIKE $2::text
		OR contact_name ILIKE $2::text
		OR contact_email ILIKE $2::text
		OR kvk_number ILIKE $2::text
		OR vat_number ILIKE $2::text
	  )
ORDER BY
	CASE WHEN $3::text = 'businessName' AND $4::text = 'asc' THEN business_name END ASC,
	CASE WHEN $3::text = 'businessName' AND $4::text = 'desc' THEN business_name END DESC,
	CASE WHEN $3::text = 'contactName' AND $4::text = 'asc' THEN contact_name END ASC,
	CASE WHEN $3::text = 'contactName' AND $4::text = 'desc' THEN contact_name END DESC,
	CASE WHEN $3::text = 'createdAt' AND $4::text = 'asc' THEN created_at END ASC,
	CASE WHEN $3::text = 'createdAt' AND $4::text = 'desc' THEN created_at END DESC,
	CASE WHEN $3::text = 'updatedAt' AND $4::text = 'asc' THEN updated_at END ASC,
	CASE WHEN $3::text = 'updatedAt' AND $4::text = 'desc' THEN updated_at END DESC,
	business_name ASC
LIMIT $6::int
OFFSET $5::int
`

type ListPartnersParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Search         pgtype.Text `json:"search"`
	SortBy         string      `json:"sort_by"`
	SortOrder      string      `json:"sort_order"`
	OffsetCount    int32       `json:"offset_count"`
	LimitCount     int32       `json:"limit_count"`
}

func (q *Queries) ListPartners(ctx context.Context, arg ListPartnersParams) ([]RacPartner, error) {
	rows, err := q.db.Query(ctx, listPartners,
		arg.OrganizationID,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacPartner
	for rows.Next() {
		var i RacPartner
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.BusinessName,
			&i.KvkNumber,
			&i.VatNumber,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.PostalCode,
			&i.City,
			&i.Country,
			&i.ContactName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoFileKey,
			&i.LogoFileName,
			&i.LogoContentType,
			&i.LogoSizeBytes,
			&i.Latitude,
			&i.Longitude,
			&i.HouseNumber,
			&i.WhatsappOptedIn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuoteItemsForQuote = `-- name: ListQuoteItemsForQuote :many
SELECT qi.description,
	qi.quantity::text AS quantity,
	qi.id,
	qi.unit_price_cents,
	ROUND((qi.quantity_numeric * qi.unit_price_cents::numeric) * (1 + qi.tax_rate::numeric / 10000))::bigint AS line_total_cents
FROM RAC_quote_items qi
WHERE qi.quote_id = $1::uuid
  AND qi.organization_id = $2::uuid
  AND (qi.is_optional = FALSE OR qi.is_selected = TRUE)
ORDER BY qi.sort_order ASC
`

type ListQuoteItemsForQuoteParams struct {
	QuoteID        pgtype.UUID `json:"quote_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListQuoteItemsForQuoteRow struct {
	Description    string      `json:"description"`
	Quantity       string      `json:"quantity"`
	ID             pgtype.UUID `json:"id"`
	UnitPriceCents int64       `json:"unit_price_cents"`
	LineTotalCents int64       `json:"line_total_cents"`
}

func (q *Queries) ListQuoteItemsForQuote(ctx context.Context, arg ListQuoteItemsForQuoteParams) ([]ListQuoteItemsForQuoteRow, error) {
	rows, err := q.db.Query(ctx, listQuoteItemsForQuote, arg.QuoteID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuoteItemsForQuoteRow
	for rows.Next() {
		var i ListQuoteItemsForQuoteRow
		if err := rows.Scan(
			&i.Description,
			&i.Quantity,
			&i.ID,
			&i.UnitPriceCents,
			&i.LineTotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const partnerExists = `-- name: PartnerExists :one
SELECT EXISTS(
	SELECT 1
	FROM RAC_partners
	WHERE id = $1::uuid
	  AND organization_id = $2::uuid
)
`

type PartnerExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) PartnerExists(ctx context.Context, arg PartnerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, partnerExists, arg.ID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rejectPartnerOffer = `-- name: RejectPartnerOffer :execrows
UPDATE RAC_partner_offers
SET status = 'rejected',
	rejected_at = now(),
	rejection_reason = $1::text,
	updated_at = now()
WHERE id = $2::uuid
  AND status IN ('pending', 'sent')
`

type RejectPartnerOfferParams struct {
	RejectionReason pgtype.Text `json:"rejection_reason"`
	OfferID         pgtype.UUID `json:"offer_id"`
}

func (q *Queries) RejectPartnerOffer(ctx context.Context, arg RejectPartnerOfferParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectPartnerOffer, arg.RejectionReason, arg.OfferID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePartnerInvite = `-- name: RevokePartnerInvite :one
UPDATE RAC_partner_invites
SET expires_at = now()
WHERE id = $1::uuid
  AND organization_id = $2::uuid
  AND used_at IS NULL
RETURNING id, organization_id, partner_id, email, token_hash, expires_at, created_by, created_at, used_at, used_by, lead_id, lead_service_id
`

type RevokePartnerInviteParams struct {
	InviteID       pgtype.UUID `json:"invite_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) RevokePartnerInvite(ctx context.Context, arg RevokePartnerInviteParams) (RacPartnerInvite, error) {
	row := q.db.QueryRow(ctx, revokePartnerInvite, arg.InviteID, arg.OrganizationID)
	var i RacPartnerInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PartnerID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.LeadID,
		&i.LeadServiceID,
	)
	return i, err
}

const setPartnerOfferPDFFileKey = `-- name: SetPartnerOfferPDFFileKey :execrows
UPDATE RAC_partner_offers
SET pdf_file_key = $1::text,
	updated_at = now()
WHERE id = $2::uuid
`

type SetPartnerOfferPDFFileKeyParams struct {
	FileKey string      `json:"file_key"`
	OfferID pgtype.UUID `json:"offer_id"`
}

func (q *Queries) SetPartnerOfferPDFFileKey(ctx context.Context, arg SetPartnerOfferPDFFileKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPartnerOfferPDFFileKey, arg.FileKey, arg.OfferID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkPartnerLead = `-- name: UnlinkPartnerLead :execrows
DELETE FROM RAC_partner_leads
WHERE organization_id = $1::uuid
  AND partner_id = $2::uuid
  AND lead_id = $3::uuid
`

type UnlinkPartnerLeadParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	PartnerID      pgtype.UUID `json:"partner_id"`
	LeadID         pgtype.UUID `json:"lead_id"`
}

func (q *Queries) UnlinkPartnerLead(ctx context.Context, arg UnlinkPartnerLeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkPartnerLead, arg.OrganizationID, arg.PartnerID, arg.LeadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePartner = `-- name: UpdatePartner :one
UPDATE RAC_partners
SET business_name = COALESCE($1::text, business_name),
	kvk_number = CASE WHEN $2::text IS NULL THEN kvk_number ELSE NULLIF($2::text, '') END,
	vat_number = CASE WHEN $3::text IS NULL THEN vat_number ELSE NULLIF($3::text, '') END,
	address_line1 = COALESCE($4::text, address_line1),
	address_line2 = COALESCE($5::text, address_line2),
	house_number = COALESCE($6::text, house_number),
	postal_code = COALESCE($7::text, postal_code),
	city = COALESCE($8::text, city),
	country = COALESCE($9::text, country),
	latitude = COALESCE($10::float8, latitude),
	longitude = COALESCE($11::float8, longitude),
	contact_name = COALESCE($12::text, contact_name),
	contact_email = COALESCE($13::text, contact_email),
	contact_phone = COALESCE($14::text, contact_phone),
	whatsapp_opted_in = COALESCE($15::bool, whatsapp_opted_in),
	updated_at = now()
WHERE id = $16::uuid
  AND organization_id = $17::uuid
RETURNING id, organization_id, business_name, kvk_number, vat_number, address_line1, address_line2, postal_code, city, country, contact_name, contact_email, contact_phone, created_at, updated_at, logo_file_key, logo_file_name, logo_content_type, logo_size_bytes, latitude, longitude, house_number, whatsapp_opted_in
`

type UpdatePartnerParams struct {
	BusinessName    pgtype.Text   `json:"business_name"`
	KvkNumber       pgtype.Text   `json:"kvk_number"`
	VatNumber       pgtype.Text   `json:"vat_number"`
	AddressLine1    pgtype.Text   `json:"address_line1"`
	AddressLine2    pgtype.Text   `json:"address_line2"`
	HouseNumber     pgtype.Text   `json:"house_number"`
	PostalCode      pgtype.Text   `json:"postal_code"`
	City            pgtype.Text   `json:"city"`
	Country         pgtype.Text   `json:"country"`
	Latitude        pgtype.Float8 `json:"latitude"`
	Longitude       pgtype.Float8 `json:"longitude"`
	ContactName     pgtype.Text   `json:"contact_name"`
	ContactEmail    pgtype.Text   `json:"contact_email"`
	ContactPhone    pgtype.Text   `json:"contact_phone"`
	WhatsappOptedIn pgtype.Bool   `json:"whatsapp_opted_in"`
	ID              pgtype.UUID   `json:"id"`
	OrganizationID  pgtype.UUID   `json:"organization_id"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (RacPartner, error) {
	row := q.db.QueryRow(ctx, updatePartner,
		arg.BusinessName,
		arg.KvkNumber,
		arg.VatNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.HouseNumber,
		arg.PostalCode,
		arg.City,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.ContactName,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.WhatsappOptedIn,
		arg.ID,
		arg.OrganizationID,
	)
	var i RacPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessName,
		&i.KvkNumber,
		&i.VatNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.Latitude,
		&i.Longitude,
		&i.HouseNumber,
		&i.WhatsappOptedIn,
	)
	return i, err
}

const updatePartnerLogo = `-- name: UpdatePartnerLogo :one
UPDATE RAC_partners
SET logo_file_key = $1::text,
	logo_file_name = $2::text,
	logo_content_type = $3::text,
	logo_size_bytes = $4::bigint,
	updated_at = now()
WHERE id = $5::uuid
  AND organization_id = $6::uuid
RETURNING id, organization_id, business_name, kvk_number, vat_number, address_line1, address_line2, postal_code, city, country, contact_name, contact_email, contact_phone, created_at, updated_at, logo_file_key, logo_file_name, logo_content_type, logo_size_bytes, latitude, longitude, house_number, whatsapp_opted_in
`

type UpdatePartnerLogoParams struct {
	FileKey        string      `json:"file_key"`
	FileName       string      `json:"file_name"`
	ContentType    string      `json:"content_type"`
	SizeBytes      int64       `json:"size_bytes"`
	PartnerID      pgtype.UUID `json:"partner_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdatePartnerLogo(ctx context.Context, arg UpdatePartnerLogoParams) (RacPartner, error) {
	row := q.db.QueryRow(ctx, updatePartnerLogo,
		arg.FileKey,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.PartnerID,
		arg.OrganizationID,
	)
	var i RacPartner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.BusinessName,
		&i.KvkNumber,
		&i.VatNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ContactName,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoFileKey,
		&i.LogoFileName,
		&i.LogoContentType,
		&i.LogoSizeBytes,
		&i.Latitude,
		&i.Longitude,
		&i.HouseNumber,
		&i.WhatsappOptedIn,
	)
	return i, err
}

const updatePartnerOfferBuilderSummaryIfEmpty = `-- name: UpdatePartnerOfferBuilderSummaryIfEmpty :execrows
UPDATE RAC_partner_offers
SET builder_summary = $1::text,
	updated_at = now()
WHERE id = $2::uuid
	AND organization_id = $3::uuid
	AND builder_summary IS NULL
`

type UpdatePartnerOfferBuilderSummaryIfEmptyParams struct {
	Summary        string      `json:"summary"`
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdatePartnerOfferBuilderSummaryIfEmpty(ctx context.Context, arg UpdatePartnerOfferBuilderSummaryIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePartnerOfferBuilderSummaryIfEmpty, arg.Summary, arg.OfferID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePartnerOfferJobSummaryShortIfEmpty = `-- name: UpdatePartnerOfferJobSummaryShortIfEmpty :execrows
UPDATE RAC_partner_offers
SET job_summary_short = $1::text,
	updated_at = now()
WHERE id = $2::uuid
	AND organization_id = $3::uuid
	AND job_summary_short IS NULL
`

type UpdatePartnerOfferJobSummaryShortIfEmptyParams struct {
	Summary        string      `json:"summary"`
	OfferID        pgtype.UUID `json:"offer_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdatePartnerOfferJobSummaryShortIfEmpty(ctx context.Context, arg UpdatePartnerOfferJobSummaryShortIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePartnerOfferJobSummaryShortIfEmpty, arg.Summary, arg.OfferID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
