// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package leadsdb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PipelineStage string

const (
	PipelineStageTriage             PipelineStage = "Triage"
	PipelineStageNurturing          PipelineStage = "Nurturing"
	PipelineStageReadyForEstimator  PipelineStage = "Ready_For_Estimator"
	PipelineStageQuoteSent          PipelineStage = "Quote_Sent"
	PipelineStageReadyForPartner    PipelineStage = "Ready_For_Partner"
	PipelineStagePartnerMatching    PipelineStage = "Partner_Matching"
	PipelineStagePartnerAssigned    PipelineStage = "Partner_Assigned"
	PipelineStageManualIntervention PipelineStage = "Manual_Intervention"
	PipelineStageCompleted          PipelineStage = "Completed"
	PipelineStageLost               PipelineStage = "Lost"
)

func (e *PipelineStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PipelineStage(s)
	case string:
		*e = PipelineStage(s)
	default:
		return fmt.Errorf("unsupported scan type for PipelineStage: %T", src)
	}
	return nil
}

type NullPipelineStage struct {
	PipelineStage PipelineStage `json:"pipeline_stage"`
	Valid         bool          `json:"valid"` // Valid is true if PipelineStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPipelineStage) Scan(value interface{}) error {
	if value == nil {
		ns.PipelineStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PipelineStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPipelineStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PipelineStage), nil
}

type LeadTimelineEvent struct {
	ID             pgtype.UUID        `json:"id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	ServiceID      pgtype.UUID        `json:"service_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	ActorType      string             `json:"actor_type"`
	ActorName      string             `json:"actor_name"`
	EventType      string             `json:"event_type"`
	Title          string             `json:"title"`
	Summary        pgtype.Text        `json:"summary"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RacLead struct {
	ID                    pgtype.UUID        `json:"id"`
	ConsumerFirstName     string             `json:"consumer_first_name"`
	ConsumerLastName      string             `json:"consumer_last_name"`
	ConsumerPhone         string             `json:"consumer_phone"`
	ConsumerEmail         pgtype.Text        `json:"consumer_email"`
	ConsumerRole          string             `json:"consumer_role"`
	AddressStreet         string             `json:"address_street"`
	AddressHouseNumber    string             `json:"address_house_number"`
	AddressZipCode        string             `json:"address_zip_code"`
	AddressCity           string             `json:"address_city"`
	ServiceType           string             `json:"service_type"`
	Status                string             `json:"status"`
	AssignedAgentID       pgtype.UUID        `json:"assigned_agent_id"`
	ViewedByID            pgtype.UUID        `json:"viewed_by_id"`
	ViewedAt              pgtype.Timestamptz `json:"viewed_at"`
	VisitScheduledDate    pgtype.Timestamptz `json:"visit_scheduled_date"`
	VisitScoutID          pgtype.UUID        `json:"visit_scout_id"`
	VisitMeasurements     pgtype.Text        `json:"visit_measurements"`
	VisitAccessDifficulty pgtype.Text        `json:"visit_access_difficulty"`
	VisitNotes            pgtype.Text        `json:"visit_notes"`
	VisitCompletedAt      pgtype.Timestamptz `json:"visit_completed_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ConsumerNote          pgtype.Text        `json:"consumer_note"`
	Source                pgtype.Text        `json:"source"`
}

type RacLeadActivity struct {
	ID        pgtype.UUID        `json:"id"`
	LeadID    pgtype.UUID        `json:"lead_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Meta      []byte             `json:"meta"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RacLeadAiAnalysis struct {
	ID                  pgtype.UUID        `json:"id"`
	LeadID              pgtype.UUID        `json:"lead_id"`
	UrgencyLevel        string             `json:"urgency_level"`
	UrgencyReason       pgtype.Text        `json:"urgency_reason"`
	TalkingPoints       []byte             `json:"talking_points"`
	ObjectionHandling   []byte             `json:"objection_handling"`
	UpsellOpportunities []byte             `json:"upsell_opportunities"`
	Summary             string             `json:"summary"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type RacLeadNote struct {
	ID        pgtype.UUID        `json:"id"`
	LeadID    pgtype.UUID        `json:"lead_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RacLeadService struct {
	ID                    pgtype.UUID        `json:"id"`
	LeadID                pgtype.UUID        `json:"lead_id"`
	ServiceType           string             `json:"service_type"`
	Status                string             `json:"status"`
	VisitScheduledDate    pgtype.Timestamptz `json:"visit_scheduled_date"`
	VisitScoutID          pgtype.UUID        `json:"visit_scout_id"`
	VisitMeasurements     pgtype.Text        `json:"visit_measurements"`
	VisitAccessDifficulty pgtype.Text        `json:"visit_access_difficulty"`
	VisitNotes            pgtype.Text        `json:"visit_notes"`
	VisitCompletedAt      pgtype.Timestamptz `json:"visit_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ServiceTypeID         pgtype.UUID        `json:"service_type_id"`
	PipelineStage         PipelineStage      `json:"pipeline_stage"`
}

type RacServiceType struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	Icon         pgtype.Text        `json:"icon"`
	Color        pgtype.Text        `json:"color"`
	IsActive     bool               `json:"is_active"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type VisitHistory struct {
	ID               pgtype.UUID        `json:"id"`
	LeadID           pgtype.UUID        `json:"lead_id"`
	ScheduledDate    pgtype.Timestamptz `json:"scheduled_date"`
	ScoutID          pgtype.UUID        `json:"scout_id"`
	Outcome          string             `json:"outcome"`
	Measurements     pgtype.Text        `json:"measurements"`
	AccessDifficulty pgtype.Text        `json:"access_difficulty"`
	Notes            pgtype.Text        `json:"notes"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
