// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package leadsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkSoftDeleteLeads(ctx context.Context, dollar_1 []pgtype.UUID) (pgconn.CommandTag, error)
	CompleteLeadServiceSurvey(ctx context.Context, arg CompleteLeadServiceSurveyParams) (LeadService, error)
	CompleteLeadSurvey(ctx context.Context, arg CompleteLeadSurveyParams) (Lead, error)
	CountLeads(ctx context.Context) (int64, error)
	// Leads Domain SQL Queries
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	// Lead Activity Queries
	CreateLeadActivity(ctx context.Context, arg CreateLeadActivityParams) error
	// Lead Notes Queries
	CreateLeadNote(ctx context.Context, arg CreateLeadNoteParams) (LeadNote, error)
	// Lead Services Queries
	CreateLeadService(ctx context.Context, arg CreateLeadServiceParams) (LeadService, error)
	// Visit History Queries
	CreateVisitHistory(ctx context.Context, arg CreateVisitHistoryParams) (VisitHistory, error)
	DeleteLeadNote(ctx context.Context, id pgtype.UUID) error
	GetLeadByID(ctx context.Context, id pgtype.UUID) (Lead, error)
	GetLeadByPhone(ctx context.Context, consumerPhone string) (Lead, error)
	GetLeadNote(ctx context.Context, id pgtype.UUID) (LeadNote, error)
	GetLeadService(ctx context.Context, id pgtype.UUID) (LeadService, error)
	ListLeadActivities(ctx context.Context, leadID pgtype.UUID) ([]LeadActivity, error)
	ListLeadNotes(ctx context.Context, leadID pgtype.UUID) ([]LeadNote, error)
	ListLeadServices(ctx context.Context, leadID pgtype.UUID) ([]LeadService, error)
	ListVisitHistory(ctx context.Context, leadID pgtype.UUID) ([]VisitHistory, error)
	ScheduleLeadServiceVisit(ctx context.Context, arg ScheduleLeadServiceVisitParams) (LeadService, error)
	ScheduleLeadVisit(ctx context.Context, arg ScheduleLeadVisitParams) (Lead, error)
	SetLeadViewedBy(ctx context.Context, arg SetLeadViewedByParams) error
	SoftDeleteLead(ctx context.Context, id pgtype.UUID) error
	UpdateLeadNote(ctx context.Context, arg UpdateLeadNoteParams) (LeadNote, error)
	UpdateLeadServiceStatus(ctx context.Context, arg UpdateLeadServiceStatusParams) (LeadService, error)
	UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error)
}

var _ Querier = (*Queries)(nil)
