// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package leadsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkSoftDeleteLeads(ctx context.Context, dollar_1 []pgtype.UUID) (pgconn.CommandTag, error)
	CountLeads(ctx context.Context) (int64, error)
	// Leads Domain SQL Queries
	CreateLead(ctx context.Context, arg CreateLeadParams) (RacLead, error)
	// Lead AI Analysis Queries
	CreateLeadAIAnalysis(ctx context.Context, arg CreateLeadAIAnalysisParams) (RacLeadAiAnalysis, error)
	// Lead Activity Queries
	CreateLeadActivity(ctx context.Context, arg CreateLeadActivityParams) error
	// Lead Notes Queries
	CreateLeadNote(ctx context.Context, arg CreateLeadNoteParams) (RacLeadNote, error)
	// Lead Services Queries
	CreateLeadService(ctx context.Context, arg CreateLeadServiceParams) (CreateLeadServiceRow, error)
	DeleteLeadNote(ctx context.Context, id pgtype.UUID) error
	GetLatestLeadAIAnalysis(ctx context.Context, leadID pgtype.UUID) (RacLeadAiAnalysis, error)
	GetLeadByID(ctx context.Context, id pgtype.UUID) (RacLead, error)
	GetLeadByPhone(ctx context.Context, consumerPhone string) (RacLead, error)
	GetLeadNote(ctx context.Context, id pgtype.UUID) (RacLeadNote, error)
	GetLeadService(ctx context.Context, id pgtype.UUID) (RacLeadService, error)
	ListLeadAIAnalysis(ctx context.Context, leadID pgtype.UUID) ([]RacLeadAiAnalysis, error)
	ListLeadActivities(ctx context.Context, leadID pgtype.UUID) ([]RacLeadActivity, error)
	ListLeadNotes(ctx context.Context, leadID pgtype.UUID) ([]RacLeadNote, error)
	ListLeadServices(ctx context.Context, leadID pgtype.UUID) ([]RacLeadService, error)
	SetLeadViewedBy(ctx context.Context, arg SetLeadViewedByParams) error
	SoftDeleteLead(ctx context.Context, id pgtype.UUID) error
	UpdateLeadNote(ctx context.Context, arg UpdateLeadNoteParams) (RacLeadNote, error)
	UpdateLeadServiceStatus(ctx context.Context, arg UpdateLeadServiceStatusParams) (RacLeadService, error)
	UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (RacLead, error)
}

var _ Querier = (*Queries)(nil)
