// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package leadsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLeadByID = `-- name: GetLeadByID :one

SELECT id, consumer_first_name, consumer_last_name, consumer_phone, consumer_email, consumer_role, address_street, address_house_number, address_zip_code, address_city, assigned_agent_id, viewed_by_id, viewed_at, created_at, updated_at, deleted_at, source, projected_value_cents, latitude, longitude, organization_id, energy_class, energy_index, energy_bouwjaar, energy_gebouwtype, energy_label_valid_until, energy_label_registered_at, energy_primair_fossiel, energy_bag_verblijfsobject_id, energy_label_fetched_at, lead_enrichment_source, lead_enrichment_postcode6, lead_enrichment_buurtcode, lead_enrichment_gem_aardgasverbruik, lead_enrichment_huishouden_grootte, lead_enrichment_koopwoningen_pct, lead_enrichment_bouwjaar_vanaf2000_pct, lead_enrichment_mediaan_vermogen_x1000, lead_enrichment_huishoudens_met_kinderen_pct, lead_enrichment_confidence, lead_enrichment_fetched_at, lead_score, lead_score_pre_ai, lead_score_factors, lead_score_version, lead_score_updated_at, lead_enrichment_postcode4, lead_enrichment_data_year, lead_enrichment_gem_elektriciteitsverbruik, lead_enrichment_woz_waarde, lead_enrichment_gem_inkomen, lead_enrichment_pct_hoog_inkomen, lead_enrichment_pct_laag_inkomen, lead_enrichment_stedelijkheid, public_token, public_token_expires_at, raw_form_data, webhook_source_domain, is_incomplete, gclid, utm_source, utm_medium, utm_campaign, utm_content, utm_term, ad_landing_page, referrer_url, whatsapp_opted_in, google_campaign_id, google_adgroup_id, google_creative_id, google_form_id FROM rac_leads WHERE id = $1 AND organization_id = $2
`

type GetLeadByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Leads Domain SQL Queries
// Add sqlc-annotated queries here as you migrate raw SQL from repository files.
func (q *Queries) GetLeadByID(ctx context.Context, arg GetLeadByIDParams) (RacLead, error) {
	row := q.db.QueryRow(ctx, getLeadByID, arg.ID, arg.OrganizationID)
	var i RacLead
	err := row.Scan(
		&i.ID,
		&i.ConsumerFirstName,
		&i.ConsumerLastName,
		&i.ConsumerPhone,
		&i.ConsumerEmail,
		&i.ConsumerRole,
		&i.AddressStreet,
		&i.AddressHouseNumber,
		&i.AddressZipCode,
		&i.AddressCity,
		&i.AssignedAgentID,
		&i.ViewedByID,
		&i.ViewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.ProjectedValueCents,
		&i.Latitude,
		&i.Longitude,
		&i.OrganizationID,
		&i.EnergyClass,
		&i.EnergyIndex,
		&i.EnergyBouwjaar,
		&i.EnergyGebouwtype,
		&i.EnergyLabelValidUntil,
		&i.EnergyLabelRegisteredAt,
		&i.EnergyPrimairFossiel,
		&i.EnergyBagVerblijfsobjectID,
		&i.EnergyLabelFetchedAt,
		&i.LeadEnrichmentSource,
		&i.LeadEnrichmentPostcode6,
		&i.LeadEnrichmentBuurtcode,
		&i.LeadEnrichmentGemAardgasverbruik,
		&i.LeadEnrichmentHuishoudenGrootte,
		&i.LeadEnrichmentKoopwoningenPct,
		&i.LeadEnrichmentBouwjaarVanaf2000Pct,
		&i.LeadEnrichmentMediaanVermogenX1000,
		&i.LeadEnrichmentHuishoudensMetKinderenPct,
		&i.LeadEnrichmentConfidence,
		&i.LeadEnrichmentFetchedAt,
		&i.LeadScore,
		&i.LeadScorePreAi,
		&i.LeadScoreFactors,
		&i.LeadScoreVersion,
		&i.LeadScoreUpdatedAt,
		&i.LeadEnrichmentPostcode4,
		&i.LeadEnrichmentDataYear,
		&i.LeadEnrichmentGemElektriciteitsverbruik,
		&i.LeadEnrichmentWozWaarde,
		&i.LeadEnrichmentGemInkomen,
		&i.LeadEnrichmentPctHoogInkomen,
		&i.LeadEnrichmentPctLaagInkomen,
		&i.LeadEnrichmentStedelijkheid,
		&i.PublicToken,
		&i.PublicTokenExpiresAt,
		&i.RawFormData,
		&i.WebhookSourceDomain,
		&i.IsIncomplete,
		&i.Gclid,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmContent,
		&i.UtmTerm,
		&i.AdLandingPage,
		&i.ReferrerUrl,
		&i.WhatsappOptedIn,
		&i.GoogleCampaignID,
		&i.GoogleAdgroupID,
		&i.GoogleCreativeID,
		&i.GoogleFormID,
	)
	return i, err
}
