// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package appointmentsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAppointments = `-- name: CountAppointments :one
SELECT COUNT(*)::int AS countValue
FROM RAC_appointments
WHERE organization_id = $1
	AND ($2::uuid IS NULL OR user_id = $2::uuid)
	AND ($3::uuid IS NULL OR lead_id = $3::uuid)
	AND ($4::text IS NULL OR type = $4::text)
	AND ($5::text IS NULL OR status = $5::text)
	AND ($6::timestamptz IS NULL OR start_time >= $6::timestamptz)
	AND ($7::timestamptz IS NULL OR start_time <= $7::timestamptz)
	AND ($8::text IS NULL OR title ILIKE $8::text OR location ILIKE $8::text OR meeting_link ILIKE $8::text)
`

type CountAppointmentsParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	Type           pgtype.Text        `json:"type"`
	Status         pgtype.Text        `json:"status"`
	StartFrom      pgtype.Timestamptz `json:"start_from"`
	StartTo        pgtype.Timestamptz `json:"start_to"`
	Search         pgtype.Text        `json:"search"`
}

func (q *Queries) CountAppointments(ctx context.Context, arg CountAppointmentsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAppointments,
		arg.OrganizationID,
		arg.UserID,
		arg.LeadID,
		arg.Type,
		arg.Status,
		arg.StartFrom,
		arg.StartTo,
		arg.Search,
	)
	var countvalue int32
	err := row.Scan(&countvalue)
	return countvalue, err
}

const createAppointment = `-- name: CreateAppointment :exec

INSERT INTO RAC_appointments (
	id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
)
VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8,
	$9, $10, $11, $12, $13, $14, $15, $16
)
`

type CreateAppointmentParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Appointments Domain SQL Queries
func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) error {
	_, err := q.db.Exec(ctx, createAppointment,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.LeadID,
		arg.LeadServiceID,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.MeetingLink,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.AllDay,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createAppointmentAttachment = `-- name: CreateAppointmentAttachment :one
INSERT INTO RAC_appointment_attachments
	(id, appointment_id, organization_id, file_key, file_name, content_type, size_bytes)
VALUES
	($1, $2, $3, $4, $5, $6, $7)
RETURNING id, appointment_id, organization_id, file_key, file_name, content_type, size_bytes, created_at
`

type CreateAppointmentAttachmentParams struct {
	ID             pgtype.UUID `json:"id"`
	AppointmentID  pgtype.UUID `json:"appointment_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	FileKey        string      `json:"file_key"`
	FileName       string      `json:"file_name"`
	ContentType    pgtype.Text `json:"content_type"`
	SizeBytes      pgtype.Int8 `json:"size_bytes"`
}

type CreateAppointmentAttachmentRow struct {
	ID             pgtype.UUID        `json:"id"`
	AppointmentID  pgtype.UUID        `json:"appointment_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	FileKey        string             `json:"file_key"`
	FileName       string             `json:"file_name"`
	ContentType    pgtype.Text        `json:"content_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAppointmentAttachment(ctx context.Context, arg CreateAppointmentAttachmentParams) (CreateAppointmentAttachmentRow, error) {
	row := q.db.QueryRow(ctx, createAppointmentAttachment,
		arg.ID,
		arg.AppointmentID,
		arg.OrganizationID,
		arg.FileKey,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i CreateAppointmentAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.OrganizationID,
		&i.FileKey,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createAvailabilityOverride = `-- name: CreateAvailabilityOverride :one
INSERT INTO RAC_appointment_availability_overrides
	(id, organization_id, user_id, date, is_available, start_time, end_time, timezone)
VALUES
	($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, user_id, date, is_available, start_time, end_time, timezone, created_at, updated_at
`

type CreateAvailabilityOverrideParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Date           pgtype.Date `json:"date"`
	IsAvailable    bool        `json:"is_available"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	Timezone       string      `json:"timezone"`
}

type CreateAvailabilityOverrideRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Date           pgtype.Date        `json:"date"`
	IsAvailable    bool               `json:"is_available"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAvailabilityOverride(ctx context.Context, arg CreateAvailabilityOverrideParams) (CreateAvailabilityOverrideRow, error) {
	row := q.db.QueryRow(ctx, createAvailabilityOverride,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Date,
		arg.IsAvailable,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i CreateAvailabilityOverrideRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Date,
		&i.IsAvailable,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAvailabilityRule = `-- name: CreateAvailabilityRule :one
INSERT INTO RAC_appointment_availability_rules
	(id, organization_id, user_id, weekday, start_time, end_time, timezone)
VALUES
	($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, user_id, weekday, start_time, end_time, timezone, created_at, updated_at
`

type CreateAvailabilityRuleParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Weekday        int16       `json:"weekday"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	Timezone       string      `json:"timezone"`
}

type CreateAvailabilityRuleRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Weekday        int16              `json:"weekday"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAvailabilityRule(ctx context.Context, arg CreateAvailabilityRuleParams) (CreateAvailabilityRuleRow, error) {
	row := q.db.QueryRow(ctx, createAvailabilityRule,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i CreateAvailabilityRuleRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :execrows
DELETE FROM RAC_appointments
WHERE id = $1 AND organization_id = $2
`

type DeleteAppointmentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteAppointment(ctx context.Context, arg DeleteAppointmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppointment, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAvailabilityOverride = `-- name: DeleteAvailabilityOverride :execrows
DELETE FROM RAC_appointment_availability_overrides
WHERE id = $1 AND organization_id = $2
`

type DeleteAvailabilityOverrideParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteAvailabilityOverride(ctx context.Context, arg DeleteAvailabilityOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailabilityOverride, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAvailabilityRule = `-- name: DeleteAvailabilityRule :execrows
DELETE FROM RAC_appointment_availability_rules
WHERE id = $1 AND organization_id = $2
`

type DeleteAvailabilityRuleParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteAvailabilityRule(ctx context.Context, arg DeleteAvailabilityRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAvailabilityRule, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE id = $1 AND organization_id = $2
`

type GetAppointmentByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAppointmentByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAppointmentByID(ctx context.Context, arg GetAppointmentByIDParams) (GetAppointmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, arg.ID, arg.OrganizationID)
	var i GetAppointmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.LeadID,
		&i.LeadServiceID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.MeetingLink,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.AllDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentByLeadServiceID = `-- name: GetAppointmentByLeadServiceID :one
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE lead_service_id = $1 AND organization_id = $2 AND status != 'cancelled'
ORDER BY created_at DESC
LIMIT 1
`

type GetAppointmentByLeadServiceIDParams struct {
	LeadServiceID  pgtype.UUID `json:"lead_service_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAppointmentByLeadServiceIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAppointmentByLeadServiceID(ctx context.Context, arg GetAppointmentByLeadServiceIDParams) (GetAppointmentByLeadServiceIDRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentByLeadServiceID, arg.LeadServiceID, arg.OrganizationID)
	var i GetAppointmentByLeadServiceIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.LeadID,
		&i.LeadServiceID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.MeetingLink,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.AllDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentLeadEmail = `-- name: GetAppointmentLeadEmail :one
SELECT COALESCE(consumer_email, '') AS consumerEmailValue
FROM RAC_leads
WHERE id = $1 AND organization_id = $2
`

type GetAppointmentLeadEmailParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetAppointmentLeadEmail(ctx context.Context, arg GetAppointmentLeadEmailParams) (string, error) {
	row := q.db.QueryRow(ctx, getAppointmentLeadEmail, arg.ID, arg.OrganizationID)
	var consumeremailvalue string
	err := row.Scan(&consumeremailvalue)
	return consumeremailvalue, err
}

const getAppointmentLeadInfo = `-- name: GetAppointmentLeadInfo :one
SELECT id, consumer_first_name, consumer_last_name, consumer_phone, address_street, address_house_number, address_city
FROM RAC_leads
WHERE id = $1 AND organization_id = $2
`

type GetAppointmentLeadInfoParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAppointmentLeadInfoRow struct {
	ID                 pgtype.UUID `json:"id"`
	ConsumerFirstName  string      `json:"consumer_first_name"`
	ConsumerLastName   string      `json:"consumer_last_name"`
	ConsumerPhone      string      `json:"consumer_phone"`
	AddressStreet      string      `json:"address_street"`
	AddressHouseNumber string      `json:"address_house_number"`
	AddressCity        string      `json:"address_city"`
}

func (q *Queries) GetAppointmentLeadInfo(ctx context.Context, arg GetAppointmentLeadInfoParams) (GetAppointmentLeadInfoRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentLeadInfo, arg.ID, arg.OrganizationID)
	var i GetAppointmentLeadInfoRow
	err := row.Scan(
		&i.ID,
		&i.ConsumerFirstName,
		&i.ConsumerLastName,
		&i.ConsumerPhone,
		&i.AddressStreet,
		&i.AddressHouseNumber,
		&i.AddressCity,
	)
	return i, err
}

const getAppointmentVisitReport = `-- name: GetAppointmentVisitReport :one
SELECT appointment_id, organization_id, measurements, measurement_products, access_difficulty, notes, created_at, updated_at
FROM RAC_appointment_visit_reports
WHERE appointment_id = $1 AND organization_id = $2
`

type GetAppointmentVisitReportParams struct {
	AppointmentID  pgtype.UUID `json:"appointment_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAppointmentVisitReportRow struct {
	AppointmentID       pgtype.UUID        `json:"appointment_id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	Measurements        pgtype.Text        `json:"measurements"`
	MeasurementProducts []byte             `json:"measurement_products"`
	AccessDifficulty    pgtype.Text        `json:"access_difficulty"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAppointmentVisitReport(ctx context.Context, arg GetAppointmentVisitReportParams) (GetAppointmentVisitReportRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentVisitReport, arg.AppointmentID, arg.OrganizationID)
	var i GetAppointmentVisitReportRow
	err := row.Scan(
		&i.AppointmentID,
		&i.OrganizationID,
		&i.Measurements,
		&i.MeasurementProducts,
		&i.AccessDifficulty,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailabilityOverrideByID = `-- name: GetAvailabilityOverrideByID :one
SELECT id, organization_id, user_id, date, is_available, start_time, end_time, timezone, created_at, updated_at
FROM RAC_appointment_availability_overrides
WHERE id = $1 AND organization_id = $2
`

type GetAvailabilityOverrideByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAvailabilityOverrideByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Date           pgtype.Date        `json:"date"`
	IsAvailable    bool               `json:"is_available"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAvailabilityOverrideByID(ctx context.Context, arg GetAvailabilityOverrideByIDParams) (GetAvailabilityOverrideByIDRow, error) {
	row := q.db.QueryRow(ctx, getAvailabilityOverrideByID, arg.ID, arg.OrganizationID)
	var i GetAvailabilityOverrideByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Date,
		&i.IsAvailable,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailabilityRuleByID = `-- name: GetAvailabilityRuleByID :one
SELECT id, organization_id, user_id, weekday, start_time, end_time, timezone, created_at, updated_at
FROM RAC_appointment_availability_rules
WHERE id = $1 AND organization_id = $2
`

type GetAvailabilityRuleByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetAvailabilityRuleByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Weekday        int16              `json:"weekday"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAvailabilityRuleByID(ctx context.Context, arg GetAvailabilityRuleByIDParams) (GetAvailabilityRuleByIDRow, error) {
	row := q.db.QueryRow(ctx, getAvailabilityRuleByID, arg.ID, arg.OrganizationID)
	var i GetAvailabilityRuleByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestScheduledVisitByLead = `-- name: GetLatestScheduledVisitByLead :one
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE lead_id = $1
	AND organization_id = $2
	AND type = 'lead_visit'
	AND status = 'scheduled'
ORDER BY start_time DESC
LIMIT 1
`

type GetLatestScheduledVisitByLeadParams struct {
	LeadID         pgtype.UUID `json:"lead_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetLatestScheduledVisitByLeadRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLatestScheduledVisitByLead(ctx context.Context, arg GetLatestScheduledVisitByLeadParams) (GetLatestScheduledVisitByLeadRow, error) {
	row := q.db.QueryRow(ctx, getLatestScheduledVisitByLead, arg.LeadID, arg.OrganizationID)
	var i GetLatestScheduledVisitByLeadRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.LeadID,
		&i.LeadServiceID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.MeetingLink,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.AllDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextRequestedVisitByLead = `-- name: GetNextRequestedVisitByLead :one
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE lead_id = $1
	AND organization_id = $2
	AND type = 'lead_visit'
	AND status = 'requested'
ORDER BY start_time ASC
LIMIT 1
`

type GetNextRequestedVisitByLeadParams struct {
	LeadID         pgtype.UUID `json:"lead_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetNextRequestedVisitByLeadRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNextRequestedVisitByLead(ctx context.Context, arg GetNextRequestedVisitByLeadParams) (GetNextRequestedVisitByLeadRow, error) {
	row := q.db.QueryRow(ctx, getNextRequestedVisitByLead, arg.LeadID, arg.OrganizationID)
	var i GetNextRequestedVisitByLeadRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.LeadID,
		&i.LeadServiceID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.MeetingLink,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.AllDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextUpcomingScheduledVisitByLead = `-- name: GetNextUpcomingScheduledVisitByLead :one
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE lead_id = $1
	AND organization_id = $2
	AND type = 'lead_visit'
	AND status = 'scheduled'
	AND start_time > now()
ORDER BY start_time ASC
LIMIT 1
`

type GetNextUpcomingScheduledVisitByLeadParams struct {
	LeadID         pgtype.UUID `json:"lead_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetNextUpcomingScheduledVisitByLeadRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNextUpcomingScheduledVisitByLead(ctx context.Context, arg GetNextUpcomingScheduledVisitByLeadParams) (GetNextUpcomingScheduledVisitByLeadRow, error) {
	row := q.db.QueryRow(ctx, getNextUpcomingScheduledVisitByLead, arg.LeadID, arg.OrganizationID)
	var i GetNextUpcomingScheduledVisitByLeadRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.LeadID,
		&i.LeadServiceID,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.MeetingLink,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.AllDay,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointmentAttachments = `-- name: ListAppointmentAttachments :many
SELECT id, appointment_id, organization_id, file_key, file_name, content_type, size_bytes, created_at
FROM RAC_appointment_attachments
WHERE appointment_id = $1 AND organization_id = $2
ORDER BY created_at ASC
`

type ListAppointmentAttachmentsParams struct {
	AppointmentID  pgtype.UUID `json:"appointment_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListAppointmentAttachmentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	AppointmentID  pgtype.UUID        `json:"appointment_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	FileKey        string             `json:"file_key"`
	FileName       string             `json:"file_name"`
	ContentType    pgtype.Text        `json:"content_type"`
	SizeBytes      pgtype.Int8        `json:"size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAppointmentAttachments(ctx context.Context, arg ListAppointmentAttachmentsParams) ([]ListAppointmentAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentAttachments, arg.AppointmentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentAttachmentsRow
	for rows.Next() {
		var i ListAppointmentAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.OrganizationID,
			&i.FileKey,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentLeadInfoByIDs = `-- name: ListAppointmentLeadInfoByIDs :many
SELECT id, consumer_first_name, consumer_last_name, consumer_phone, address_street, address_house_number, address_city
FROM RAC_leads
WHERE id = ANY($1::uuid[]) AND organization_id = $2
`

type ListAppointmentLeadInfoByIDsParams struct {
	Column1        []pgtype.UUID `json:"column_1"`
	OrganizationID pgtype.UUID   `json:"organization_id"`
}

type ListAppointmentLeadInfoByIDsRow struct {
	ID                 pgtype.UUID `json:"id"`
	ConsumerFirstName  string      `json:"consumer_first_name"`
	ConsumerLastName   string      `json:"consumer_last_name"`
	ConsumerPhone      string      `json:"consumer_phone"`
	AddressStreet      string      `json:"address_street"`
	AddressHouseNumber string      `json:"address_house_number"`
	AddressCity        string      `json:"address_city"`
}

func (q *Queries) ListAppointmentLeadInfoByIDs(ctx context.Context, arg ListAppointmentLeadInfoByIDsParams) ([]ListAppointmentLeadInfoByIDsRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentLeadInfoByIDs, arg.Column1, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentLeadInfoByIDsRow
	for rows.Next() {
		var i ListAppointmentLeadInfoByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConsumerFirstName,
			&i.ConsumerLastName,
			&i.ConsumerPhone,
			&i.AddressStreet,
			&i.AddressHouseNumber,
			&i.AddressCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE organization_id = $1
	AND ($2::uuid IS NULL OR user_id = $2::uuid)
	AND ($3::uuid IS NULL OR lead_id = $3::uuid)
	AND ($4::text IS NULL OR type = $4::text)
	AND ($5::text IS NULL OR status = $5::text)
	AND ($6::timestamptz IS NULL OR start_time >= $6::timestamptz)
	AND ($7::timestamptz IS NULL OR start_time <= $7::timestamptz)
	AND ($8::text IS NULL OR title ILIKE $8::text OR location ILIKE $8::text OR meeting_link ILIKE $8::text)
ORDER BY
	CASE WHEN $9::text = 'title' AND $10::text = 'asc' THEN title END ASC,
	CASE WHEN $9::text = 'title' AND $10::text = 'desc' THEN title END DESC,
	CASE WHEN $9::text = 'type' AND $10::text = 'asc' THEN type END ASC,
	CASE WHEN $9::text = 'type' AND $10::text = 'desc' THEN type END DESC,
	CASE WHEN $9::text = 'status' AND $10::text = 'asc' THEN status END ASC,
	CASE WHEN $9::text = 'status' AND $10::text = 'desc' THEN status END DESC,
	CASE WHEN $9::text = 'startTime' AND $10::text = 'asc' THEN start_time END ASC,
	CASE WHEN $9::text = 'startTime' AND $10::text = 'desc' THEN start_time END DESC,
	CASE WHEN $9::text = 'endTime' AND $10::text = 'asc' THEN end_time END ASC,
	CASE WHEN $9::text = 'endTime' AND $10::text = 'desc' THEN end_time END DESC,
	CASE WHEN $9::text = 'createdAt' AND $10::text = 'asc' THEN created_at END ASC,
	CASE WHEN $9::text = 'createdAt' AND $10::text = 'desc' THEN created_at END DESC,
	start_time ASC
LIMIT $12 OFFSET $11
`

type ListAppointmentsParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	Type           pgtype.Text        `json:"type"`
	Status         pgtype.Text        `json:"status"`
	StartFrom      pgtype.Timestamptz `json:"start_from"`
	StartTo        pgtype.Timestamptz `json:"start_to"`
	Search         pgtype.Text        `json:"search"`
	SortBy         string             `json:"sort_by"`
	SortOrder      string             `json:"sort_order"`
	OffsetCount    int32              `json:"offset_count"`
	LimitCount     int32              `json:"limit_count"`
}

type ListAppointmentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointments,
		arg.OrganizationID,
		arg.UserID,
		arg.LeadID,
		arg.Type,
		arg.Status,
		arg.StartFrom,
		arg.StartTo,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsRow
	for rows.Next() {
		var i ListAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.LeadID,
			&i.LeadServiceID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.MeetingLink,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AllDay,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsForDateRange = `-- name: ListAppointmentsForDateRange :many
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE organization_id = $1 AND user_id = $2
	AND start_time < $4 AND end_time > $3
	AND status = 'scheduled'
ORDER BY start_time ASC
`

type ListAppointmentsForDateRangeParams struct {
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
}

type ListAppointmentsForDateRangeRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAppointmentsForDateRange(ctx context.Context, arg ListAppointmentsForDateRangeParams) ([]ListAppointmentsForDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsForDateRange,
		arg.OrganizationID,
		arg.UserID,
		arg.EndTime,
		arg.StartTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsForDateRangeRow
	for rows.Next() {
		var i ListAppointmentsForDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.LeadID,
			&i.LeadServiceID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.MeetingLink,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AllDay,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityOverrides = `-- name: ListAvailabilityOverrides :many
SELECT id, organization_id, user_id, date, is_available, start_time, end_time, timezone, created_at, updated_at
FROM RAC_appointment_availability_overrides
WHERE organization_id = $1 AND user_id = $2
	AND ($3::date IS NULL OR date >= $3)
	AND ($4::date IS NULL OR date <= $4)
ORDER BY date ASC
`

type ListAvailabilityOverridesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Column3        pgtype.Date `json:"column_3"`
	Column4        pgtype.Date `json:"column_4"`
}

type ListAvailabilityOverridesRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Date           pgtype.Date        `json:"date"`
	IsAvailable    bool               `json:"is_available"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAvailabilityOverrides(ctx context.Context, arg ListAvailabilityOverridesParams) ([]ListAvailabilityOverridesRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityOverrides,
		arg.OrganizationID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailabilityOverridesRow
	for rows.Next() {
		var i ListAvailabilityOverridesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Date,
			&i.IsAvailable,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityRuleUserIDs = `-- name: ListAvailabilityRuleUserIDs :many
SELECT DISTINCT user_id AS userIDValue
FROM RAC_appointment_availability_rules
WHERE organization_id = $1
`

func (q *Queries) ListAvailabilityRuleUserIDs(ctx context.Context, organizationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAvailabilityRuleUserIDs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var useridvalue pgtype.UUID
		if err := rows.Scan(&useridvalue); err != nil {
			return nil, err
		}
		items = append(items, useridvalue)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityRules = `-- name: ListAvailabilityRules :many
SELECT id, organization_id, user_id, weekday, start_time, end_time, timezone, created_at, updated_at
FROM RAC_appointment_availability_rules
WHERE organization_id = $1 AND user_id = $2
ORDER BY weekday, start_time
`

type ListAvailabilityRulesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type ListAvailabilityRulesRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Weekday        int16              `json:"weekday"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAvailabilityRules(ctx context.Context, arg ListAvailabilityRulesParams) ([]ListAvailabilityRulesRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityRules, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailabilityRulesRow
	for rows.Next() {
		var i ListAvailabilityRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadVisitsByStatus = `-- name: ListLeadVisitsByStatus :many
SELECT id, organization_id, user_id, lead_id, lead_service_id, type, title, description,
	location, meeting_link, start_time, end_time, status, all_day, created_at, updated_at
FROM RAC_appointments
WHERE lead_id = $1
	AND organization_id = $2
	AND type = 'lead_visit'
	AND status = ANY($3::text[])
ORDER BY start_time ASC
`

type ListLeadVisitsByStatusParams struct {
	LeadID         pgtype.UUID `json:"lead_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Column3        []string    `json:"column_3"`
}

type ListLeadVisitsByStatusRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	LeadServiceID  pgtype.UUID        `json:"lead_service_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Status         string             `json:"status"`
	AllDay         bool               `json:"all_day"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLeadVisitsByStatus(ctx context.Context, arg ListLeadVisitsByStatusParams) ([]ListLeadVisitsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listLeadVisitsByStatus, arg.LeadID, arg.OrganizationID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeadVisitsByStatusRow
	for rows.Next() {
		var i ListLeadVisitsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.LeadID,
			&i.LeadServiceID,
			&i.Type,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.MeetingLink,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.AllDay,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :execrows
UPDATE RAC_appointments
SET title = $2,
	description = $3,
	location = $4,
	meeting_link = $5,
	start_time = $6,
	end_time = $7,
	all_day = $8,
	updated_at = $9
WHERE id = $1 AND organization_id = $10
`

type UpdateAppointmentParams struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	Location       pgtype.Text        `json:"location"`
	MeetingLink    pgtype.Text        `json:"meeting_link"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	AllDay         bool               `json:"all_day"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppointment,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.MeetingLink,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.UpdatedAt,
		arg.OrganizationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :execrows
UPDATE RAC_appointments
SET status = $3, updated_at = $4
WHERE id = $1 AND organization_id = $2
`

type UpdateAppointmentStatusParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Status         string             `json:"status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppointmentStatus,
		arg.ID,
		arg.OrganizationID,
		arg.Status,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAvailabilityOverride = `-- name: UpdateAvailabilityOverride :one
UPDATE RAC_appointment_availability_overrides
SET date = $3,
	is_available = $4,
	start_time = $5,
	end_time = $6,
	timezone = $7,
	updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, user_id, date, is_available, start_time, end_time, timezone, created_at, updated_at
`

type UpdateAvailabilityOverrideParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Date           pgtype.Date `json:"date"`
	IsAvailable    bool        `json:"is_available"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	Timezone       string      `json:"timezone"`
}

type UpdateAvailabilityOverrideRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Date           pgtype.Date        `json:"date"`
	IsAvailable    bool               `json:"is_available"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAvailabilityOverride(ctx context.Context, arg UpdateAvailabilityOverrideParams) (UpdateAvailabilityOverrideRow, error) {
	row := q.db.QueryRow(ctx, updateAvailabilityOverride,
		arg.ID,
		arg.OrganizationID,
		arg.Date,
		arg.IsAvailable,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i UpdateAvailabilityOverrideRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Date,
		&i.IsAvailable,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAvailabilityRule = `-- name: UpdateAvailabilityRule :one
UPDATE RAC_appointment_availability_rules
SET weekday = $3,
	start_time = $4,
	end_time = $5,
	timezone = $6,
	updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, user_id, weekday, start_time, end_time, timezone, created_at, updated_at
`

type UpdateAvailabilityRuleParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Weekday        int16       `json:"weekday"`
	StartTime      pgtype.Time `json:"start_time"`
	EndTime        pgtype.Time `json:"end_time"`
	Timezone       string      `json:"timezone"`
}

type UpdateAvailabilityRuleRow struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Weekday        int16              `json:"weekday"`
	StartTime      pgtype.Time        `json:"start_time"`
	EndTime        pgtype.Time        `json:"end_time"`
	Timezone       string             `json:"timezone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAvailabilityRule(ctx context.Context, arg UpdateAvailabilityRuleParams) (UpdateAvailabilityRuleRow, error) {
	row := q.db.QueryRow(ctx, updateAvailabilityRule,
		arg.ID,
		arg.OrganizationID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i UpdateAvailabilityRuleRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppointmentVisitReport = `-- name: UpsertAppointmentVisitReport :one
INSERT INTO RAC_appointment_visit_reports
	(appointment_id, organization_id, measurements, measurement_products, access_difficulty, notes, created_at, updated_at)
VALUES
	($1, $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (appointment_id)
DO UPDATE SET
	measurements = EXCLUDED.measurements,
	measurement_products = EXCLUDED.measurement_products,
	access_difficulty = EXCLUDED.access_difficulty,
	notes = EXCLUDED.notes,
	updated_at = now()
RETURNING appointment_id, organization_id, measurements, measurement_products, access_difficulty, notes, created_at, updated_at
`

type UpsertAppointmentVisitReportParams struct {
	AppointmentID       pgtype.UUID `json:"appointment_id"`
	OrganizationID      pgtype.UUID `json:"organization_id"`
	Measurements        pgtype.Text `json:"measurements"`
	MeasurementProducts []byte      `json:"measurement_products"`
	AccessDifficulty    pgtype.Text `json:"access_difficulty"`
	Notes               pgtype.Text `json:"notes"`
}

type UpsertAppointmentVisitReportRow struct {
	AppointmentID       pgtype.UUID        `json:"appointment_id"`
	OrganizationID      pgtype.UUID        `json:"organization_id"`
	Measurements        pgtype.Text        `json:"measurements"`
	MeasurementProducts []byte             `json:"measurement_products"`
	AccessDifficulty    pgtype.Text        `json:"access_difficulty"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAppointmentVisitReport(ctx context.Context, arg UpsertAppointmentVisitReportParams) (UpsertAppointmentVisitReportRow, error) {
	row := q.db.QueryRow(ctx, upsertAppointmentVisitReport,
		arg.AppointmentID,
		arg.OrganizationID,
		arg.Measurements,
		arg.MeasurementProducts,
		arg.AccessDifficulty,
		arg.Notes,
	)
	var i UpsertAppointmentVisitReportRow
	err := row.Scan(
		&i.AppointmentID,
		&i.OrganizationID,
		&i.Measurements,
		&i.MeasurementProducts,
		&i.AccessDifficulty,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
