// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package searchdb

import (
	"context"
)

type Querier interface {
	GlobalSearch(ctx context.Context, arg GlobalSearchParams) ([]GlobalSearchRow, error)
}

var _ Querier = (*Queries)(nil)
