// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO RAC_refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO RAC_users (email, password_hash, is_email_verified)
VALUES ($1, $2, false)
RETURNING id, email, password_hash, is_email_verified, first_name, last_name, phone, onboarding_completed_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	Phone                 pgtype.Text        `json:"phone"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// Auth Domain SQL Queries (sqlc)
// ============================================================================
// Complexity: O(1) Time. Requires UNIQUE index on email.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserToken = `-- name: CreateUserToken :exec

INSERT INTO RAC_user_tokens (user_id, token_hash, type, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateUserTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Type      string             `json:"type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ============================================================================
// Token Management
// ============================================================================
func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) error {
	_, err := q.db.Exec(ctx, createUserToken,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.ExpiresAt,
	)
	return err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :exec

INSERT INTO RAC_webauthn_credentials (
    id, user_id, public_key, attestation_type, transport,
    flags_json, aaguid, sign_count, clone_warning, nickname
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateWebAuthnCredentialParams struct {
	ID              []byte      `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	PublicKey       []byte      `json:"public_key"`
	AttestationType string      `json:"attestation_type"`
	Transport       []string    `json:"transport"`
	FlagsJson       []byte      `json:"flags_json"`
	Aaguid          []byte      `json:"aaguid"`
	SignCount       int64       `json:"sign_count"`
	CloneWarning    bool        `json:"clone_warning"`
	Nickname        string      `json:"nickname"`
}

// ============================================================================
// WebAuthn Credential Queries
// ============================================================================
func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, createWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transport,
		arg.FlagsJson,
		arg.Aaguid,
		arg.SignCount,
		arg.CloneWarning,
		arg.Nickname,
	)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM RAC_user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM RAC_webauthn_credentials
WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     []byte      `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	return err
}

const ensureUserSettings = `-- name: EnsureUserSettings :exec

INSERT INTO RAC_user_settings (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

// ============================================================================
// User Settings & Onboarding
// ============================================================================
func (q *Queries) EnsureUserSettings(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureUserSettings, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT user_id, expires_at 
FROM RAC_refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

type GetRefreshTokenRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, is_email_verified, first_name, last_name, phone, onboarding_completed_at, created_at, updated_at 
FROM RAC_users 
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	Phone                 pgtype.Text        `json:"phone"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Complexity: O(log N) Time. Requires UNIQUE index on email.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, is_email_verified, first_name, last_name, phone, onboarding_completed_at, created_at, updated_at 
FROM RAC_users 
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	Phone                 pgtype.Text        `json:"phone"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Complexity: O(1) Time (Primary Key lookup).
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByWebAuthnCredentialID = `-- name: GetUserByWebAuthnCredentialID :one
SELECT u.id, u.email, u.password_hash, u.is_email_verified,
       u.first_name, u.last_name, u.phone, u.onboarding_completed_at,
       u.created_at, u.updated_at
FROM RAC_users u
JOIN RAC_webauthn_credentials wc ON wc.user_id = u.id
WHERE wc.id = $1
`

type GetUserByWebAuthnCredentialIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	Phone                 pgtype.Text        `json:"phone"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Complexity: O(log N) Time. Requires Primary Key index on WebAuthn id.
func (q *Queries) GetUserByWebAuthnCredentialID(ctx context.Context, id []byte) (GetUserByWebAuthnCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByWebAuthnCredentialID, id)
	var i GetUserByWebAuthnCredentialIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many

SELECT r.name 
FROM RAC_roles r
JOIN RAC_user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

// ============================================================================
// Role Management (RBAC)
// ============================================================================
func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT preferred_language AS preferredLanguage
FROM RAC_user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var preferredlanguage string
	err := row.Scan(&preferredlanguage)
	return preferredlanguage, err
}

const getUserToken = `-- name: GetUserToken :one
SELECT user_id, expires_at 
FROM RAC_user_tokens
WHERE token_hash = $1 AND type = $2 AND used_at IS NULL
`

type GetUserTokenParams struct {
	TokenHash string `json:"token_hash"`
	Type      string `json:"type"`
}

type GetUserTokenRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Complexity: O(log N) Time. Requires Index on (token_hash, type) WHERE used_at IS NULL.
func (q *Queries) GetUserToken(ctx context.Context, arg GetUserTokenParams) (GetUserTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserToken, arg.TokenHash, arg.Type)
	var i GetUserTokenRow
	err := row.Scan(&i.UserID, &i.ExpiresAt)
	return i, err
}

const getValidRoles = `-- name: GetValidRoles :many
SELECT name FROM RAC_roles WHERE name = ANY($1::text[])
`

func (q *Queries) GetValidRoles(ctx context.Context, rolenames []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getValidRoles, rolenames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebAuthnCredential = `-- name: GetWebAuthnCredential :one
SELECT id, user_id, public_key, attestation_type, transport,
       flags_json, aaguid, sign_count, clone_warning, nickname,
       created_at, last_used_at
FROM RAC_webauthn_credentials
WHERE id = $1
`

func (q *Queries) GetWebAuthnCredential(ctx context.Context, id []byte) (RacWebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredential, id)
	var i RacWebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transport,
		&i.FlagsJson,
		&i.Aaguid,
		&i.SignCount,
		&i.CloneWarning,
		&i.Nickname,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertUserRoles = `-- name: InsertUserRoles :exec
INSERT INTO RAC_user_roles (user_id, role_id)
SELECT $1, id FROM RAC_roles WHERE name = ANY($2::text[])
`

type InsertUserRolesParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 []string    `json:"column_2"`
}

func (q *Queries) InsertUserRoles(ctx context.Context, arg InsertUserRolesParams) error {
	_, err := q.db.Exec(ctx, insertUserRoles, arg.UserID, arg.Column2)
	return err
}

const listUsers = `-- name: ListUsers :many

SELECT
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    COALESCE(array_agg(r.name) FILTER (WHERE r.name IS NOT NULL), ARRAY[]::text[])::text[] AS roles
FROM RAC_users u
LEFT JOIN RAC_user_roles ur ON ur.user_id = u.id
LEFT JOIN RAC_roles r ON r.id = ur.role_id
GROUP BY u.id
ORDER BY u.email
`

type ListUsersRow struct {
	ID        pgtype.UUID `json:"id"`
	Email     string      `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Roles     []string    `json:"roles"`
}

// ============================================================================
// Bulk Read Operations (WARNING: O(N) Complexity Risks)
// ============================================================================
// WARNING: This requires pagination (LIMIT/OFFSET) in V2 to prevent memory exhaustion.
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    COALESCE(array_agg(r.name) FILTER (WHERE r.name IS NOT NULL), ARRAY[]::text[])::text[] AS roles
FROM RAC_organization_members om
JOIN RAC_users u ON u.id = om.user_id
LEFT JOIN RAC_user_roles ur ON ur.user_id = u.id
LEFT JOIN RAC_roles r ON r.id = ur.role_id
WHERE om.organization_id = $1
GROUP BY u.id
ORDER BY u.email
`

type ListUsersByOrganizationRow struct {
	ID        pgtype.UUID `json:"id"`
	Email     string      `json:"email"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Roles     []string    `json:"roles"`
}

func (q *Queries) ListUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListUsersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByOrganizationRow
	for rows.Next() {
		var i ListUsersByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentialsByUser = `-- name: ListWebAuthnCredentialsByUser :many
SELECT id, user_id, public_key, attestation_type, transport,
       flags_json, aaguid, sign_count, clone_warning, nickname,
       created_at, last_used_at
FROM RAC_webauthn_credentials
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListWebAuthnCredentialsByUser(ctx context.Context, userID pgtype.UUID) ([]RacWebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacWebauthnCredential
	for rows.Next() {
		var i RacWebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transport,
			&i.FlagsJson,
			&i.Aaguid,
			&i.SignCount,
			&i.CloneWarning,
			&i.Nickname,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE RAC_users 
SET is_email_verified = true, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const markOnboardingComplete = `-- name: MarkOnboardingComplete :exec
UPDATE RAC_users 
SET onboarding_completed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND onboarding_completed_at IS NULL
`

func (q *Queries) MarkOnboardingComplete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOnboardingComplete, id)
	return err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE RAC_refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE RAC_refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const touchUserUpdatedAt = `-- name: TouchUserUpdatedAt :exec
UPDATE RAC_users SET updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) TouchUserUpdatedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchUserUpdatedAt, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE RAC_users 
SET password_hash = $2, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE RAC_users
SET email = $2, is_email_verified = false, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, password_hash, is_email_verified, first_name, last_name, phone, onboarding_completed_at, created_at, updated_at
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

type UpdateUserEmailRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	Phone                 pgtype.Text        `json:"phone"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Security: Implicitly resets is_email_verified to false to prevent account takeover.
func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserNames = `-- name: UpdateUserNames :one
UPDATE RAC_users
SET first_name = $2, last_name = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, password_hash, is_email_verified, first_name, last_name, phone, onboarding_completed_at, created_at, updated_at
`

type UpdateUserNamesParams struct {
	ID        pgtype.UUID `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}

type UpdateUserNamesRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	Phone                 pgtype.Text        `json:"phone"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserNames(ctx context.Context, arg UpdateUserNamesParams) (UpdateUserNamesRow, error) {
	row := q.db.QueryRow(ctx, updateUserNames, arg.ID, arg.FirstName, arg.LastName)
	var i UpdateUserNamesRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE RAC_users
SET phone = NULLIF(BTRIM($2::text), ''),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, password_hash, is_email_verified, first_name, last_name, phone, onboarding_completed_at, created_at, updated_at
`

type UpdateUserPhoneParams struct {
	ID    pgtype.UUID `json:"id"`
	Phone string      `json:"phone"`
}

type UpdateUserPhoneRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	IsEmailVerified       bool               `json:"is_email_verified"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	Phone                 pgtype.Text        `json:"phone"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Optimization: Eliminated verbose CASE/WHEN block. NULLIF(TRIM()) safely coalesces empty/whitespace strings to NULL.
func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (UpdateUserPhoneRow, error) {
	row := q.db.QueryRow(ctx, updateUserPhone, arg.ID, arg.Phone)
	var i UpdateUserPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.IsEmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.OnboardingCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebAuthnCredentialNickname = `-- name: UpdateWebAuthnCredentialNickname :exec
UPDATE RAC_webauthn_credentials
SET nickname = $2
WHERE id = $1 AND user_id = $3
`

type UpdateWebAuthnCredentialNicknameParams struct {
	ID       []byte      `json:"id"`
	Nickname string      `json:"nickname"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateWebAuthnCredentialNickname(ctx context.Context, arg UpdateWebAuthnCredentialNicknameParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialNickname, arg.ID, arg.Nickname, arg.UserID)
	return err
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE RAC_webauthn_credentials
SET sign_count = $2, clone_warning = $3, last_used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	ID           []byte `json:"id"`
	SignCount    int64  `json:"sign_count"`
	CloneWarning bool   `json:"clone_warning"`
}

// Security: Critical for clone detection during passkey login phase.
func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.ID, arg.SignCount, arg.CloneWarning)
	return err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO RAC_user_settings (user_id, preferred_language)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET preferred_language = EXCLUDED.preferred_language, updated_at = CURRENT_TIMESTAMP
`

type UpsertUserSettingsParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	PreferredLanguage string      `json:"preferred_language"`
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertUserSettings, arg.UserID, arg.PreferredLanguage)
	return err
}

const useUserToken = `-- name: UseUserToken :exec
UPDATE RAC_user_tokens 
SET used_at = CURRENT_TIMESTAMP
WHERE token_hash = $1 AND type = $2 AND used_at IS NULL
`

type UseUserTokenParams struct {
	TokenHash string `json:"token_hash"`
	Type      string `json:"type"`
}

// Security: Atomic invalidation prevents TOCTOU replay attacks on verification links.
func (q *Queries) UseUserToken(ctx context.Context, arg UseUserTokenParams) error {
	_, err := q.db.Exec(ctx, useUserToken, arg.TokenHash, arg.Type)
	return err
}
