// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package webhookdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearOrganizationGTMContainerID(ctx context.Context, id pgtype.UUID) error
	CreateGoogleWebhookConfig(ctx context.Context, arg CreateGoogleWebhookConfigParams) (pgtype.UUID, error)
	CreateWebhookAPIKey(ctx context.Context, arg CreateWebhookAPIKeyParams) (RacWebhookApiKey, error)
	CreateWebhookTimelineEvent(ctx context.Context, arg CreateWebhookTimelineEventParams) error
	DeleteGoogleCampaignMapping(ctx context.Context, arg DeleteGoogleCampaignMappingParams) error
	DeleteGoogleWebhookConfig(ctx context.Context, arg DeleteGoogleWebhookConfigParams) (int64, error)
	FindRecentDuplicateLead(ctx context.Context, arg FindRecentDuplicateLeadParams) (pgtype.UUID, error)
	GetGoogleWebhookConfigByHash(ctx context.Context, googleKeyHash string) (RacGoogleWebhookConfig, error)
	GetOrganizationGTMContainerID(ctx context.Context, id pgtype.UUID) (pgtype.Text, error)
	GetWebhookAPIKeyByHash(ctx context.Context, keyHash string) (RacWebhookApiKey, error)
	GoogleLeadIDExists(ctx context.Context, leadID string) (bool, error)
	ListGoogleWebhookConfigs(ctx context.Context, organizationID pgtype.UUID) ([]RacGoogleWebhookConfig, error)
	ListWebhookAPIKeysByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]RacWebhookApiKey, error)
	RevokeWebhookAPIKey(ctx context.Context, arg RevokeWebhookAPIKeyParams) (int64, error)
	SetOrganizationGTMContainerID(ctx context.Context, arg SetOrganizationGTMContainerIDParams) error
	StoreGoogleLeadID(ctx context.Context, arg StoreGoogleLeadIDParams) error
	UpdateGoogleLeadMetadata(ctx context.Context, arg UpdateGoogleLeadMetadataParams) error
	UpdateWebhookLeadData(ctx context.Context, arg UpdateWebhookLeadDataParams) error
	UpsertGoogleCampaignMapping(ctx context.Context, arg UpsertGoogleCampaignMappingParams) error
}

var _ Querier = (*Queries)(nil)
